use uo;
include "include/utility";

function MandrakeRoot( item )
	return CInt( GetObjProperty( item, "MandrakeRoot" ));
endfunction
function Ginsengs( item )
	return CInt( GetObjProperty( item, "Ginsengs" ));
endfunction
function Garlic( item )
	return CInt( GetObjProperty( item, "Garlic" ));
endfunction
function Nightshade( item )
	return CInt( GetObjProperty( item, "Nightshade" ));
endfunction
function SulphurousAsh( item )
	return CInt( GetObjProperty( item, "SulphurousAsh" ));
endfunction
function SpiderSilk( item )
	return CInt( GetObjProperty( item, "SpiderSilk" ));
endfunction
function BlackPearl( item )
	return CInt( GetObjProperty( item, "BlackPearl" ));
endfunction
function BloodMoss( item )
	return CInt( GetObjProperty( item, "BloodMoss" ));
endfunction
function Batwing( item )
	return CInt( GetObjProperty( item, "Batwing" ));
endfunction
function Blackmoor( item )
	return CInt( GetObjProperty( item, "Blackmoor" ));
endfunction
function Bloodspawn( item )
	return CInt( GetObjProperty( item, "Bloodspawn" ));
endfunction
function VialOfBlood( item )
	return CInt( GetObjProperty( item, "VialOfBlood" ));
endfunction
function Bone( item )
	return CInt( GetObjProperty( item, "Bone" ));
endfunction
function Brimstone( item )
	return CInt( GetObjProperty( item, "Brimstone" ));
endfunction
function DaemonBone( item )
	return CInt( GetObjProperty( item, "DaemonBone" ));
endfunction
function FertileDirt( item )
	return CInt( GetObjProperty( item, "FertileDirt" ));
endfunction
function DragonsBlood( item )
	return CInt( GetObjProperty( item, "DragonsBlood" ));
endfunction
function ExecutionersCap( item )
	return CInt( GetObjProperty( item, "ExecutionersCap" ));
endfunction
function EyeOfNewt( item )
	return CInt( GetObjProperty( item, "EyeOfNewt" ));
endfunction
function Obsidian( item )
	return CInt( GetObjProperty( item, "Obsidian" ));
endfunction
function PigIron( item )
	return CInt( GetObjProperty( item, "PigIron" ));
endfunction
function Pumice( item )
	return CInt( GetObjProperty( item, "Pumice" ));
endfunction
function SerpentsScales( item )
	return CInt( GetObjProperty( item, "SerpentsScales" ));
endfunction
function VolcanicAsh( item )
	return CInt( GetObjProperty( item, "VolcanicAsh" ));
endfunction
function Deadwood( item )
	return CInt( GetObjProperty( item, "Deadwood" ));
endfunction
function WormsHeart( item )
	return CInt( GetObjProperty( item, "WormsHeart" ));
endfunction
function Starsapphire( item )
	return CInt( GetObjProperty( item, "Starsapphire" ));
endfunction
function Emerald( item )
	return CInt( GetObjProperty( item, "Emerald" ));
endfunction
function Sapphire( item )
	return CInt( GetObjProperty( item, "Sapphire" ));
endfunction
function Ruby( item )
	return CInt( GetObjProperty( item, "Ruby" ));
endfunction
function Citrine( item )
	return CInt( GetObjProperty( item, "Citrine" ));
endfunction
function Amethyst( item )
	return CInt( GetObjProperty( item, "Amethyst" ));
endfunction
function Tourmaline( item )
	return CInt( GetObjProperty( item, "Tourmaline" ));
endfunction
function Amber( item )
	return CInt( GetObjProperty( item, "Amber" ));
endfunction
function Diamond( item )
	return CInt( GetObjProperty( item, "Diamond" ));
endfunction
function IronIngot( item )
	return CInt( GetObjProperty( item, "IronIngot" ));
endfunction
function SilverIngot( item )
	return CInt( GetObjProperty( item, "SilverIngot" ));
endfunction
function BloodIngot( item )
	return CInt( GetObjProperty( item, "BloodIngot" ));
endfunction
function DestrIngot( item )
	return CInt( GetObjProperty( item, "DestrIngot" ));
endfunction
function OnyxIngot( item )
	return CInt( GetObjProperty( item, "OnyxIngot" ));
endfunction
function MalachiteIngot( item )
	return CInt( GetObjProperty( item, "MalachiteIngot" ));
endfunction
function LavaRockIngot( item )
	return CInt( GetObjProperty( item, "LavaRockIngot" ));
endfunction
function DripstoneIngot( item )
	return CInt( GetObjProperty( item, "DripstoneIngot" ));
endfunction
function CrystalIngot( item )
	return CInt( GetObjProperty( item, "CrystalIngot" ));
endfunction
function GoddessIngot( item )
	return CInt( GetObjProperty( item, "GoddessIngot" ));
endfunction
function DoomIngot( item )
	return CInt( GetObjProperty( item, "DoomIngot" ));
endfunction
function PlatinumIngot( item )
	return CInt( GetObjProperty( item, "PlatinumIngot" ));
endfunction
function NewZuluIngot( item )
	return CInt( GetObjProperty( item, "NewZuluIngot" ));
endfunction
function EboonIngot( item )
	return CInt( GetObjProperty( item, "EboonIngot" ));
endfunction
function DarkSableIngot( item )
	return CInt( GetObjProperty( item, "DarkSableIngot" ));
endfunction
function RadiantNimbusIngot( item )
	return CInt( GetObjProperty( item, "RadiantNimbusIngot" ));
endfunction

function boltofcloth( item )
	return CInt( GetObjProperty( item, "boltofcloth" ));
endfunction
function cloth( item )
	return CInt( GetObjProperty( item, "cloth" ));
endfunction
function wool( item )
	return CInt( GetObjProperty( item, "wool" ));
endfunction
function clay( item )
	return CInt( GetObjProperty( item, "clay" ));
endfunction
function goldingot( item )
	return CInt( GetObjProperty( item, "goldingot" ));
endfunction


function hides( item )
	return CInt( GetObjProperty( item, "hides" ));
endfunction
function lizardhide( item )
	return CInt( GetObjProperty( item, "lizardhide" ));
endfunction
function orchide( item )
	return CInt( GetObjProperty( item, "orchide" ));
endfunction
function trollhide( item )
	return CInt( GetObjProperty( item, "trollhide" ));
endfunction
function terathanhide( item )
	return CInt( GetObjProperty( item, "terathanhide" ));
endfunction
function bearhide( item )
	return CInt( GetObjProperty( item, "bearhide" ));
endfunction
function icehide( item )
	return CInt( GetObjProperty( item, "icehide" ));
endfunction
function lichehide( item )
	return CInt( GetObjProperty( item, "lichehide" ));
endfunction
function daemonhide( item )
	return CInt( GetObjProperty( item, "daemonhide" ));
endfunction
function balronhide( item )
	return CInt( GetObjProperty( item, "balronhide" ));
endfunction

function rathide( item )
	return CInt( GetObjProperty( item, "rathide" ));
endfunction
function dragonhide( item )
	return CInt( GetObjProperty( item, "dragonhide" ));
endfunction
function greatwyrmhide( item )
	return CInt( GetObjProperty( item, "greatwyrmhide" ));
endfunction
function wyrmhide( item )
	return CInt( GetObjProperty( item, "wyrmhide" ));
endfunction
function celestialhide( item )
	return CInt( GetObjProperty( item, "celestialhide" ));
endfunction
function Goldendragonhide( item )
	return CInt( GetObjProperty( item, "Goldendragonhide" ));
endfunction

function logs( item )
	return CInt( GetObjProperty( item, "logs" ));
endfunction
function silverleaflog( item )
	return CInt( GetObjProperty( item, "silverleaflog" ));
endfunction
function emeraldlog( item )
	return CInt( GetObjProperty( item, "emeraldlog" ));
endfunction
function swamplog( item )
	return CInt( GetObjProperty( item, "swamplog" ));
endfunction
function oaklog( item )
	return CInt( GetObjProperty( item, "oaklog" ));
endfunction
function stardustlog( item )
	return CInt( GetObjProperty( item, "stardustlog" ));
endfunction
function jadelog( item )
	return CInt( GetObjProperty( item, "jadelog" ));
endfunction
function darkwoodlog( item )
	return CInt( GetObjProperty( item, "darkwoodlog" ));
endfunction
function goldenreflectionlog( item )
	return CInt( GetObjProperty( item, "goldenreflectionlog" ));
endfunction
function doomlog( item )
	return CInt( GetObjProperty( item, "doomlog" ));
endfunction
function bloodhorselog( item )
	return CInt( GetObjProperty( item, "bloodhorselog" ));
endfunction
function yewlogs( item )
	return CInt( GetObjProperty( item, "yewlog" ));
endfunction
function darknesslog( item )
	return CInt( GetObjProperty( item, "darknesslog" ));
endfunction
function elvenlog( item )
	return CInt( GetObjProperty( item, "elvenlog" ));
endfunction
function glass( item )
	return CInt( GetObjProperty( item, "glass" ));
endfunction

function bottleofliquor( item )
	return CInt( GetObjProperty( item, "bottleofliquor" ));
endfunction
function bottleofale( item )
	return CInt( GetObjProperty( item, "bottleofale" ));
endfunction
function bottleofwine( item )
	return CInt( GetObjProperty( item, "bottleofwine" ));
endfunction
function pitcherofale( item )
	return CInt( GetObjProperty( item, "pitcherofale" ));
endfunction
function pitcherofcider( item )
	return CInt( GetObjProperty( item, "pitcherofcider" ));
endfunction
function pitcherofliquor( item )
	return CInt( GetObjProperty( item, "pitcherofliquor" ));
endfunction
function pitcherofwine( item )
	return CInt( GetObjProperty( item, "pitcherofwine" ));
endfunction
function pitcherofwater( item )
	return CInt( GetObjProperty( item, "pitcherofwater" ));
endfunction
function pitcherofmilk( item )
	return CInt( GetObjProperty( item, "pitcherofmilk" ));
endfunction
function glassofliquor( item )
	return CInt( GetObjProperty( item, "glassofliquor" ));
endfunction
function mugofale( item )
	return CInt( GetObjProperty( item, "mugofale" ));
endfunction
function glassofwine( item )
	return CInt( GetObjProperty( item, "glassofwine" ));
endfunction
function glassofcider( item )
	return CInt( GetObjProperty( item, "glassofcider" ));
endfunction
function glassofmilk( item )
	return CInt( GetObjProperty( item, "glassofmilk" ));
endfunction
function glassofwater( item )
	return CInt( GetObjProperty( item, "glassofwater" ));
endfunction
function flour( item )
	return CInt( GetObjProperty( item, "flour" ));
endfunction
function rawrib( item )
	return CInt( GetObjProperty( item, "rawrib" ));
endfunction
function rawfishsteak( item )
	return CInt( GetObjProperty( item, "rawfishsteak" ));
endfunction
function rawbird( item )
	return CInt( GetObjProperty( item, "rawbird" ));
endfunction
function rawham( item )
	return CInt( GetObjProperty( item, "rawham" ));
endfunction
function huntpoints( item )
	return CInt( GetObjProperty( item, "huntpoints" ));
endfunction
function slabofbacon( item )
	return CInt( GetObjProperty( item, "slabofbacon" ));
endfunction
function lard( item )
	return CInt( GetObjProperty( item, "lard" ));
endfunction
function rawchickenleg( item )
	return CInt( GetObjProperty( item, "rawchickenleg" ));
endfunction
function rawlegoflamb( item )
	return CInt( GetObjProperty( item, "rawlegoflamb" ));
endfunction
function honey( item )
	return CInt( GetObjProperty( item, "honey" ));
endfunction
function coconut( item )
	return CInt( GetObjProperty( item, "coconut" ));
endfunction
function pizzacrust( item )
	return CInt( GetObjProperty( item, "pizzacrust" ));
endfunction
function piecrust( item )
	return CInt( GetObjProperty( item, "piecrust" ));
endfunction
function fish2( item )
	return CInt( GetObjProperty( item, "fish2" ));
endfunction
function fish3( item )
	return CInt( GetObjProperty( item, "fish3" ));
endfunction
function fish4( item )
	return CInt( GetObjProperty( item, "fish4" ));
endfunction
function wheelofcheese( item )
	return CInt( GetObjProperty( item, "wheelofcheese" ));
endfunction
function friedchickenleg( item )
	return CInt( GetObjProperty( item, "friedchickenleg" ));
endfunction
function cookedlegoflamb( item )
	return CInt( GetObjProperty( item, "cookedlegoflamb" ));
endfunction
function sushi( item )
	return CInt( GetObjProperty( item, "sushi" ));
endfunction
function CookedFishSteak( item )
	return CInt( GetObjProperty( item, "CookedFishSteak" ));
endfunction
function smokedsalmon( item )
	return CInt( GetObjProperty( item, "smokedsalmon" ));
endfunction
function cookedbird( item )
	return CInt( GetObjProperty( item, "cookedbird" ));
endfunction
function CookedRib( item )
	return CInt( GetObjProperty( item, "CookedRib" ));
endfunction
function magicfish1( item )
	return CInt( GetObjProperty( item, "magicfish1" ));
endfunction
function magicfish2( item )
	return CInt( GetObjProperty( item, "magicfish2" ));
endfunction
function magicfish3( item )
	return CInt( GetObjProperty( item, "magicfish3" ));
endfunction
function magicfish4( item )
	return CInt( GetObjProperty( item, "magicfish4" ));
endfunction
function magicfish5( item )
	return CInt( GetObjProperty( item, "magicfish5" ));
endfunction
function magicfish6( item )
	return CInt( GetObjProperty( item, "magicfish6" ));
endfunction
function magicfish7( item )
	return CInt( GetObjProperty( item, "magicfish7" ));
endfunction
function magicfish8( item )
	return CInt( GetObjProperty( item, "magicfish8" ));
endfunction
function pancakes( item )
	return CInt( GetObjProperty( item, "pancakes" ));
endfunction
function mincemeatpie( item )
	return CInt( GetObjProperty( item, "mincemeatpie" ));
endfunction
function chickenpotpie( item )
	return CInt( GetObjProperty( item, "chickenpotpie" ));
endfunction
function lemonherbfish( item )
	return CInt( GetObjProperty( item, "lemonherbfish" ));
endfunction
function onion( item )
	return CInt( GetObjProperty( item, "onion" ));
endfunction
function Goldcoin( item )
	return CInt( GetObjProperty( item, "Goldcoin" ));
endfunction
function zulucoin( item )
	return CInt( GetObjProperty( item, "zulucoin" ));
endfunction
function ammoarrow( item )
	return CInt( GetObjProperty( item, "ammoarrow" ));
endfunction
function ammobolt( item )
	return CInt( GetObjProperty( item, "ammobolt" ));
endfunction
function ammofire( item )
	return CInt( GetObjProperty( item, "ammofire" ));
endfunction
function ammoice( item )
	return CInt( GetObjProperty( item, "ammoice" ));
endfunction
function ammothunder( item )
	return CInt( GetObjProperty( item, "ammothunder" ));
endfunction
function ammothrow( item )
	return CInt( GetObjProperty( item, "ammothrow" ));
endfunction
function ammogun( item )
	return CInt( GetObjProperty( item, "ammogun" ));
endfunction
function ammoshaft( item )
	return CInt( GetObjProperty( item, "ammoshaft" ));
endfunction
function ammofeather( item )
	return CInt( GetObjProperty( item, "ammofeather" ));
endfunction
function LHEALPOTION( item )
	return CInt( GetObjProperty( item, "LHEALPOTION" ));
endfunction
function HEALPOTION( item )
	return CInt( GetObjProperty( item, "HEALPOTION" ));
endfunction
function GHEALPOTION( item )
	return CInt( GetObjProperty( item, "GHEALPOTION" ));
endfunction
function LPOISONPOTION( item )
	return CInt( GetObjProperty( item, "LPOISONPOTION" ));
endfunction
function POISONPOTION( item )
	return CInt( GetObjProperty( item, "POISONPOTION" ));
endfunction
function GRPOISONPOTION( item )
	return CInt( GetObjProperty( item, "GRPOISONPOTION" ));
endfunction
function GREXPLOSIONPOTION( item )
	return CInt( GetObjProperty( item, "GREXPLOSIONPOTION" ));
endfunction
function LEXPLOSIONPOTION( item )
	return CInt( GetObjProperty( item, "LEXPLOSIONPOTION" ));
endfunction
function EXPLOSIONPOTION( item )
	return CInt( GetObjProperty( item, "EXPLOSIONPOTION" ));
endfunction
function LAGILITYPOTION( item )
	return CInt( GetObjProperty( item, "LAGILITYPOTION" ));
endfunction
function AGILITYPOTION( item )
	return CInt( GetObjProperty( item, "AGILITYPOTION" ));
endfunction
function GRAGILITYPOTION( item )
	return CInt( GetObjProperty( item, "GRAGILITYPOTION" ));
endfunction
function REFRESHPOTION( item )
	return CInt( GetObjProperty( item, "REFRESHPOTION" ));
endfunction
function FULLREFRESHPOTION( item )
	return CInt( GetObjProperty( item, "FULLREFRESHPOTION" ));
endfunction
function LSTRENGTHPOTION( item )
	return CInt( GetObjProperty( item, "LSTRENGTHPOTION" ));
endfunction
function STRENGTHPOTION( item )
	return CInt( GetObjProperty( item, "STRENGTHPOTION" ));
endfunction
function GRSTRENGTHPOTION( item )
	return CInt( GetObjProperty( item, "GRSTRENGTHPOTION" ));
endfunction
function LCUREPOTION( item )
	return CInt( GetObjProperty( item, "LCUREPOTION" ));
endfunction
function CUREPOTION( item )
	return CInt( GetObjProperty( item, "CUREPOTION" ));
endfunction
function GRCUREPOTION( item )
	return CInt( GetObjProperty( item, "GRCUREPOTION" ));
endfunction
function DEDLYPOISONPOTION( item )
	return CInt( GetObjProperty( item, "DEDLYPOISONPOTION" ));
endfunction
function LMINDPOTION( item )
	return CInt( GetObjProperty( item, "LMINDPOTION" ));
endfunction
function MINDPOTION( item )
	return CInt( GetObjProperty( item, "MINDPOTION" ));
endfunction
function GMINDPOTION( item )
	return CInt( GetObjProperty( item, "GMINDPOTION" ));
endfunction
function InvisibilityPotion( item )
	return CInt( GetObjProperty( item, "InvisibilityPotion" ));
endfunction
function FineIntellect( item )
	return CInt( GetObjProperty( item, "FineIntellect" ));
endfunction
function FabulousIntellect( item )
	return CInt( GetObjProperty( item, "FabulousIntellect" ));
endfunction
function FantasticIntellect( item )
	return CInt( GetObjProperty( item, "FantasticIntellect" ));
endfunction
function lesserMegoInvul( item )
	return CInt( GetObjProperty( item, "lesserMegoInvul" ));
endfunction
function MegoInvulnerabilitypotion( item )
	return CInt( GetObjProperty( item, "MegoInvulnerabilitypotion" ));
endfunction
function greaterMegoInvulnerabilitypotion( item )
	return CInt( GetObjProperty( item, "greaterMegoInvulnerabilitypotion" ));
endfunction
function GrandMageRefreshElixir( item )
	return CInt( GetObjProperty( item, "GrandMageRefreshElixir" ));
endfunction
function HomericMightpotion( item )
	return CInt( GetObjProperty( item, "HomericMightpotion" ));
endfunction
function GreaterHomericMightpotion( item )
	return CInt( GetObjProperty( item, "GreaterHomericMightpotion" ));
endfunction
function TamlaHealpotion( item )
	return CInt( GetObjProperty( item, "TamlaHealpotion" ));
endfunction
function MinorTransmutation( item )
	return CInt( GetObjProperty( item, "MinorTransmutation" ));
endfunction
function MajorTransmutation( item )
	return CInt( GetObjProperty( item, "MajorTransmutation" ));
endfunction
function Totem( item )
	return CInt( GetObjProperty( item, "Totem" ));
endfunction
function Elixer( item )
	return CInt( GetObjProperty( item, "Elixer" ));
endfunction
function GreatElixerium( item )
	return CInt( GetObjProperty( item, "GreatElixerium" ));
endfunction
function MegoElixerium( item )
	return CInt( GetObjProperty( item, "MegoElixerium" ));
endfunction
function DispelPotion( item )
	return CInt( GetObjProperty( item, "DispelPotion" ));
endfunction
function Antidotescroll( item )
	return CInt( GetObjProperty( item, "Antidotescroll" ));
endfunction
function Owlsightscroll( item )
	return CInt( GetObjProperty( item, "Owlsightscroll" ));
endfunction
function Shiftingearthscroll( item )
	return CInt( GetObjProperty( item, "Shiftingearthscroll" ));
endfunction
function Summonmammalsscroll( item )
	return CInt( GetObjProperty( item, "Summonmammalsscroll" ));
endfunction
function Calllightningscroll( item )
	return CInt( GetObjProperty( item, "Calllightningscroll" ));
endfunction
function Earthblessingscroll( item )
	return CInt( GetObjProperty( item, "Earthblessingscroll" ));
endfunction
function Earthportalscroll( item )
	return CInt( GetObjProperty( item, "Earthportalscroll" ));
endfunction
function Naturestouchscroll( item )
	return CInt( GetObjProperty( item, "Naturestouchscroll" ));
endfunction
function Gustofairscroll( item )
	return CInt( GetObjProperty( item, "Gustofairscroll" ));
endfunction
function Risingfirescroll( item )
	return CInt( GetObjProperty( item, "Risingfirescroll" ));
endfunction
function Shapeshiftscroll( item )
	return CInt( GetObjProperty( item, "Shapeshiftscroll" ));
endfunction
function Icestrikescroll( item )
	return CInt( GetObjProperty( item, "Icestrikescroll" ));
endfunction
function Earthspiritscroll( item )
	return CInt( GetObjProperty( item, "Earthspiritscroll" ));
endfunction
function Flamespiritscroll( item )
	return CInt( GetObjProperty( item, "Flamespiritscroll" ));
endfunction
function Stormspiritscroll( item )
	return CInt( GetObjProperty( item, "Stormspiritscroll" ));
endfunction
function Waterspiritscroll( item )
	return CInt( GetObjProperty( item, "Waterspiritscroll" ));
endfunction
function ControlUndeadScroll( item )
	return CInt( GetObjProperty( item, "ControlUndeadScroll" ));
endfunction
function DarknessScroll( item )
	return CInt( GetObjProperty( item, "DarknessScroll" ));
endfunction
function DecayingRayScroll( item )
	return CInt( GetObjProperty( item, "DecayingRayScroll" ));
endfunction
function SpectresTouchScroll( item )
	return CInt( GetObjProperty( item, "SpectresTouchScroll" ));
endfunction
function AbyssalFlameScroll( item )
	return CInt( GetObjProperty( item, "AbyssalFlameScroll" ));
endfunction
function AnimateDeadScroll( item )
	return CInt( GetObjProperty( item, "AnimateDeadScroll" ));
endfunction
function SacrificeScroll( item )
	return CInt( GetObjProperty( item, "SacrificeScroll" ));
endfunction
function WraithsBreathScroll( item )
	return CInt( GetObjProperty( item, "WraithsBreathScroll" ));
endfunction
function SorcerersBaneScroll( item )
	return CInt( GetObjProperty( item, "SorcerersBaneScroll" ));
endfunction
function SummonSpiritScroll( item )
	return CInt( GetObjProperty( item, "SummonSpiritScroll" ));
endfunction
function WraithformScroll( item )
	return CInt( GetObjProperty( item, "WraithformScroll" ));
endfunction
function WyvernStrikeScroll( item )
	return CInt( GetObjProperty( item, "WyvernStrikeScroll" ));
endfunction
function KillScroll( item )
	return CInt( GetObjProperty( item, "KillScroll" ));
endfunction
function LicheScroll( item )
	return CInt( GetObjProperty( item, "LicheScroll" ));
endfunction
function PlagueScroll( item )
	return CInt( GetObjProperty( item, "PlagueScroll" ));
endfunction
function SpellbindScroll( item )
	return CInt( GetObjProperty( item, "SpellbindScroll" ));
endfunction
function songscroll1( item )
	return CInt( GetObjProperty( item, "songscroll1" ));
endfunction
function songscroll2( item )
	return CInt( GetObjProperty( item, "songscroll2" ));
endfunction
function songscroll3( item )
	return CInt( GetObjProperty( item, "songscroll3" ));
endfunction
function songscroll4( item )
	return CInt( GetObjProperty( item, "songscroll4" ));
endfunction
function songscroll5( item )
	return CInt( GetObjProperty( item, "songscroll5" ));
endfunction
function songscroll6( item )
	return CInt( GetObjProperty( item, "songscroll6" ));
endfunction
function songscroll7( item )
	return CInt( GetObjProperty( item, "songscroll7" ));
endfunction
function songscroll8( item )
	return CInt( GetObjProperty( item, "songscroll8" ));
endfunction
function songscroll9( item )
	return CInt( GetObjProperty( item, "songscroll9" ));
endfunction
function songscroll10( item )
	return CInt( GetObjProperty( item, "songscroll10" ));
endfunction
function songscroll11( item )
	return CInt( GetObjProperty( item, "songscroll11" ));
endfunction
function songscroll12( item )
	return CInt( GetObjProperty( item, "songscroll12" ));
endfunction
function songscroll13( item )
	return CInt( GetObjProperty( item, "songscroll13" ));
endfunction
function songscroll14( item )
	return CInt( GetObjProperty( item, "songscroll14" ));
endfunction
function songscroll15( item )
	return CInt( GetObjProperty( item, "songscroll15" ));
endfunction
function songscroll16( item )
	return CInt( GetObjProperty( item, "songscroll16" ));
endfunction
function songscroll17( item )
	return CInt( GetObjProperty( item, "songscroll17" ));
endfunction
function songscroll18( item )
	return CInt( GetObjProperty( item, "songscroll18" ));
endfunction
function songscroll19( item )
	return CInt( GetObjProperty( item, "songscroll19" ));
endfunction
function songscroll20( item )
	return CInt( GetObjProperty( item, "songscroll20" ));
endfunction
function holyscroll1( item )
	return CInt( GetObjProperty( item, "holyscroll1" ));
endfunction
function holyscroll2( item )
	return CInt( GetObjProperty( item, "holyscroll2" ));
endfunction
function holyscroll3( item )
	return CInt( GetObjProperty( item, "holyscroll3" ));
endfunction
function holyscroll4( item )
	return CInt( GetObjProperty( item, "holyscroll4" ));
endfunction
function holyscroll5( item )
	return CInt( GetObjProperty( item, "holyscroll5" ));
endfunction
function holyscroll6( item )
	return CInt( GetObjProperty( item, "holyscroll6" ));
endfunction
function holyscroll7( item )
	return CInt( GetObjProperty( item, "holyscroll7" ));
endfunction
function holyscroll8( item )
	return CInt( GetObjProperty( item, "holyscroll8" ));
endfunction
function holyscroll9( item )
	return CInt( GetObjProperty( item, "holyscroll9" ));
endfunction
function blankscroll( item )
	return CInt( GetObjProperty( item, "blankscroll" ));
endfunction
function blankmap( item )
	return CInt( GetObjProperty( item, "blankmap" ));
endfunction
function lockpick( item )
	return CInt( GetObjProperty( item, "lockpick" ));
endfunction
function emptybottle( item )
	return CInt( GetObjProperty( item, "emptybottle" ));
endfunction
function recallrune( item )
	return CInt( GetObjProperty( item, "recallrune" ));
endfunction
function kindling( item )
	return CInt( GetObjProperty( item, "kindling" ));
endfunction
function bandages( item )
	return CInt( GetObjProperty( item, "bandages" ));
endfunction
function SymbolOfAbsorption( item )
	return CInt( GetObjProperty( item, "SymbolOfAbsorption" ));
endfunction
function SymbolOfToxinsResistance( item )
	return CInt( GetObjProperty( item, "SymbolOfToxinsResistance" ));
endfunction
function SymbolOfHealth( item )
	return CInt( GetObjProperty( item, "SymbolOfHealth" ));
endfunction
function SymbolOfHeavenTouch( item )
	return CInt( GetObjProperty( item, "SymbolOfHeavenTouch" ));
endfunction
function SymbolOfHellFire( item )
	return CInt( GetObjProperty( item, "SymbolOfHellFire" ));
endfunction
function SymbolOfVanishing( item )
	return CInt( GetObjProperty( item, "SymbolOfVanishing" ));
endfunction
function SymbolOfVengeance( item )
	return CInt( GetObjProperty( item, "SymbolOfVengeance" ));
endfunction
function SymbolOfRecalling( item )
	return CInt( GetObjProperty( item, "SymbolOfRecalling" ));
endfunction
function SymbolOfThunderStorm( item )
	return CInt( GetObjProperty( item, "SymbolOfThunderStorm" ));
endfunction
function SymbolOfRegeneration( item )
	return CInt( GetObjProperty( item, "SymbolOfRegeneration" ));
endfunction
function SymbolOfLifeStream( item )
	return CInt( GetObjProperty( item, "SymbolOfLifeStream" ));
endfunction
function castspeedupgrade( item )
	return CInt( GetObjProperty( item, "castspeedupgrade" ));
endfunction
function hitupgrade( item )
	return CInt( GetObjProperty( item, "hitupgrade" ));
endfunction
function damagebonus( item )
	return CInt( GetObjProperty( item, "damagebonus" ));
endfunction
function armorupgrade( item )
	return CInt( GetObjProperty( item, "armorupgrade" ));
endfunction
function weapondmgupgrade( item )
	return CInt( GetObjProperty( item, "damagebonusPhys" ));
endfunction
function crystallballs( item )
	return CInt( GetObjProperty( item, "CrystalBall" ));
endfunction

function store_collection_item(who, what, item)
	case (what.objtype)
	0x0F91:
		if (GetObjProperty(item, "WormsHeart"))
			SetObjProperty(item,"WormsHeart",GetObjProperty(item,"WormsHeart") + CINT(what.amount));
		else
			SetObjProperty(item, "WormsHeart",CINT(what.amount));
		endif 
	0x0F90:
		if (GetObjProperty(item, "Deadwood"))
			SetObjProperty(item,"Deadwood",GetObjProperty(item,"Deadwood") + CINT(what.amount));
		else
			SetObjProperty(item, "Deadwood",CINT(what.amount));
		endif 
	0x0F8F:
		if (GetObjProperty(item, "VolcanicAsh"))
			SetObjProperty(item,"VolcanicAsh",GetObjProperty(item,"VolcanicAsh") + CINT(what.amount));
		else
			SetObjProperty(item, "VolcanicAsh",CINT(what.amount));
		endif 
	0x0F8E:
		if (GetObjProperty(item, "SerpentsScales"))
			SetObjProperty(item,"SerpentsScales",GetObjProperty(item,"SerpentsScales") +CINT(what.amount));
		else
			SetObjProperty(item, "SerpentsScales",CINT(what.amount));
		endif 
	0x0F8B:
		if (GetObjProperty(item, "Pumice"))
			SetObjProperty(item,"Pumice",GetObjProperty(item,"Pumice") + CINT(what.amount));
		else
			SetObjProperty(item, "Pumice",CINT(what.amount));
		endif 
	0x0F8A:
		if (GetObjProperty(item, "PigIron"))
			SetObjProperty(item,"PigIron",GetObjProperty(item,"PigIron") + CINT(what.amount));
		else
			SetObjProperty(item, "PigIron",CINT(what.amount));
		endif 
	0x0F89:
		if (GetObjProperty(item, "Obsidian"))
			SetObjProperty(item,"Obsidian",GetObjProperty(item,"Obsidian") + CINT(what.amount));
		else
			SetObjProperty(item, "Obsidian",CINT(what.amount));
		endif 
	0x0F87:
		if (GetObjProperty(item, "EyeOfNewt"))
			SetObjProperty(item,"EyeOfNewt",GetObjProperty(item,"EyeOfNewt") + CINT(what.amount));
		else
			SetObjProperty(item, "EyeOfNewt",CINT(what.amount));
		endif 
	0x0F83:
		if (GetObjProperty(item, "ExecutionersCap"))
			SetObjProperty(item,"ExecutionersCap",GetObjProperty(item,"ExecutionersCap") + CINT(what.amount));
		else
			SetObjProperty(item, "ExecutionersCap",CINT(what.amount));
		endif 
	0x0F82:
		if (GetObjProperty(item, "DragonsBlood"))
			SetObjProperty(item,"DragonsBlood",GetObjProperty(item,"DragonsBlood") + CINT(what.amount));
		else
			SetObjProperty(item, "DragonsBlood",CINT(what.amount));
		endif 
	0x0F81:
		if (GetObjProperty(item, "FertileDirt"))
			SetObjProperty(item,"FertileDirt",GetObjProperty(item,"FertileDirt") + CINT(what.amount));
		else
			SetObjProperty(item, "FertileDirt",CINT(what.amount));
		endif 
	0x0F80:
		if (GetObjProperty(item, "DaemonBone"))
			SetObjProperty(item,"DaemonBone",GetObjProperty(item,"DaemonBone") + CINT(what.amount));
		else
			SetObjProperty(item, "DaemonBone",CINT(what.amount));
		endif 
	0x0F7F:
		if (GetObjProperty(item, "Brimstone"))
			SetObjProperty(item,"Brimstone",GetObjProperty(item,"Brimstone") + CINT(what.amount));
		else
			SetObjProperty(item, "Brimstone",CINT(what.amount));
		endif 
	0x0F7E:
		if (GetObjProperty(item, "Bone"))
			SetObjProperty(item,"Bone",GetObjProperty(item,"Bone") + CINT(what.amount));
		else
			SetObjProperty(item, "Bone",CINT(what.amount));
		endif 
	0x0F7D:
		if (GetObjProperty(item, "VialOfBlood"))
			SetObjProperty(item,"VialOfBlood",GetObjProperty(item,"VialOfBlood") + CINT(what.amount));
		else
			SetObjProperty(item, "VialOfBlood",CINT(what.amount));
		endif 
	0x0F7C:
		if (GetObjProperty(item, "Bloodspawn"))
			SetObjProperty(item,"Bloodspawn",GetObjProperty(item,"Bloodspawn") + CINT(what.amount));
		else
			SetObjProperty(item, "Bloodspawn",CINT(what.amount));
		endif 
	0x0F79:
		if (GetObjProperty(item, "Blackmoor"))
			SetObjProperty(item,"Blackmoor",GetObjProperty(item,"Blackmoor") +CINT(what.amount));
		else
			SetObjProperty(item, "Blackmoor",CINT(what.amount));
		endif 
	0x0F78:
		if (GetObjProperty(item, "Batwing"))
			SetObjProperty(item,"Batwing",GetObjProperty(item,"Batwing") + CINT(what.amount));
		else
			SetObjProperty(item, "Batwing",CINT(what.amount));
		endif 
	0x0F7B:
		if (GetObjProperty(item, "BloodMoss"))
			SetObjProperty(item,"BloodMoss",GetObjProperty(item,"BloodMoss") + CINT(what.amount));
		else
			SetObjProperty(item, "BloodMoss",CINT(what.amount));
		endif
	0x0F7A:
		if (GetObjProperty(item, "BlackPearl"))
			SetObjProperty(item,"BlackPearl",GetObjProperty(item,"BlackPearl") + CINT(what.amount));
		else
			SetObjProperty(item, "BlackPearl",CINT(what.amount));
		endif
	0x0F8D:
		if (GetObjProperty(item, "SpiderSilk"))
			SetObjProperty(item,"SpiderSilk",GetObjProperty(item,"SpiderSilk") + CINT(what.amount));
		else
			SetObjProperty(item, "SpiderSilk",CINT(what.amount));
		endif
	0x0F8C:
		if (GetObjProperty(item, "SulphurousAsh"))
			SetObjProperty(item,"SulphurousAsh",GetObjProperty(item,"SulphurousAsh") + CINT(what.amount));
		else
			SetObjProperty(item, "SulphurousAsh",CINT(what.amount));
		endif
	0x0F88:
		if (GetObjProperty(item, "Nightshade"))
			SetObjProperty(item,"Nightshade",GetObjProperty(item,"Nightshade") + CINT(what.amount));
		else
			SetObjProperty(item, "Nightshade",CINT(what.amount));
		endif
	0x0F84:
		if (GetObjProperty(item, "Garlic"))
			SetObjProperty(item,"Garlic",GetObjProperty(item,"Garlic") + CINT(what.amount));
		else
			SetObjProperty(item, "Garlic",CINT(what.amount));
		endif
	0x0f86:
		if (GetObjProperty(item, "MandrakeRoot"))
			SetObjProperty(item,"MandrakeRoot",GetObjProperty(item,"MandrakeRoot") + CINT(what.amount));
		else
			SetObjProperty(item, "MandrakeRoot",CINT(what.amount));
		endif
	0x0f85:
		if (GetObjProperty(item, "Ginsengs"))
			SetObjProperty(item,"Ginsengs",GetObjProperty(item,"Ginsengs") + CINT(what.amount));
		else
			SetObjProperty(item, "Ginsengs",CINT(what.amount));
		endif
	0x0F0F:
		if (GetObjProperty(item, "Starsapphire"))
			SetObjProperty(item,"Starsapphire",GetObjProperty(item,"Starsapphire") + CINT(what.amount));
		else
			SetObjProperty(item, "Starsapphire",CINT(what.amount));
		endif
	0x0F10:
		if (GetObjProperty(item, "Emerald"))
			SetObjProperty(item,"Emerald",GetObjProperty(item,"Emerald") + CINT(what.amount));
		else
			SetObjProperty(item, "Emerald",CINT(what.amount));
		endif
	0x0F11:
		if (GetObjProperty(item, "Sapphire"))
			SetObjProperty(item,"Sapphire",GetObjProperty(item,"Sapphire") + CINT(what.amount));
		else
			SetObjProperty(item, "Sapphire",CINT(what.amount));
		endif
	0x0F13:
		if (GetObjProperty(item, "Ruby"))
			SetObjProperty(item,"Ruby",GetObjProperty(item,"Ruby") + CINT(what.amount));
		else
			SetObjProperty(item, "Ruby",CINT(what.amount));
		endif
	0x0F15:
		if (GetObjProperty(item, "Citrine"))
			SetObjProperty(item,"Citrine",GetObjProperty(item,"Citrine") + CINT(what.amount));
		else
			SetObjProperty(item, "Citrine",CINT(what.amount));
		endif
	0x0F16:
		if (GetObjProperty(item, "Amethyst"))
			SetObjProperty(item,"Amethyst",GetObjProperty(item,"Amethyst") + CINT(what.amount));
		else
			SetObjProperty(item, "Amethyst",CINT(what.amount));
		endif
	0x0F18:
		if (GetObjProperty(item, "Tourmaline"))
			SetObjProperty(item,"Tourmaline",GetObjProperty(item,"Tourmaline") + CINT(what.amount));
		else
			SetObjProperty(item, "Tourmaline",CINT(what.amount));
		endif
	0x0F25:
		if (GetObjProperty(item, "Amber"))
			SetObjProperty(item,"Amber",GetObjProperty(item,"Amber") + CINT(what.amount));
		else
			SetObjProperty(item, "Amber",CINT(what.amount));
		endif
	0x0F30:
		if (GetObjProperty(item, "Diamond"))
			SetObjProperty(item,"Diamond",GetObjProperty(item,"Diamond") + CINT(what.amount));
		else
			SetObjProperty(item, "Diamond",CINT(what.amount));
		endif

	0x6011:
		if (GetObjProperty(item, "IronIngot"))
			SetObjProperty(item,"IronIngot",GetObjProperty(item,"IronIngot") + CINT(what.amount));
		else
			SetObjProperty(item, "IronIngot",CINT(what.amount));
		endif 
	0x6012:
		if (GetObjProperty(item, "SilverIngot"))
			SetObjProperty(item,"SilverIngot",GetObjProperty(item,"SilverIngot") + CINT(what.amount));
		else
			SetObjProperty(item, "SilverIngot",CINT(what.amount));
		endif 
	0x6013:
		if (GetObjProperty(item, "BloodIngot"))
			SetObjProperty(item,"BloodIngot",GetObjProperty(item,"BloodIngot") + CINT(what.amount));
		else
			SetObjProperty(item, "BloodIngot",CINT(what.amount));
		endif 
	0x6014:
		if (GetObjProperty(item, "DestructionIngot"))
			SetObjProperty(item,"DestructionIngot",GetObjProperty(item,"DestructionIngot") + CINT(what.amount));
		else
			SetObjProperty(item, "DestructionIngot",CINT(what.amount));
		endif 
	0x6015:
		if (GetObjProperty(item, "OnyxIngot"))
			SetObjProperty(item,"OnyxIngot",GetObjProperty(item,"OnyxIngot") + CINT(what.amount));
		else
			SetObjProperty(item, "OnyxIngot",CINT(what.amount));
		endif 
	0x6016:
		if (GetObjProperty(item, "MalachiteIngot"))
			SetObjProperty(item,"MalachiteIngot",GetObjProperty(item,"MalachiteIngot") + CINT(what.amount));
		else
			SetObjProperty(item, "MalachiteIngot",CINT(what.amount));
		endif 
	0x6017:
		if (GetObjProperty(item, "LavaRockIngot"))
			SetObjProperty(item,"LavaRockIngot",GetObjProperty(item,"LavaRockIngot") + CINT(what.amount));
		else
			SetObjProperty(item, "LavaRockIngot",CINT(what.amount));
		endif 
	0x6018:
		if (GetObjProperty(item, "DripstoneIngot"))
			SetObjProperty(item,"DripstoneIngot",GetObjProperty(item,"DripstoneIngot") + CINT(what.amount));
		else
			SetObjProperty(item, "DripstoneIngot",CINT(what.amount));
		endif 
	0xc510:
		if (GetObjProperty(item, "CrystalIngot"))
			SetObjProperty(item,"CrystalIngot",GetObjProperty(item,"CrystalIngot") + CINT(what.amount));
		else
			SetObjProperty(item, "CrystalIngot",CINT(what.amount));
		endif 
	0xc511:
		if (GetObjProperty(item, "GoddessIngot"))
			SetObjProperty(item,"GoddessIngot",GetObjProperty(item,"GoddessIngot") + CINT(what.amount));
		else
			SetObjProperty(item, "GoddessIngot",CINT(what.amount));
		endif 
	0xc512:
		if (GetObjProperty(item, "DoomIngot"))
			SetObjProperty(item,"DoomIngot",GetObjProperty(item,"DoomIngot") + CINT(what.amount));
		else
			SetObjProperty(item, "DoomIngot",CINT(what.amount));
		endif
	0xc513:
		if (GetObjProperty(item, "PlatinumIngot"))
			SetObjProperty(item,"PlatinumIngot",GetObjProperty(item,"PlatinumIngot") + CINT(what.amount));
		else
			SetObjProperty(item, "PlatinumIngot",CINT(what.amount));
		endif 
	0xc514:
		if (GetObjProperty(item, "NewZuluIngot"))
			SetObjProperty(item,"NewZuluIngot",GetObjProperty(item,"NewZuluIngot") + CINT(what.amount));
		else
			SetObjProperty(item, "NewZuluIngot",CINT(what.amount));
		endif 
	0xc515:
		if (GetObjProperty(item, "EboonIngot"))
			SetObjProperty(item,"EboonIngot",GetObjProperty(item,"EboonIngot") + CINT(what.amount));
		else
			SetObjProperty(item, "EboonIngot",CINT(what.amount));
		endif 
	0xc516:
		if (GetObjProperty(item, "DarkSableIngot"))
			SetObjProperty(item,"DarkSableIngot",GetObjProperty(item,"DarkSableIngot") + CINT(what.amount));
		else
			SetObjProperty(item, "DarkSableIngot",CINT(what.amount));
		endif 
	0xc517:
		if (GetObjProperty(item, "RadiantNimbusIngot"))
			SetObjProperty(item,"RadiantNimbusIngot",GetObjProperty(item,"RadiantNimbusIngot") + CINT(what.amount));
		else
			SetObjProperty(item, "RadiantNimbusIngot",CINT(what.amount));
		endif 
	
	
	0x1765:
		if (GetObjProperty(item, "cloth"))
			SetObjProperty(item,"cloth",GetObjProperty(item,"cloth") + CINT(what.amount));
		else
			SetObjProperty(item, "cloth",CINT(what.amount));
		endif 
	0xee20:
		if (GetObjProperty(item, "glass"))
			SetObjProperty(item,"glass",GetObjProperty(item,"glass") + CINT(what.amount));
		else
			SetObjProperty(item, "glass",CINT(what.amount));
		endif 
	0xee19:
		if (GetObjProperty(item, "clay"))
			SetObjProperty(item,"clay",GetObjProperty(item,"clay") + CINT(what.amount));
		else
			SetObjProperty(item, "clay",CINT(what.amount));
		endif 
	0x1be9:
		if (GetObjProperty(item, "goldingot"))
			SetObjProperty(item,"goldingot",GetObjProperty(item,"goldingot") + CINT(what.amount));
		else
			SetObjProperty(item, "goldingot",CINT(what.amount));
		endif 
	0x1078:
		if (GetObjProperty(item, "hides"))
			SetObjProperty(item,"hides",GetObjProperty(item,"hides") + CINT(what.amount));
		else
			SetObjProperty(item, "hides",CINT(what.amount));
		endif 
	0x7020:
		if (GetObjProperty(item, "lizardhide"))
			SetObjProperty(item,"lizardhide",GetObjProperty(item,"lizardhide") + CINT(what.amount));
		else
			SetObjProperty(item, "lizardhide",CINT(what.amount));
		endif 
	0x7021:
		if (GetObjProperty(item, "orchide"))
			SetObjProperty(item,"orchide",GetObjProperty(item,"orchide") + CINT(what.amount));
		else
			SetObjProperty(item, "orchide",CINT(what.amount));
		endif 
	0x7022:
		if (GetObjProperty(item, "trollhide"))
			SetObjProperty(item,"trollhide",GetObjProperty(item,"trollhide") + CINT(what.amount));
		else
			SetObjProperty(item, "trollhide",CINT(what.amount));
		endif 
	0x702d:
		if (GetObjProperty(item, "terathanhide"))
			SetObjProperty(item,"terathanhide",GetObjProperty(item,"terathanhide") + CINT(what.amount));
		else
			SetObjProperty(item, "terathanhide",CINT(what.amount));
		endif 
	0x7023:
		if (GetObjProperty(item, "bearhide"))
			SetObjProperty(item,"bearhide",GetObjProperty(item,"bearhide") + CINT(what.amount));
		else
			SetObjProperty(item, "bearhide",CINT(what.amount));
		endif 
	0x7025:
		if (GetObjProperty(item, "icehide"))
			SetObjProperty(item,"icehide",GetObjProperty(item,"icehide") + CINT(what.amount));
		else
			SetObjProperty(item, "icehide",CINT(what.amount));
		endif 
	0x7026:
		if (GetObjProperty(item, "lichehide"))
			SetObjProperty(item,"lichehide",GetObjProperty(item,"lichehide") + CINT(what.amount));
		else
			SetObjProperty(item, "lichehide",CINT(what.amount));
		endif 
	0x7028:
		if (GetObjProperty(item, "daemonhide"))
			SetObjProperty(item,"daemonhide",GetObjProperty(item,"daemonhide") + CINT(what.amount));
		else
			SetObjProperty(item, "daemonhide",CINT(what.amount));
		endif 
	0x702a:
		if (GetObjProperty(item, "balronhide"))
			SetObjProperty(item,"balronhide",GetObjProperty(item,"balronhide") + CINT(what.amount));
		else
			SetObjProperty(item, "balronhide",CINT(what.amount));
		endif 
	0x7024:
		if (GetObjProperty(item, "rathide"))
			SetObjProperty(item,"rathide",GetObjProperty(item,"rathide") + CINT(what.amount));
		else
			SetObjProperty(item, "rathide",CINT(what.amount));
		endif 
	0x7027:
		if (GetObjProperty(item, "dragonhide"))
			SetObjProperty(item,"dragonhide",GetObjProperty(item,"dragonhide") + CINT(what.amount));
		else
			SetObjProperty(item, "dragonhide",CINT(what.amount));
		endif 
	0x702f:
		if (GetObjProperty(item, "wyrmhide"))
			SetObjProperty(item,"wyrmhide",GetObjProperty(item,"wyrmhide") + CINT(what.amount));
		else
			SetObjProperty(item, "wyrmhide",CINT(what.amount));
		endif 
	0x7029:
		if (GetObjProperty(item, "greatwyrmhide"))
			SetObjProperty(item,"greatwyrmhide",GetObjProperty(item,"greatwyrmhide") + CINT(what.amount));
		else
			SetObjProperty(item, "greatwyrmhide",CINT(what.amount));
		endif 
	0x702b:
		if (GetObjProperty(item, "celestialhide"))
			SetObjProperty(item,"celestialhide",GetObjProperty(item,"celestialhide") + CINT(what.amount));
		else
			SetObjProperty(item, "celestialhide",CINT(what.amount));
		endif 
	0x702c:
		if (GetObjProperty(item, "Goldendragonhide"))
			SetObjProperty(item,"Goldendragonhide",GetObjProperty(item,"Goldendragonhide") + CINT(what.amount));
		else
			SetObjProperty(item, "Goldendragonhide",CINT(what.amount));
		endif 
	0x1BDD:
		if (GetObjProperty(item, "logs"))
			SetObjProperty(item,"logs",GetObjProperty(item,"logs") + CINT(what.amount));
		else
			SetObjProperty(item, "logs",CINT(what.amount));
		endif 
	0x7300:
		if (GetObjProperty(item, "silverleaflog"))
			SetObjProperty(item,"silverleaflog",GetObjProperty(item,"silverleaflog") + CINT(what.amount));
		else
			SetObjProperty(item, "silverleaflog",CINT(what.amount));
		endif 
	0x7301:
		if (GetObjProperty(item, "emeraldlog"))
			SetObjProperty(item,"emeraldlog",GetObjProperty(item,"emeraldlog") + CINT(what.amount));
		else
			SetObjProperty(item, "emeraldlog",CINT(what.amount));
		endif 
	0x7302:
		if (GetObjProperty(item, "swamplog"))
			SetObjProperty(item,"swamplog",GetObjProperty(item,"swamplog") + CINT(what.amount));
		else
			SetObjProperty(item, "swamplog",CINT(what.amount));
		endif
	0x7303:
		if (GetObjProperty(item, "oaklog"))
			SetObjProperty(item,"oaklog",GetObjProperty(item,"oaklog") + CINT(what.amount));
		else
			SetObjProperty(item, "oaklog",CINT(what.amount));
		endif 
	0x7304:
		if (GetObjProperty(item, "stardustlog"))
			SetObjProperty(item,"stardustlog",GetObjProperty(item,"stardustlog") + CINT(what.amount));
		else
			SetObjProperty(item, "stardustlog",CINT(what.amount));
		endif 
	0x7305:
		if (GetObjProperty(item, "jadelog"))
			SetObjProperty(item,"jadelog",GetObjProperty(item,"jadelog") + CINT(what.amount));
		else
			SetObjProperty(item, "jadelog",CINT(what.amount));
		endif 
	0x7306:
		if (GetObjProperty(item, "darkwoodlog"))
			SetObjProperty(item,"darkwoodlog",GetObjProperty(item,"darkwoodlog") + CINT(what.amount));
		else
			SetObjProperty(item, "darkwoodlog",CINT(what.amount));
		endif 
	0x7307:
		if (GetObjProperty(item, "goldenreflectionlog"))
			SetObjProperty(item,"goldenreflectionlog",GetObjProperty(item,"goldenreflectionlog") + CINT(what.amount));
		else
			SetObjProperty(item, "goldenreflectionlog",CINT(what.amount));
		endif 
	0x7308:
		if (GetObjProperty(item, "doomlog"))
			SetObjProperty(item,"doomlog",GetObjProperty(item,"doomlog") + CINT(what.amount));
		else
			SetObjProperty(item, "doomlog",CINT(what.amount));
		endif 
	0x7309:
		if (GetObjProperty(item, "bloodhorselog"))
			SetObjProperty(item,"bloodhorselog",GetObjProperty(item,"bloodhorselog") + CINT(what.amount));
		else
			SetObjProperty(item, "bloodhorselog",CINT(what.amount));
		endif 
	0x730a:
		if (GetObjProperty(item, "yewlog"))
			SetObjProperty(item,"yewlog",GetObjProperty(item,"yewlog") + CINT(what.amount));
		else
			SetObjProperty(item, "yewlog",CINT(what.amount));
		endif 
	0x730b:
		if (GetObjProperty(item, "darknesslog"))
			SetObjProperty(item,"darknesslog",GetObjProperty(item,"darknesslog") + CINT(what.amount));
		else
			SetObjProperty(item, "darknesslog",CINT(what.amount));
		endif 
	0x730c:
		if (GetObjProperty(item, "elvenlog"))
			SetObjProperty(item,"elvenlog",GetObjProperty(item,"elvenlog") + CINT(what.amount));
		else
			SetObjProperty(item, "elvenlog",CINT(what.amount));
		endif 
	
	0x099B:
		if (GetObjProperty(item, "bottleofliquor"))
			SetObjProperty(item,"bottleofliquor",GetObjProperty(item,"bottleofliquor") + CINT(what.amount));
		else
			SetObjProperty(item, "bottleofliquor",CINT(what.amount));
		endif 
	0x099F:
		if (GetObjProperty(item, "bottleofale"))
			SetObjProperty(item,"bottleofale",GetObjProperty(item,"bottleofale") + CINT(what.amount));
		else
			SetObjProperty(item, "bottleofale",CINT(what.amount));
		endif 
	0x09C7:
		if (GetObjProperty(item, "bottleofwine"))
			SetObjProperty(item,"bottleofwine",GetObjProperty(item,"bottleofwine") + CINT(what.amount));
		else
			SetObjProperty(item, "bottleofwine",CINT(what.amount));
		endif 
	0x1f96:
		if (GetObjProperty(item, "pitcherofale"))
			SetObjProperty(item,"pitcherofale",GetObjProperty(item,"pitcherofale") + CINT(what.amount));
		else
			SetObjProperty(item, "pitcherofale",CINT(what.amount));
		endif 
	0x1f98:
		if (GetObjProperty(item, "pitcherofcider"))
			SetObjProperty(item,"pitcherofcider",GetObjProperty(item,"pitcherofcider") + CINT(what.amount));
		else
			SetObjProperty(item, "pitcherofcider",CINT(what.amount));
		endif 
	0x1f9a:
		if (GetObjProperty(item, "pitcherofliquor"))
			SetObjProperty(item,"pitcherofliquor",GetObjProperty(item,"pitcherofliquor") + CINT(what.amount));
		else
			SetObjProperty(item, "pitcherofliquor",CINT(what.amount));
		endif 
	0x1f9c:
		if (GetObjProperty(item, "pitcherofwine"))
			SetObjProperty(item,"pitcherofwine",GetObjProperty(item,"pitcherofwine") + CINT(what.amount));
		else
			SetObjProperty(item, "pitcherofwine",CINT(what.amount));
		endif 
	0x1f9e:
		if (GetObjProperty(item, "pitcherofwater"))
			SetObjProperty(item,"pitcherofwater",GetObjProperty(item,"pitcherofwater") + CINT(what.amount));
		else
			SetObjProperty(item, "pitcherofwater",CINT(what.amount));
		endif 
	0x09ad:
		if (GetObjProperty(item, "pitcherofmilk"))
			SetObjProperty(item,"pitcherofmilk",GetObjProperty(item,"pitcherofmilk") + CINT(what.amount));
		else
			SetObjProperty(item, "pitcherofmilk",CINT(what.amount));
		endif 
	0x1F85:
		if (GetObjProperty(item, "glassofliquor"))
			SetObjProperty(item,"glassofliquor",GetObjProperty(item,"glassofliquor") + CINT(what.amount));
		else
			SetObjProperty(item, "glassofliquor",CINT(what.amount));
		endif 
	0x09EE:
		if (GetObjProperty(item, "mugofale"))
			SetObjProperty(item,"mugofale",GetObjProperty(item,"mugofale") + CINT(what.amount));
		else
			SetObjProperty(item, "mugofale",CINT(what.amount));
		endif 
	0x1F8D:
		if (GetObjProperty(item, "glassofwine"))
			SetObjProperty(item,"glassofwine",GetObjProperty(item,"glassofwine") + CINT(what.amount));
		else
			SetObjProperty(item, "glassofwine",CINT(what.amount));
		endif 
	0x1F7D:
		if (GetObjProperty(item, "glassofcider"))
			SetObjProperty(item,"glassofcider",GetObjProperty(item,"glassofcider") + CINT(what.amount));
		else
			SetObjProperty(item, "glassofcider",CINT(what.amount));
		endif 
	0x1F89:
		if (GetObjProperty(item, "glassofmilk"))
			SetObjProperty(item,"glassofmilk",GetObjProperty(item,"glassofmilk") + CINT(what.amount));
		else
			SetObjProperty(item, "glassofmilk",CINT(what.amount));
		endif 
	0x1F91:
		if (GetObjProperty(item, "glassofwater"))
			SetObjProperty(item,"glassofwater",GetObjProperty(item,"glassofwater") + CINT(what.amount));
		else
			SetObjProperty(item, "glassofwater",CINT(what.amount));
		endif 
	0x1045:
		if (GetObjProperty(item, "flour"))
			SetObjProperty(item,"flour",GetObjProperty(item,"flour") + CINT(what.amount));
		else
			SetObjProperty(item, "flour",CINT(what.amount));
		endif 
	0x0c6d:
		if (GetObjProperty(item, "onion"))
			SetObjProperty(item,"onion",GetObjProperty(item,"onion") + CINT(what.amount));
		else
			SetObjProperty(item, "onion",CINT(what.amount));
		endif	
	0x09f1:
		if (GetObjProperty(item, "rawrib"))
			SetObjProperty(item,"rawrib",GetObjProperty(item,"rawrib") + CINT(what.amount));
		else
			SetObjProperty(item, "rawrib",CINT(what.amount));
		endif 
	0x097a:
		if (GetObjProperty(item, "rawfishsteak"))
			SetObjProperty(item,"rawfishsteak",GetObjProperty(item,"rawfishsteak") + CINT(what.amount));
		else
			SetObjProperty(item, "rawfishsteak",CINT(what.amount));
		endif 
	0x09b9:
		if (GetObjProperty(item, "rawbird"))
			SetObjProperty(item,"rawbird",GetObjProperty(item,"rawbird") + CINT(what.amount));
		else
			SetObjProperty(item, "rawbird",CINT(what.amount));
		endif 
	0x09c9:
		if (GetObjProperty(item, "rawham"))
			SetObjProperty(item,"rawham",GetObjProperty(item,"rawham") + CINT(what.amount));
		else
			SetObjProperty(item, "rawham",CINT(what.amount));
		endif 
	0x0976:
		if (GetObjProperty(item, "slabofbacon"))
			SetObjProperty(item,"slabofbacon",GetObjProperty(item,"slabofbacon") + CINT(what.amount));
		else
			SetObjProperty(item, "slabofbacon",CINT(what.amount));
		endif 
	0x1e8a:
		if (GetObjProperty(item, "lard"))
			SetObjProperty(item,"lard",GetObjProperty(item,"lard") + CINT(what.amount));
		else
			SetObjProperty(item, "lard",CINT(what.amount));
		endif 
	0x1607:
		if (GetObjProperty(item, "rawchickenleg"))
			SetObjProperty(item,"rawchickenleg",GetObjProperty(item,"rawchickenleg") + CINT(what.amount));
		else
			SetObjProperty(item, "rawchickenleg",CINT(what.amount));
		endif 
	0x1609:
		if (GetObjProperty(item, "rawlegoflamb"))
			SetObjProperty(item,"rawlegoflamb",GetObjProperty(item,"rawlegoflamb") + CINT(what.amount));
		else
			SetObjProperty(item, "rawlegoflamb",CINT(what.amount));
		endif 
	0x09ec:
		if (GetObjProperty(item, "honey"))
			SetObjProperty(item,"honey",GetObjProperty(item,"honey") + CINT(what.amount));
		else
			SetObjProperty(item, "honey",CINT(what.amount));
		endif 
	0x1726:
		if (GetObjProperty(item, "coconut"))
			SetObjProperty(item,"coconut",GetObjProperty(item,"coconut") + CINT(what.amount));
		else
			SetObjProperty(item, "coconut",CINT(what.amount));
		endif 
	0xc803:
		if (GetObjProperty(item, "pizzacrust"))
			SetObjProperty(item,"pizzacrust",GetObjProperty(item,"pizzacrust") + CINT(what.amount));
		else
			SetObjProperty(item, "pizzacrust",CINT(what.amount));
		endif 
	0xc804:
		if (GetObjProperty(item, "piecrust"))
			SetObjProperty(item,"piecrust",GetObjProperty(item,"piecrust") + CINT(what.amount));
		else
			SetObjProperty(item, "piecrust",CINT(what.amount));
		endif 
	0x09cd:
		if (GetObjProperty(item, "fish2"))
			SetObjProperty(item,"fish2",GetObjProperty(item,"fish2") + CINT(what.amount));
		else
			SetObjProperty(item, "fish2",CINT(what.amount));
		endif 
	0x09ce:
		if (GetObjProperty(item, "fish3"))
			SetObjProperty(item,"fish3",GetObjProperty(item,"fish3") + CINT(what.amount));
		else
			SetObjProperty(item, "fish3",CINT(what.amount));
		endif 
	0x09cf:
		if (GetObjProperty(item, "fish4"))
			SetObjProperty(item,"fish4",GetObjProperty(item,"fish4") + CINT(what.amount));
		else
			SetObjProperty(item, "fish4",CINT(what.amount));
		endif 
	0x097E:
		if (GetObjProperty(item, "wheelofcheese"))
			SetObjProperty(item,"wheelofcheese",GetObjProperty(item,"wheelofcheese") + CINT(what.amount));
		else
			SetObjProperty(item, "wheelofcheese",CINT(what.amount));
		endif 
	0x1608:
		if (GetObjProperty(item, "friedchickenleg"))
			SetObjProperty(item,"friedchickenleg",GetObjProperty(item,"friedchickenleg") + CINT(what.amount));
		else
			SetObjProperty(item, "friedchickenleg",CINT(what.amount));
		endif 
	0x160a:
		if (GetObjProperty(item, "cookedlegoflamb"))
			SetObjProperty(item,"cookedlegoflamb",GetObjProperty(item,"cookedlegoflamb") + CINT(what.amount));
		else
			SetObjProperty(item, "cookedlegoflamb",CINT(what.amount));
		endif 
	0xc923:
		if (GetObjProperty(item, "sushi"))
			SetObjProperty(item,"sushi",GetObjProperty(item,"sushi") + CINT(what.amount));
		else
			SetObjProperty(item, "sushi",CINT(what.amount));
		endif 
	0x097b:
		if (GetObjProperty(item, "CookedFishSteak"))
			SetObjProperty(item,"CookedFishSteak",GetObjProperty(item,"CookedFishSteak") + CINT(what.amount));
		else
			SetObjProperty(item, "CookedFishSteak",CINT(what.amount));
		endif 
	0x1e1e:
		if (GetObjProperty(item, "smokedsalmon"))
			SetObjProperty(item,"smokedsalmon",GetObjProperty(item,"smokedsalmon") + CINT(what.amount));
		else
			SetObjProperty(item, "smokedsalmon",CINT(what.amount));
		endif 
	0x09b7:
		if (GetObjProperty(item, "cookedbird"))
			SetObjProperty(item,"cookedbird",GetObjProperty(item,"cookedbird") + CINT(what.amount));
		else
			SetObjProperty(item, "cookedbird",CINT(what.amount));
		endif 
	0x09f2:
		if (GetObjProperty(item, "CookedRib"))
			SetObjProperty(item,"CookedRib",GetObjProperty(item,"CookedRib") + CINT(what.amount));
		else
			SetObjProperty(item, "CookedRib",CINT(what.amount));
		endif 
	0xA368:
		if (GetObjProperty(item, "magicfish1"))
			SetObjProperty(item,"magicfish1",GetObjProperty(item,"magicfish1") + CINT(what.amount));
		else
			SetObjProperty(item, "magicfish1",CINT(what.amount));
		endif 
	0xA369:
		if (GetObjProperty(item, "magicfish2"))
			SetObjProperty(item,"magicfish2",GetObjProperty(item,"magicfish2") + CINT(what.amount));
		else
			SetObjProperty(item, "magicfish2",CINT(what.amount));
		endif 
	0xA36A:
		if (GetObjProperty(item, "magicfish3"))
			SetObjProperty(item,"magicfish3",GetObjProperty(item,"magicfish3") + CINT(what.amount));
		else
			SetObjProperty(item, "magicfish3",CINT(what.amount));
		endif 
	0xA36B:
		if (GetObjProperty(item, "magicfish4"))
			SetObjProperty(item,"magicfish4",GetObjProperty(item,"magicfish4") + CINT(what.amount));
		else
			SetObjProperty(item, "magicfish4",CINT(what.amount));
		endif 
	0xA36C:
		if (GetObjProperty(item, "magicfish5"))
			SetObjProperty(item,"magicfish5",GetObjProperty(item,"magicfish5") + CINT(what.amount));
		else
			SetObjProperty(item, "magicfish5",CINT(what.amount));
		endif 
	0xA36D:
		if (GetObjProperty(item, "magicfish6"))
			SetObjProperty(item,"magicfish6",GetObjProperty(item,"magicfish6") + CINT(what.amount));
		else
			SetObjProperty(item, "magicfish6",CINT(what.amount));
		endif 
	0xA36E:
		if (GetObjProperty(item, "magicfish7"))
			SetObjProperty(item,"magicfish7",GetObjProperty(item,"magicfish7") + CINT(what.amount));
		else
			SetObjProperty(item, "magicfish7",CINT(what.amount));
		endif 
	0xA36F:
		if (GetObjProperty(item, "magicfish8"))
			SetObjProperty(item,"magicfish8",GetObjProperty(item,"magicfish8") + CINT(what.amount));
		else
			SetObjProperty(item, "magicfish8",CINT(what.amount));
		endif 
	0xc912:
		if (GetObjProperty(item, "pancakes"))
			SetObjProperty(item,"pancakes",GetObjProperty(item,"pancakes") + CINT(what.amount));
		else
			SetObjProperty(item, "pancakes",CINT(what.amount));
		endif 
	0xc942:
		if (GetObjProperty(item, "mincemeatpie"))
			SetObjProperty(item,"mincemeatpie",GetObjProperty(item,"mincemeatpie") + CINT(what.amount));
		else
			SetObjProperty(item, "mincemeatpie",CINT(what.amount));
		endif 
	0xc943:
		if (GetObjProperty(item, "chickenpotpie"))
			SetObjProperty(item,"chickenpotpie",GetObjProperty(item,"chickenpotpie") + CINT(what.amount));
		else
			SetObjProperty(item, "chickenpotpie",CINT(what.amount));
		endif 
	0x27bc:
		if (GetObjProperty(item, "lemonherbfish"))
			SetObjProperty(item,"lemonherbfish",GetObjProperty(item,"lemonherbfish") + CINT(what.amount));
		else
			SetObjProperty(item, "lemonherbfish",CINT(what.amount));
		endif
	0x0eed:
		if (GetObjProperty(item, "Goldcoin"))
			SetObjProperty(item,"Goldcoin",GetObjProperty(item,"Goldcoin") + CINT(what.amount));
		else
			SetObjProperty(item, "Goldcoin",CINT(what.amount));
		endif 
	0x3b9a:
		if (GetObjProperty(item, "zulucoin"))
			SetObjProperty(item,"zulucoin",GetObjProperty(item,"zulucoin") + CINT(what.amount));
		else
			SetObjProperty(item, "zulucoin",CINT(what.amount));
		endif
	0xdf0c:
		if (GetObjProperty(item, "Goldcoin"))
			SetObjProperty(item,"Goldcoin",GetObjProperty(item,"Goldcoin") + CINT(GetObjProperty(what,"gold_amount")));
		else
			SetObjProperty(item, "Goldcoin",CINT(GetObjProperty(what,"gold_amount")));
		endif
	0xdc01:
		if (GetObjProperty(item,"LHEALPOTION"))
			if (GetObjProperty(item, "ByTrueMageLHeal") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
				return;
			endif
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageLHeal", GetObjProperty(what,"ByTrueMage"));
			endif
			SetObjProperty(item,"LHEALPOTION",GetObjProperty(item,"LHEALPOTION") + CINT(what.amount));
		else
			SetObjProperty(item, "LHEALPOTION",CINT(what.amount));
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageLHeal", GetObjProperty(what,"ByTrueMage"));
			endif
		endif
	0xdc02:
		 if (GetObjProperty(item,"HEALPOTION"))
			if (GetObjProperty(item, "ByTrueMageLHeal") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
				return;
			endif
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageLHeal", GetObjProperty(what,"ByTrueMage")); 
			endif
			SetObjProperty(item,"HEALPOTION",GetObjProperty(item,"HEALPOTION") + CINT(what.amount));
			else
				SetObjProperty(item, "HEALPOTION",CINT(what.amount));
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageHeal", GetObjProperty(what,"ByTrueMage"));
			endif
		endif
			
			
	0xdc03:
		if (GetObjProperty(item,"GHEALPOTION"))
				if (GetObjProperty(item, "ByTrueMageGHeal") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
					return;
				endif
				if (GetObjProperty(what,"ByTrueMage"))
					SetObjProperty(item,"ByTrueMageGHeal", GetObjProperty(what,"ByTrueMage")); 
				endif
				SetObjProperty(item,"GHEALPOTION",GetObjProperty(item,"GHEALPOTION") + CINT(what.amount));
			else
				SetObjProperty(item, "GHEALPOTION",CINT(what.amount));
				if (GetObjProperty(what,"ByTrueMage"))
					SetObjProperty(item,"ByTrueMageGHeal", GetObjProperty(what,"ByTrueMage"));
				endif
			endif
	0xdc04:
		if (GetObjProperty(item,"LPOISONPOTION"))
				if (GetObjProperty(item, "ByTrueMageLPoison") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
					return;
				endif
				if (GetObjProperty(what,"ByTrueMage"))
					SetObjProperty(item,"ByTrueMageLPoison", GetObjProperty(what,"ByTrueMage")); 
				endif
				SetObjProperty(item,"LPOISONPOTION",GetObjProperty(item,"LPOISONPOTION") + CINT(what.amount));
			else
				SetObjProperty(item, "LPOISONPOTION",CINT(what.amount));
				if (GetObjProperty(what,"ByTrueMage"))
					SetObjProperty(item,"ByTrueMageGHeal", GetObjProperty(what,"ByTrueMage"));
				endif
			endif
	0xdc05:
		if (GetObjProperty(item,"POISONPOTION"))
			if (GetObjProperty(item, "ByTrueMagePoison") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
					return;
				endif
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMagePoison", GetObjProperty(what,"ByTrueMage")); 
				endif
				SetObjProperty(item,"POISONPOTION",GetObjProperty(item,"POISONPOTION") + CINT(what.amount));
			else
				SetObjProperty(item, "POISONPOTION",CINT(what.amount));
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMagePoison", GetObjProperty(what,"ByTrueMage"));
				endif
			endif
	0xdc06:
		if (GetObjProperty(item,"GRPOISONPOTION"))
			if (GetObjProperty(item, "ByTrueMageGPoison") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
					return;
				endif
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageGPoison", GetObjProperty(what,"ByTrueMage")); 
					endif
				SetObjProperty(item,"GRPOISONPOTION",GetObjProperty(item,"GRPOISONPOTION") + CINT(what.amount));
			else
				SetObjProperty(item, "GRPOISONPOTION",CINT(what.amount));
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageGPoison", GetObjProperty(what,"ByTrueMage")); 
				endif
			endif
	0xdc07:
		if (GetObjProperty(item,"GREXPLOSIONPOTION"))
			if (GetObjProperty(item, "ByTrueMageGExpl") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
				return;
			endif
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageGExpl", GetObjProperty(what,"ByTrueMage")); 
			endif
			SetObjProperty(item,"GREXPLOSIONPOTION",GetObjProperty(item,"GREXPLOSIONPOTION") + CINT(what.amount));
		else
			SetObjProperty(item, "GREXPLOSIONPOTION",CINT(what.amount));
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageGExpl", GetObjProperty(what,"ByTrueMage")); 
			endif
		endif
	0xdc08:
		if (GetObjProperty(item,"LEXPLOSIONPOTION"))
			if (GetObjProperty(item, "ByTrueMageLExpl") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
				return;
			endif
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageLExpl", GetObjProperty(what,"ByTrueMage")); 
			endif
			SetObjProperty(item,"LEXPLOSIONPOTION",GetObjProperty(item,"LEXPLOSIONPOTION") + CINT(what.amount));
		else
			SetObjProperty(item, "LEXPLOSIONPOTION",CINT(what.amount));
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageLExpl", GetObjProperty(what,"ByTrueMage")); 
			endif
		endif
	0xdc09:
		if (GetObjProperty(item,"EXPLOSIONPOTION"))
			if (GetObjProperty(item, "ByTrueMageExpl") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
				return;
			endif
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageExpl", GetObjProperty(what,"ByTrueMage")); 
			endif
			SetObjProperty(item,"EXPLOSIONPOTION",GetObjProperty(item,"EXPLOSIONPOTION") + CINT(what.amount));
		else
			SetObjProperty(item, "EXPLOSIONPOTION",CINT(what.amount));
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageExpl", GetObjProperty(what,"ByTrueMage")); 
			endif
		endif
		
	0xdc0b:
		if (GetObjProperty(item,"LAGILITYPOTION"))
			if (GetObjProperty(item, "ByTrueMageLagil") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
				return;
			endif
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageLagil", GetObjProperty(what,"ByTrueMage")); 
			endif
			SetObjProperty(item,"LAGILITYPOTION",GetObjProperty(item,"LAGILITYPOTION") + CINT(what.amount));
		else
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageLagil", GetObjProperty(what,"ByTrueMage")); 
			endif
			SetObjProperty(item, "LAGILITYPOTION",CINT(what.amount));
		endif
	0xdc0c:
		if (GetObjProperty(item,"AGILITYPOTION"))
			if (GetObjProperty(item, "ByTrueMageAgil") != (GetObjProperty(what, "ByTrueMage")))
			SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
				return;
			endif
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageAgil", GetObjProperty(what,"ByTrueMage"));
			endif 
			SetObjProperty(item,"AGILITYPOTION",GetObjProperty(item,"AGILITYPOTION") + CINT(what.amount));
		else
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageAgil", GetObjProperty(what,"ByTrueMage")); 
			endif
			SetObjProperty(item, "AGILITYPOTION",CINT(what.amount));
		endif
	0xdc0d:
		if (GetObjProperty(item,"GRAGILITYPOTION"))
			if (GetObjProperty(item, "ByTrueMageGagil") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
				return;
			endif
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageGagil", GetObjProperty(what,"ByTrueMage"));
			endif
			SetObjProperty(item,"GRAGILITYPOTION",GetObjProperty(item,"GRAGILITYPOTION") + CINT(what.amount));
		else
			SetObjProperty(item, "GRAGILITYPOTION",CINT(what.amount));
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageGagil", GetObjProperty(what,"ByTrueMage"));
			endif
		endif
	0xdc0e:
		if (GetObjProperty(item,"REFRESHPOTION"))
			if (GetObjProperty(item, "ByTrueMageRefresh") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
				return;
			endif
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageRefresh", GetObjProperty(what,"ByTrueMage"));
			endif
			SetObjProperty(item,"REFRESHPOTION",GetObjProperty(item,"REFRESHPOTION") + CINT(what.amount));
		else
			SetObjProperty(item, "REFRESHPOTION",CINT(what.amount));
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageRefresh", GetObjProperty(what,"ByTrueMage"));
			endif
		endif
	0xdc0f:
		if (GetObjProperty(item,"FULLREFRESHPOTION"))
			if (GetObjProperty(item, "ByTrueMageFRefresh") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
				return;
			endif
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageFRefresh", GetObjProperty(what,"ByTrueMage"));
			endif
			SetObjProperty(item,"FULLREFRESHPOTION",GetObjProperty(item,"FULLREFRESHPOTION") + CINT(what.amount));
		else
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageFRefresh", GetObjProperty(what,"ByTrueMage"));
			endif
			SetObjProperty(item, "FULLREFRESHPOTION",CINT(what.amount));
		endif 
	0xdc10:
		if (GetObjProperty(item,"LSTRENGTHPOTION"))
			if (GetObjProperty(item, "ByTrueMageLstrpot") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
					return;
				endif
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageLstrpot", GetObjProperty(what,"ByTrueMage"));
				endif
				SetObjProperty(item,"LSTRENGTHPOTION",GetObjProperty(item,"LSTRENGTHPOTION") + CINT(what.amount));
			else
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageLstrpot", GetObjProperty(what,"ByTrueMage"));
				endif
				SetObjProperty(item, "LSTRENGTHPOTION",CINT(what.amount));
		endif
	0xdc11:
		if (GetObjProperty(item,"STRENGTHPOTION"))
			if (GetObjProperty(item, "ByTrueMageStrpot") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
					return;
				endif
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageStrpot", GetObjProperty(what,"ByTrueMage"));
				endif
				SetObjProperty(item,"STRENGTHPOTION",GetObjProperty(item,"STRENGTHPOTION") + CINT(what.amount));
			else
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageStrpot", GetObjProperty(what,"ByTrueMage"));
				endif
				SetObjProperty(item, "STRENGTHPOTION",CINT(what.amount));
		endif
	0xdc12:
		if (GetObjProperty(item,"GRSTRENGTHPOTION"))
			if (GetObjProperty(item, "ByTrueMageGStrpot") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
				return;
			endif
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageGStrpot", GetObjProperty(what,"ByTrueMage"));
			endif
			SetObjProperty(item,"GRSTRENGTHPOTION",GetObjProperty(item,"GRSTRENGTHPOTION") + CINT(what.amount));
		else
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageGStrpot", GetObjProperty(what,"ByTrueMage"));
			endif
			SetObjProperty(item, "GRSTRENGTHPOTION",CINT(what.amount));
		endif
	0xdc14:
		if (GetObjProperty(item,"LCUREPOTION"))
			if (GetObjProperty(item, "ByTrueMageLcurepot") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
				return;
			endif
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageLcurepot", GetObjProperty(what,"ByTrueMage"));
			endif
			SetObjProperty(item,"LCUREPOTION",GetObjProperty(item,"LCUREPOTION") + CINT(what.amount));
		else
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageLcurepot", GetObjProperty(what,"ByTrueMage"));
			endif
			SetObjProperty(item, "LCUREPOTION",CINT(what.amount));
		endif
		
	0xdc15:
		if (GetObjProperty(item,"CUREPOTION"))
			if (GetObjProperty(item, "ByTrueMageCurepot") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
				return;
			endif
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageCurepot", GetObjProperty(what,"ByTrueMage"));
			endif
			SetObjProperty(item,"CUREPOTION",GetObjProperty(item,"CUREPOTION") + CINT(what.amount));
		else
			if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageCurepot", GetObjProperty(what,"ByTrueMage"));
			endif
			SetObjProperty(item, "CUREPOTION",CINT(what.amount));
		endif
	0xdc16:
		if (GetObjProperty(item,"GRCUREPOTION"))
			if (GetObjProperty(item, "ByTrueMageGCurepot") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
					return;
				endif
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageGCurepot", GetObjProperty(what,"ByTrueMage"));
				endif
				SetObjProperty(item,"GRCUREPOTION",GetObjProperty(item,"GRCUREPOTION") + CINT(what.amount));
			else
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageGCurepot", GetObjProperty(what,"ByTrueMage"));
				endif
				SetObjProperty(item, "GRCUREPOTION",CINT(what.amount));
			endif
			
	0xdc17:
		if (GetObjProperty(item,"DEDLYPOISONPOTION"))
				if (GetObjProperty(item, "ByTrueMageDpoisonpot") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
					return;
				endif
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageDpoisonpot", GetObjProperty(what,"ByTrueMage"));
				endif
				SetObjProperty(item,"DEDLYPOISONPOTION",GetObjProperty(item,"DEDLYPOISONPOTION") + CINT(what.amount));
			else
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageDpoisonpot", GetObjProperty(what,"ByTrueMage"));
				endif
				SetObjProperty(item, "DEDLYPOISONPOTION",CINT(what.amount));
			endif
	0xdce6:
		if (GetObjProperty(item,"LMINDPOTION"))
			if (GetObjProperty(item, "ByTrueMageLMindpotion") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
					return;
				endif
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageLMindpotion", GetObjProperty(what,"ByTrueMage"));
				endif
				SetObjProperty(item,"LMINDPOTION",GetObjProperty(item,"LMINDPOTION") + CINT(what.amount));
			else
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageLMindpotion", GetObjProperty(what,"ByTrueMage"));
				endif
				SetObjProperty(item, "LMINDPOTION",CINT(what.amount));
			endif
			
	0xdce7:
		if (GetObjProperty(item,"MINDPOTION"))
				if (GetObjProperty(item, "ByTrueMageMindpotion") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
					return;
				endif
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageMindpotion", GetObjProperty(what,"ByTrueMage"));
				endif
				SetObjProperty(item,"MINDPOTION",GetObjProperty(item,"MINDPOTION") + CINT(what.amount));
			else
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageMindpotion", GetObjProperty(what,"ByTrueMage"));
				endif
				SetObjProperty(item, "MINDPOTION",CINT(what.amount));
			endif
	0xdce8:
		if (GetObjProperty(item,"GMINDPOTION"))
				if (GetObjProperty(item, "ByTrueMageGMindpotion") != (GetObjProperty(what, "ByTrueMage")))
				SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
					return;
				endif
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageGMindpotion", GetObjProperty(what,"ByTrueMage"));
				endif
				SetObjProperty(item,"GMINDPOTION",GetObjProperty(item,"GMINDPOTION") + CINT(what.amount));
			else
				if (GetObjProperty(what,"ByTrueMage"))
				SetObjProperty(item,"ByTrueMageGMindpotion", GetObjProperty(what,"ByTrueMage"));
				endif
				SetObjProperty(item, "GMINDPOTION",CINT(what.amount));
			endif
	0x7059:
		case (GetObjProperty(what, "itemtype"))
			23:
				if (GetObjProperty(item, "InvisibilityPotion"))
					if (GetObjProperty(item, "ByTrueMageInvispot") != (GetObjProperty(what, "ByTrueMage")))
						SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
						return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMageInvispot", GetObjProperty(what,"ByTrueMage"));
					endif
					SetObjProperty(item, "InvisibilityPotion", GetObjProperty(item,"InvisibilityPotion") + CINT(what.amount));
				else
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMageInvispot", GetObjProperty(what,"ByTrueMage"));
					endif
					SetObjProperty(item, "InvisibilityPotion",CINT(what.amount));
				endif 
			24:
			if (GetObjProperty(item, "FineIntellect"))
					if (GetObjProperty(item, "ByTrueMagefineint") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
						return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagefineint", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "FineIntellect", GetObjProperty(item,"FineIntellect") + CINT(what.amount));
					else
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagefineint", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "FineIntellect",CINT(what.amount));
				endif	
			25:
			if (GetObjProperty(item, "FabulousIntellect"))
					if (GetObjProperty(item, "ByTrueMagefabint") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
						return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagefabint", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "FabulousIntellect", GetObjProperty(item,"FabulousIntellect") + CINT(what.amount));
					else
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagefabint", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "FabulousIntellect",CINT(what.amount));
				endif
					
			26:
			if (GetObjProperty(item, "FantasticIntellect"))
					if (GetObjProperty(item, "ByTrueMagefanint") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
							 return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagefanint", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "FantasticIntellect", GetObjProperty(item,"FantasticIntellect") + CINT(what.amount));
					else
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagefanint", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "FantasticIntellect",CINT(what.amount));
				endif
			27:
			if (GetObjProperty(item, "lesserMegoInvul"))
					if (GetObjProperty(item, "ByTrueMagelinv") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
							 return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagelinv", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "lesserMegoInvul", GetObjProperty(item,"lesserMegoInvul") + CINT(what.amount));
					else
						SetObjProperty(item,"ByTrueMagelinv", GetObjProperty(what,"ByTrueMage"));
						SetObjProperty(item, "lesserMegoInvul",CINT(what.amount));
				endif 
			28:
			if (GetObjProperty(item, "MegoInvulnerabilitypotion"))
				if (GetObjProperty(item, "ByTrueMageMinv") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
							 return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMageMinv", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "MegoInvulnerabilitypotion", GetObjProperty(item,"MegoInvulnerabilitypotion") + CINT(what.amount));
					else
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMageMinv", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "MegoInvulnerabilitypotion",CINT(what.amount));
				endif
			29:
			if (GetObjProperty(item, "greaterMegoInvulnerabilitypotion"))
					if (GetObjProperty(item, "ByTrueMageGMinv") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
							 return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMageGMinv", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "greaterMegoInvulnerabilitypotion", GetObjProperty(item,"greaterMegoInvulnerabilitypotion") + CINT(what.amount));
					else
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMageGMinv", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "greaterMegoInvulnerabilitypotion",CINT(what.amount));
				endif
			30:
			if (GetObjProperty(item, "GrandMageRefreshElixir"))
					if (GetObjProperty(item, "ByTrueMagegmrefresh") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
							 return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagegmrefresh", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "GrandMageRefreshElixir", GetObjProperty(item,"GrandMageRefreshElixir") + CINT(what.amount));
					else
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagegmrefresh", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "GrandMageRefreshElixir",CINT(what.amount));
				endif
				 
			31:
			if (GetObjProperty(item, "HomericMightpotion"))
					if (GetObjProperty(item, "ByTrueMageHompot") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
							 return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMageHompot", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "HomericMightpotion", GetObjProperty(item,"HomericMightpotion") + CINT(what.amount));
					else
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMageHompot", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "HomericMightpotion",CINT(what.amount));
				endif
				 
			32:
			if (GetObjProperty(item, "GreaterHomericMightpotion"))
					if (GetObjProperty(item, "ByTrueMageGHompot") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
							 return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMageGHompot", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "GreaterHomericMightpotion", GetObjProperty(item,"GreaterHomericMightpotion") + CINT(what.amount));
					else
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMageGHompot", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "GreaterHomericMightpotion",CINT(what.amount));
				endif
				 
			33:
			if (GetObjProperty(item, "TamlaHealpotion"))
			if (GetObjProperty(item, "ByTrueMagetalmpot") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
							 return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagetalmpot", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "TamlaHealpotion", GetObjProperty(item,"TamlaHealpotion") + CINT(what.amount));
						
					else
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagetalmpot", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "TamlaHealpotion",CINT(what.amount));
				endif 
			34:
			if (GetObjProperty(item, "MinorTransmutation"))
					if (GetObjProperty(item, "ByTrueMagemintrans") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
							 return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagemintrans", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "MinorTransmutation", GetObjProperty(item,"MinorTransmutation") + CINT(what.amount));
					else
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagemintrans", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "MinorTransmutation",CINT(what.amount));
				endif 
				
			35:
			if (GetObjProperty(item, "MajorTransmutation"))
					if (GetObjProperty(item, "ByTrueMagemajtrans") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
							 return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagemajtrans", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "MajorTransmutation", GetObjProperty(item,"MajorTransmutation") + CINT(what.amount));
					else
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagemajtrans", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "MajorTransmutation",CINT(what.amount));
				endif 
			36:
			if (GetObjProperty(item, "Totem"))
				if (GetObjProperty(item, "ByTrueMageTotem") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
							 return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMageTotem", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "Totem", GetObjProperty(item,"Totem") + CINT(what.amount));
					else
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMageTotem", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "Totem",CINT(what.amount));
				endif
			37:
			if (GetObjProperty(item, "Elixer"))
				if (GetObjProperty(item, "ByTrueMageElixer") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
							 return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMageElixer", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "Elixer", GetObjProperty(item,"Elixer") + CINT(what.amount));
					else
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMageElixer", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "Elixer",CINT(what.amount));
				endif
				
			39:
			if (GetObjProperty(item, "GreatElixerium"))
					if (GetObjProperty(item, "ByTrueMagegElixer") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
							 return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagegElixer", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "GreatElixerium", GetObjProperty(item,"GreatElixerium") + CINT(what.amount));
					else
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagegElixer", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "GreatElixerium",CINT(what.amount));
				endif
				
				
			40:
			if (GetObjProperty(item, "MegoElixerium"))
			if (GetObjProperty(item, "ByTrueMageMElixer") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
							 return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMageMElixer", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "MegoElixerium", GetObjProperty(item,"MegoElixerium") + CINT(what.amount));
					else
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMageMElixer", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "MegoElixerium",CINT(what.amount));
				endif 
			43:
			if (GetObjProperty(item, "DispelPotion"))
					if (GetObjProperty(item, "ByTrueMagedispot") != (GetObjProperty(what, "ByTrueMage")))
					SendSysmessage(who, "To place this potion, get rid of the existing in the cabinet",color:= 2030,font:= 3 );
							 return;
					endif
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagedispot", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "DispelPotion", GetObjProperty(item,"DispelPotion") + CINT(what.amount));
					else
					if (GetObjProperty(what,"ByTrueMage"))
						SetObjProperty(item,"ByTrueMagedispot", GetObjProperty(what,"ByTrueMage"));
						endif
						SetObjProperty(item, "DispelPotion",CINT(what.amount));
				endif
			
			default: 
				SendSysmessage(who, "There is no place for this item.",color:= 2030,font:= 3 );
				return;
		endcase
	0x0f3f:
		if (GetObjProperty(item, "ammoarrow"))
			SetObjProperty(item,"ammoarrow",GetObjProperty(item,"ammoarrow") + CINT(what.amount));
		else
			SetObjProperty(item, "ammoarrow",CINT(what.amount));
		endif 
	0x1bfb:
		if (GetObjProperty(item, "ammobolt"))
			SetObjProperty(item,"ammobolt",GetObjProperty(item,"ammobolt") + CINT(what.amount));
		else
			SetObjProperty(item, "ammobolt",CINT(what.amount));
		endif 
	0x6051:
		if (GetObjProperty(item, "ammofire"))
			SetObjProperty(item,"ammofire",GetObjProperty(item,"ammofire") + CINT(what.amount));
		else
			SetObjProperty(item, "ammofire",CINT(what.amount));
		endif 
	0xb200:
		if (GetObjProperty(item, "ammoice"))
			SetObjProperty(item,"ammoice",GetObjProperty(item,"ammoice") + CINT(what.amount));
		else
			SetObjProperty(item, "ammoice",CINT(what.amount));
		endif 
	0x824e:
		if (GetObjProperty(item, "ammothunder"))
			SetObjProperty(item,"ammothunder",GetObjProperty(item,"ammothunder") + CINT(what.amount));
		else
			SetObjProperty(item, "ammothunder",CINT(what.amount));
		endif 
	0xbbb1:
		if (GetObjProperty(item, "ammothrow"))
			SetObjProperty(item,"ammothrow",GetObjProperty(item,"ammothrow") + CINT(what.amount));
		else
			SetObjProperty(item, "ammothrow",CINT(what.amount));
		endif 
		
	0xd90f:
		if (GetObjProperty(item, "ammogun"))
			SetObjProperty(item,"ammogun",GetObjProperty(item,"ammogun") + CINT(what.amount));
		else
			SetObjProperty(item, "ammogun",CINT(what.amount));
		endif 
	0x1BD4:
		if (GetObjProperty(item, "ammoshaft"))
			SetObjProperty(item,"ammoshaft",GetObjProperty(item,"ammoshaft") + CINT(what.amount));
		else
			SetObjProperty(item, "ammoshaft",CINT(what.amount));
		endif 
	0x1bd1:
		if (GetObjProperty(item, "ammofeather"))
			SetObjProperty(item,"ammofeather",GetObjProperty(item,"ammofeather") + CINT(what.amount));
		else
			SetObjProperty(item, "ammofeather",CINT(what.amount));
		endif
	0xB101:
		if (GetObjProperty(item, "Antidotescroll"))
			SetObjProperty(item,"Antidotescroll",GetObjProperty(item,"Antidotescroll") + CINT(what.amount));
		else
			SetObjProperty(item, "Antidotescroll",CINT(what.amount));
		endif 
	0xB102:
		if (GetObjProperty(item, "Owlsightscroll"))
			SetObjProperty(item,"Owlsightscroll",GetObjProperty(item,"Owlsightscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "Owlsightscroll",CINT(what.amount));
		endif 
	0xB103:
		if (GetObjProperty(item, "Shiftingearthscroll"))
			SetObjProperty(item,"Shiftingearthscroll",GetObjProperty(item,"Shiftingearthscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "Shiftingearthscroll",CINT(what.amount));
		endif 
	0xB104:
		if (GetObjProperty(item, "Summonmammalsscroll"))
			SetObjProperty(item,"Summonmammalsscroll",GetObjProperty(item,"Summonmammalsscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "Summonmammalsscroll",CINT(what.amount));
		endif 
	0xB105:
		if (GetObjProperty(item, "Calllightningscroll"))
			SetObjProperty(item,"Calllightningscroll",GetObjProperty(item,"Calllightningscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "Calllightningscroll",CINT(what.amount));
		endif 
	0xB106:
		if (GetObjProperty(item, "Earthblessingscroll"))
			SetObjProperty(item,"Earthblessingscroll",GetObjProperty(item,"Earthblessingscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "Earthblessingscroll",CINT(what.amount));
		endif 
	0xB107:
		if (GetObjProperty(item, "Earthportalscroll"))
			SetObjProperty(item,"Earthportalscroll",GetObjProperty(item,"Earthportalscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "Earthportalscroll",CINT(what.amount));
		endif 
	0xB108:
		if (GetObjProperty(item, "Naturestouchscroll"))
			SetObjProperty(item,"Naturestouchscroll",GetObjProperty(item,"Naturestouchscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "Naturestouchscroll",CINT(what.amount));
		endif 
	0xB109:
		if (GetObjProperty(item, "Gustofairscroll"))
			SetObjProperty(item,"Gustofairscroll",GetObjProperty(item,"Gustofairscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "Gustofairscroll",CINT(what.amount));
		endif 
	0xB10A:
		if (GetObjProperty(item, "Risingfirescroll"))
			SetObjProperty(item,"Risingfirescroll",GetObjProperty(item,"Risingfirescroll") + CINT(what.amount));
		else
			SetObjProperty(item, "Risingfirescroll",CINT(what.amount));
		endif 
	0xB10B:
		if (GetObjProperty(item, "Shapeshiftscroll"))
			SetObjProperty(item,"Shapeshiftscroll",GetObjProperty(item,"Shapeshiftscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "Shapeshiftscroll",CINT(what.amount));
		endif 
	0xB10C:
		if (GetObjProperty(item, "Icestrikescroll"))
			SetObjProperty(item,"Icestrikescroll",GetObjProperty(item,"Icestrikescroll") + CINT(what.amount));
		else
			SetObjProperty(item, "Icestrikescroll",CINT(what.amount));
		endif 
	0xB10D:
		if (GetObjProperty(item, "Earthspiritscroll"))
			SetObjProperty(item,"Earthspiritscroll",GetObjProperty(item,"Earthspiritscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "Earthspiritscroll",CINT(what.amount));
		endif 
	0xB10E:
		if (GetObjProperty(item, "Flamespiritscroll"))
			SetObjProperty(item,"Flamespiritscroll",GetObjProperty(item,"Flamespiritscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "Flamespiritscroll",CINT(what.amount));
		endif 
	0xB10F:
		if (GetObjProperty(item, "Stormspiritscroll"))
			SetObjProperty(item,"Stormspiritscroll",GetObjProperty(item,"Stormspiritscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "Stormspiritscroll",CINT(what.amount));
		endif 
	0xB110:
		if (GetObjProperty(item, "Waterspiritscroll"))
			SetObjProperty(item,"Waterspiritscroll",GetObjProperty(item,"Waterspiritscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "Waterspiritscroll",CINT(what.amount));
		endif 
	0xA101:
		if (GetObjProperty(item, "ControlUndeadScroll"))
			SetObjProperty(item,"ControlUndeadScroll",GetObjProperty(item,"ControlUndeadScroll") + CINT(what.amount));
		else
			SetObjProperty(item, "ControlUndeadScroll",CINT(what.amount));
		endif 
	0xA102:
		if (GetObjProperty(item, "DarknessScroll"))
			SetObjProperty(item,"DarknessScroll",GetObjProperty(item,"DarknessScroll") + CINT(what.amount));
		else
			SetObjProperty(item, "DarknessScroll",CINT(what.amount));
		endif 
	0xA103:
		if (GetObjProperty(item, "DecayingRayScroll"))
			SetObjProperty(item,"DecayingRayScroll",GetObjProperty(item,"DecayingRayScroll") + CINT(what.amount));
		else
			SetObjProperty(item, "DecayingRayScroll",CINT(what.amount));
		endif 
	0xA104:
		if (GetObjProperty(item, "SpectresTouchScroll"))
			SetObjProperty(item,"SpectresTouchScroll",GetObjProperty(item,"SpectresTouchScroll") + CINT(what.amount));
		else
			SetObjProperty(item, "SpectresTouchScroll",CINT(what.amount));
		endif 
	0xA105:
		if (GetObjProperty(item, "AbyssalFlameScroll"))
			SetObjProperty(item,"AbyssalFlameScroll",GetObjProperty(item,"AbyssalFlameScroll") + CINT(what.amount));
		else
			SetObjProperty(item, "AbyssalFlameScroll",CINT(what.amount));
		endif 
	0xA106:
		if (GetObjProperty(item, "AnimateDeadScroll"))
			SetObjProperty(item,"AnimateDeadScroll",GetObjProperty(item,"AnimateDeadScroll") + CINT(what.amount));
		else
			SetObjProperty(item, "AnimateDeadScroll",CINT(what.amount));
		endif 
	0xA107:
		if (GetObjProperty(item, "SacrificeScroll"))
			SetObjProperty(item,"SacrificeScroll",GetObjProperty(item,"SacrificeScroll") + CINT(what.amount));
		else
			SetObjProperty(item, "SacrificeScroll",CINT(what.amount));
		endif 
	0xA108:
		if (GetObjProperty(item, "WraithsBreathScroll"))
			SetObjProperty(item,"WraithsBreathScroll",GetObjProperty(item,"WraithsBreathScroll") + CINT(what.amount));
		else
			SetObjProperty(item, "WraithsBreathScroll",CINT(what.amount));
		endif 
	0xA109:
		if (GetObjProperty(item, "SorcerersBaneScroll"))
			SetObjProperty(item,"SorcerersBaneScroll",GetObjProperty(item,"SorcerersBaneScroll") + CINT(what.amount));
		else
			SetObjProperty(item, "SorcerersBaneScroll",CINT(what.amount));
		endif 
	0xA10A:
		if (GetObjProperty(item, "SummonSpiritScroll"))
			SetObjProperty(item,"SummonSpiritScroll",GetObjProperty(item,"SummonSpiritScroll") + CINT(what.amount));
		else
			SetObjProperty(item, "SummonSpiritScroll",CINT(what.amount));
		endif 
	0xA10B:
		if (GetObjProperty(item, "WraithformScroll"))
			SetObjProperty(item,"WraithformScroll",GetObjProperty(item,"WraithformScroll") + CINT(what.amount));
		else
			SetObjProperty(item, "WraithformScroll",CINT(what.amount));
		endif 
	0xA10C:
		if (GetObjProperty(item, "WyvernStrikeScroll"))
			SetObjProperty(item,"WyvernStrikeScroll",GetObjProperty(item,"WyvernStrikeScroll") + CINT(what.amount));
		else
			SetObjProperty(item, "WyvernStrikeScroll",CINT(what.amount));
		endif 
	0xA10D:
		if (GetObjProperty(item, "KillScroll"))
			SetObjProperty(item,"KillScroll",GetObjProperty(item,"KillScroll") + CINT(what.amount));
		else
			SetObjProperty(item, "KillScroll",CINT(what.amount));
		endif 
	0xA10E:
		if (GetObjProperty(item, "LicheScroll"))
			SetObjProperty(item,"LicheScroll",GetObjProperty(item,"LicheScroll") + CINT(what.amount));
		else
			SetObjProperty(item, "LicheScroll",CINT(what.amount));
		endif 
	0xA10F:
		if (GetObjProperty(item, "PlagueScroll"))
			SetObjProperty(item,"PlagueScroll",GetObjProperty(item,"PlagueScroll") + CINT(what.amount));
		else
			SetObjProperty(item, "PlagueScroll",CINT(what.amount));
		endif 
	0xA110:
		if (GetObjProperty(item, "SpellbindScroll"))
			SetObjProperty(item,"SpellbindScroll",GetObjProperty(item,"SpellbindScroll") + CINT(what.amount));
		else
			SetObjProperty(item, "SpellbindScroll",CINT(what.amount));
		endif 
	0x6178:
		if (GetObjProperty(item, "songscroll1"))
			SetObjProperty(item,"songscroll1",GetObjProperty(item,"songscroll1") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll1",CINT(what.amount));
		endif 
	0x6179:
		if (GetObjProperty(item, "songscroll2"))
			SetObjProperty(item,"songscroll2",GetObjProperty(item,"songscroll2") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll2",CINT(what.amount));
		endif 
	0x617a:
		if (GetObjProperty(item, "songscroll3"))
			SetObjProperty(item,"songscroll3",GetObjProperty(item,"songscroll3") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll3",CINT(what.amount));
		endif 
	0x617b:
		if (GetObjProperty(item, "songscroll4"))
			SetObjProperty(item,"songscroll4",GetObjProperty(item,"songscroll4") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll4",CINT(what.amount));
		endif 
	0x617c:
		if (GetObjProperty(item, "songscroll5"))
			SetObjProperty(item,"songscroll5",GetObjProperty(item,"songscroll5") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll5",CINT(what.amount));
		endif 
	0x617d:
		if (GetObjProperty(item, "songscroll6"))
			SetObjProperty(item,"songscroll6",GetObjProperty(item,"songscroll6") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll6",CINT(what.amount));
		endif 
	0x617e:
		if (GetObjProperty(item, "songscroll7"))
			SetObjProperty(item,"songscroll7",GetObjProperty(item,"songscroll7") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll7",CINT(what.amount));
		endif 
	0x617f:
		if (GetObjProperty(item, "songscroll8"))
			SetObjProperty(item,"songscroll8",GetObjProperty(item,"songscroll8") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll8",CINT(what.amount));
		endif 
	0x6180:
		if (GetObjProperty(item, "songscroll9"))
			SetObjProperty(item,"songscroll9",GetObjProperty(item,"songscroll9") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll9",CINT(what.amount));
		endif 
	0x6181:
		if (GetObjProperty(item, "songscroll10"))
			SetObjProperty(item,"songscroll10",GetObjProperty(item,"songscroll10") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll10",CINT(what.amount));
		endif 
	0x6182:
		if (GetObjProperty(item, "songscroll11"))
			SetObjProperty(item,"songscroll11",GetObjProperty(item,"songscroll11") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll11",CINT(what.amount));
		endif 
	0x6183:
		if (GetObjProperty(item, "songscroll12"))
			SetObjProperty(item,"songscroll12",GetObjProperty(item,"songscroll12") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll12",CINT(what.amount));
		endif 
	0x6184:
		if (GetObjProperty(item, "songscroll13"))
			SetObjProperty(item,"songscroll13",GetObjProperty(item,"songscroll13") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll13",CINT(what.amount));
		endif 
	0x6185:
		if (GetObjProperty(item, "songscroll14"))
			SetObjProperty(item,"songscroll14",GetObjProperty(item,"songscroll14") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll14",CINT(what.amount));
		endif 
	0x6186:
		if (GetObjProperty(item, "songscroll15"))
			SetObjProperty(item,"songscroll15",GetObjProperty(item,"songscroll15") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll15",CINT(what.amount));
		endif 
	0x6187:
		if (GetObjProperty(item, "songscroll16"))
			SetObjProperty(item,"songscroll16",GetObjProperty(item,"songscroll16") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll16",CINT(what.amount));
		endif 
	0x6188:
		if (GetObjProperty(item, "songscroll17"))
			SetObjProperty(item,"songscroll17",GetObjProperty(item,"songscroll17") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll17",CINT(what.amount));
		endif 
	0x6189:
		if (GetObjProperty(item, "songscroll18"))
			SetObjProperty(item,"songscroll18",GetObjProperty(item,"songscroll18") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll18",CINT(what.amount));
		endif 
	0x618a:
		if (GetObjProperty(item, "songscroll19"))
			SetObjProperty(item,"songscroll19",GetObjProperty(item,"songscroll19") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll19",CINT(what.amount));
		endif 
	0x618b:
		if (GetObjProperty(item, "songscroll20"))
			SetObjProperty(item,"songscroll20",GetObjProperty(item,"songscroll20") + CINT(what.amount));
		else
			SetObjProperty(item, "songscroll20",CINT(what.amount));
		endif 
	0x6167:
		if (GetObjProperty(item, "holyscroll1"))
			SetObjProperty(item,"holyscroll1",GetObjProperty(item,"holyscroll1") + CINT(what.amount));
		else
			SetObjProperty(item, "holyscroll1",CINT(what.amount));
		endif 
	0x6168:
		if (GetObjProperty(item, "holyscroll2"))
			SetObjProperty(item,"holyscroll2",GetObjProperty(item,"holyscroll2") + CINT(what.amount));
		else
			SetObjProperty(item, "holyscroll2",CINT(what.amount));
		endif 
	0x6169:
		if (GetObjProperty(item, "holyscroll3"))
			SetObjProperty(item,"holyscroll3",GetObjProperty(item,"holyscroll3") + CINT(what.amount));
		else
			SetObjProperty(item, "holyscroll3",CINT(what.amount));
		endif 
	0x616a:
		if (GetObjProperty(item, "holyscroll4"))
			SetObjProperty(item,"holyscroll4",GetObjProperty(item,"holyscroll4") + CINT(what.amount));
		else
			SetObjProperty(item, "holyscroll4",CINT(what.amount));
		endif 
	0x616b:
		if (GetObjProperty(item, "holyscroll5"))
			SetObjProperty(item,"holyscroll5",GetObjProperty(item,"holyscroll5") + CINT(what.amount));
		else
			SetObjProperty(item, "holyscroll5",CINT(what.amount));
		endif 
	0x616c:
		if (GetObjProperty(item, "holyscroll6"))
			SetObjProperty(item,"holyscroll6",GetObjProperty(item,"holyscroll6") + CINT(what.amount));
		else
			SetObjProperty(item, "holyscroll6",CINT(what.amount));
		endif 
	0x616d:
		if (GetObjProperty(item, "holyscroll7"))
			SetObjProperty(item,"holyscroll7",GetObjProperty(item,"holyscroll7") + CINT(what.amount));
		else
			SetObjProperty(item, "holyscroll7",CINT(what.amount));
		endif 
	0x616e:
		if (GetObjProperty(item, "holyscroll8"))
			SetObjProperty(item,"holyscroll8",GetObjProperty(item,"holyscroll8") + CINT(what.amount));
		else
			SetObjProperty(item, "holyscroll8",CINT(what.amount));
		endif 
	0x616f:
		if (GetObjProperty(item, "holyscroll9"))
			SetObjProperty(item,"holyscroll9",GetObjProperty(item,"holyscroll9") + CINT(what.amount));
		else
			SetObjProperty(item, "holyscroll9",CINT(what.amount));
		endif 
	0x0E34:
		if (GetObjProperty(item, "blankscroll"))
			SetObjProperty(item,"blankscroll",GetObjProperty(item,"blankscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "blankscroll",CINT(what.amount));
		endif 
	0x6001:
		if (GetObjProperty(item, "blankmap"))
			SetObjProperty(item,"blankmap",GetObjProperty(item,"blankmap") + CINT(what.amount));
		else
			SetObjProperty(item, "blankmap",CINT(what.amount));
		endif 
	0x14fb:
		if (GetObjProperty(item, "lockpick"))
			SetObjProperty(item,"lockpick",GetObjProperty(item,"lockpick") + CINT(what.amount));
		else
			SetObjProperty(item, "lockpick",CINT(what.amount));
		endif 
	0x0F0E:
		if (GetObjProperty(item, "emptybottle"))
			SetObjProperty(item,"emptybottle",GetObjProperty(item,"emptybottle") + CINT(what.amount));
		else
			SetObjProperty(item, "emptybottle",CINT(what.amount));
		endif 
	0x1f14:
		if (GetObjProperty(item, "recallrune"))
			SetObjProperty(item,"recallrune",GetObjProperty(item,"recallrune") + CINT(what.amount));
		else
			SetObjProperty(item, "recallrune",CINT(what.amount));
		endif 
	0x0de1:
		if (GetObjProperty(item, "kindling"))
			SetObjProperty(item,"kindling",GetObjProperty(item,"kindling") + CINT(what.amount));
		else
			SetObjProperty(item, "kindling",CINT(what.amount));
		endif 
	0x0e21:
		if (GetObjProperty(item, "bandages"))
			SetObjProperty(item,"bandages",GetObjProperty(item,"bandages") + CINT(what.amount));
		else
			SetObjProperty(item, "bandages",CINT(what.amount));
		endif 
	0x181d:
		if (GetObjProperty(item, "SymbolOfAbsorption"))
			SetObjProperty(item,"SymbolOfAbsorption",GetObjProperty(item,"SymbolOfAbsorption") + CINT(what.amount));
		else
			SetObjProperty(item, "SymbolOfAbsorption",CINT(what.amount));
		endif 
	0x181e:
		if (GetObjProperty(item, "SymbolOfToxinsResistance"))
			SetObjProperty(item,"SymbolOfToxinsResistance",GetObjProperty(item,"SymbolOfToxinsResistance") + CINT(what.amount));
		else
			SetObjProperty(item, "SymbolOfToxinsResistance",CINT(what.amount));
		endif 
	0x181f:
		if (GetObjProperty(item, "SymbolOfHealth"))
			SetObjProperty(item,"SymbolOfHealth",GetObjProperty(item,"SymbolOfHealth") + CINT(what.amount));
		else
			SetObjProperty(item, "SymbolOfHealth",CINT(what.amount));
		endif 
	0x1821:
		if (GetObjProperty(item, "SymbolOfHeavenTouch"))
			SetObjProperty(item,"SymbolOfHeavenTouch",GetObjProperty(item,"SymbolOfHeavenTouch") + CINT(what.amount));
		else
			SetObjProperty(item, "SymbolOfHeavenTouch",CINT(what.amount));
		endif 
	0x1822:
		if (GetObjProperty(item, "SymbolOfHellFire"))
			SetObjProperty(item,"SymbolOfHellFire",GetObjProperty(item,"SymbolOfHellFire") + CINT(what.amount));
		else
			SetObjProperty(item, "SymbolOfHellFire",CINT(what.amount));
		endif 
	0x1823:
		if (GetObjProperty(item, "SymbolOfVanishing"))
			SetObjProperty(item,"SymbolOfVanishing",GetObjProperty(item,"SymbolOfVanishing") + CINT(what.amount));
		else
			SetObjProperty(item, "SymbolOfVanishing",CINT(what.amount));
		endif 
	0x1824:
		if (GetObjProperty(item, "SymbolOfVengeance"))
			SetObjProperty(item,"SymbolOfVengeance",GetObjProperty(item,"SymbolOfVengeance") + CINT(what.amount));
		else
			SetObjProperty(item, "SymbolOfVengeance",CINT(what.amount));
		endif 
	0x1825:
		if (GetObjProperty(item, "SymbolOfRecalling"))
			SetObjProperty(item,"SymbolOfRecalling",GetObjProperty(item,"SymbolOfRecalling") + CINT(what.amount));
		else
			SetObjProperty(item, "SymbolOfRecalling",CINT(what.amount));
		endif 
	0x1826:
		if (GetObjProperty(item, "SymbolOfThunderStorm"))
			SetObjProperty(item,"SymbolOfThunderStorm",GetObjProperty(item,"SymbolOfThunderStorm") + CINT(what.amount));
		else
			SetObjProperty(item, "SymbolOfThunderStorm",CINT(what.amount));
		endif 
	0x1827:
		if (GetObjProperty(item, "SymbolOfRegeneration"))
			SetObjProperty(item,"SymbolOfRegeneration",GetObjProperty(item,"SymbolOfRegeneration") + CINT(what.amount));
		else
			SetObjProperty(item, "SymbolOfRegeneration",CINT(what.amount));
		endif 
	0x1828:
		if (GetObjProperty(item, "SymbolOfLifeStream"))
			SetObjProperty(item,"SymbolOfLifeStream",GetObjProperty(item,"SymbolOfLifeStream") + CINT(what.amount));
		else
			SetObjProperty(item, "SymbolOfLifeStream",CINT(what.amount));
		endif 
	0xf022:
		if (GetObjProperty(item, "castspeedupgrade"))
			SetObjProperty(item,"castspeedupgrade",GetObjProperty(item,"castspeedupgrade") + CINT(what.amount));
		else
			SetObjProperty(item, "castspeedupgrade",CINT(what.amount));
		endif 
	0xf025:
		if (GetObjProperty(item, "hitupgrade"))
			SetObjProperty(item,"hitupgrade",GetObjProperty(item,"hitupgrade") + CINT(what.amount));
		else
			SetObjProperty(item, "hitupgrade",CINT(what.amount));
		endif 
	0xf028:
		if (GetObjProperty(item, "damagebonus"))
			SetObjProperty(item,"damagebonus",GetObjProperty(item,"damagebonus") + CINT(what.amount));
		else
			SetObjProperty(item, "damagebonus",CINT(what.amount));
		endif 
	0xf029:
		if (GetObjProperty(item, "armorupgrade"))
			SetObjProperty(item,"armorupgrade",GetObjProperty(item,"armorupgrade") + CINT(what.amount));
		else
			SetObjProperty(item, "armorupgrade",CINT(what.amount));
		endif 
	0xf031:
		if (GetObjProperty(item, "damagebonusPhys"))
			SetObjProperty(item,"damagebonusPhys",GetObjProperty(item,"damagebonusPhys") + CINT(what.amount));
		else
			SetObjProperty(item, "damagebonusPhys",CINT(what.amount));
		endif 
	0x9e14:
		if (GetObjProperty(item, "CrystalBall"))
			SetObjProperty(item,"CrystalBall",GetObjProperty(item,"CrystalBall") + CINT(what.amount));
		else
			SetObjProperty(item, "CrystalBall",CINT(what.amount));
		endif 


	default:
		SendSysmessage(who, "There is no place for this item.",color:= 2030,font:= 3 );
		return;
	endcase
	DestroyItem(what);
endfunction


function rescollect(who, item)
	SendSysmessage(who, "What item do you want to put in the closet?",color:= 2030,font:= 3 );

	var what := Target(who, TGTOPT_CHECK_LOS);

	if (coordist( item.x, item.y, who.x, who.y ) > 6)
		SendSysmessage(who, "Too far away",color:= 2030,font:= 3 );
		return;
	endif	

	var obbjtype := {
		0x0F85,0x0F86,0x0F84,0x0F88,0x0F8C,0x0F8D,0x0F7A,0x0F7B,0x0F78,0x0F79,0x0F7C,0x0F7D,0x0F7E,
		0x0F7F,0x0F80,0x0F81,0x0F82,0x0F83,0x0F87,0x0F89,0x0F8A,0x0F8B,0x0F8E,0x0F8F,0x0F90,0x0F91,
		0x0F0F,0x0F10,0x0F11,0x0F13,0x0F15,0x0F16,0x0F18,0x0F25,0x0F30,0x6011,0x6012,0x6013,0x6014,
		0x6015,0x6016,0x6017,0x6018,0xc510,0xc511,0xc512,0xc513,0xc514,0xc515,0xc516,0xc517,
		0x1765,0xee19,0x1be9,0x1078,0x7020,0x7021,0x7022,0x702d,0x7023,0x7025,
		0x7026,0x7028,0x702a,0x7024,0x7027,0x702f,0x7029,0x702b,0x702c,0x1BDD,0x7300,0x7301,
		0x7302,0x7303,0x7304,0x7305,0x7306,0x7307,0x7308,0x7309,0x730a,0x730b,0x730c,0xee20,0x099B,
		0x099F,0x09C7,0x1f96,0x1f98,0x1f9a,0x1f9c,0x1f9e,0x09ad,0x1F85,0x09EE,0x1F8D,0x1F7D,0x1F89,
		0x1F91,0x1045,0x09f1,0x097a,0x09b9,0x09c9,0x0976,0x1e8a,0x1607,0x1609,0x09ec,0x1726,0xc803,
		0xc804,0x09cd,0x09ce,0x09cf,0x097E,0x1608,0x160a,0xc923,0x097b,0x1e1e,0x09b7,0x09f2,0xA368,
		0xA369,0xA36A,0xA36B,0xA36C,0xA36D,0xA36E,0xA36F,0xc912,0xc942,0xc943,0x27bc,0x0c6d,0x0eed,
		0x3b9a,0xdf0c,0x7059,0xdc01,0xdc02,0xdc03,0xdc04,0xdc05,0xdc06,0xdc07,0xdc08,0xdc09,0xdc0b,
		0xdc0c,0xdc0d,0xdc0e,0xdc0f,0xdc10,0xdc11,0xdc12,0xdc14,0xdc15,0xdc16,0xdc17,0xdce6,0xdce7,
		0xdce8,0x0f3f,0x1bfb,0x6051,0xb200,0x824e,0xbbb1,0xd90f,0x1BD4,0x1bd1,0xB101,0xB102,0xB103,
		0xB104,0xB105,0xB106,0xB107,0xB108,0xB109,0xB10a,0xB10b,0xB10c,0xB10d,0xB10e,0xB10f,0xB110,
		0xA101,0xA102,0xA103,0xA104,0xA105,0xA106,0xA107,0xA108,0xA109,0xA10a,0xA10b,0xA10c,0xA10d,
		0xA10e,0xA10f,0xA110,0x6178,0x6179,0x617a,0x617b,0x617c,0x617d,0x617e,0x617f,0x6180,0x6181,
		0x6182,0x6183,0x6184,0x6185,0x6186,0x6187,0x6188,0x6189,0x618a,0x618b,0x6167,0x6168,0x6169,
		0x616a,0x616b,0x616c,0x616d,0x616e,0x616f,0x0E34,0x6001,0x14fb,0x0F0E,0x1f14,0x0de1,0x0e21,
		0x181d,0x181e,0x181f,0x1821,0x1822,0x1823,0x1824,0x1825,0x1826,0x1827,0x1828,0xd05c,0xd05d,
		0xd05e,0xd05f,0xd060,0xd061,0xd062,0xd063,0xd064,0xd065,0xd066,0xd067,0xd068,0xd069,0xd06a,
		0xd06d,0xd096,0xd07d,0xd095,0xd071,0xd094,0xd087,0xd097,0xd06e,0xd08f,0xd08b,0xd078,0xd07e,
		0xd092,0xd093,0xd079,0xd06c,0xd07c,0xd083,0xd06f,0xd085,0xd09a,0xd086,0xd072,0xd080,0xd089,
		0xd075,0xd082,0xd070,0xd073,0xd074,0xd077,0xd098,0xd099,0xd08e,0xd091,0xd07a,0xd081,0xd084,
		0xd08a,0xd088,0xd08d,0xd09b,0xd076,0xd07f,0xd09c,0xd090,0xf022,0xf025,0xf028,0xf029,0xd08c,
		0xd07b,0xf031,0x9e14
	
	};

	while (what)
		
        if (what.serial != who.backpack.serial and !IsInContainer( who.backpack, what))
			SendSysmessage( who, "That item has to be in your backpack." ,color:= 2030,font:= 3 );
			return;
		endif

		SendSysmessage( who, "Press ESC if you want to cancel the cursor.." ,color:= 2030,font:= 3 );
	
		if (what.isa(POLCLASS_CONTAINER))
			
			var max_count := 0;
			foreach thing in EnumerateItemsInContainer(what)
				if(max_count >50)
					break;
				endif
			
				if (thing.objtype in obbjtype) // objtype у thing.objtype - правильный атрибут типа вещи?
					store_collection_item(who, thing, item);
					max_count++;
				endif
			endforeach
		
		elseif (what.objtype in obbjtype)
			store_collection_item(who, what, item);
		else
			SendSysmessage(who, "This is the wrong item.",color:= 2030,font:= 3 );
		endif

		what := Target( who, TGTOPT_CHECK_LOS );
	endwhile
endfunction
