use os;
use uo;
use cfgfile;
use attributes;

function MandrakeRoot( item )
  return CInt( GetObjProperty( item, "MandrakeRoot" ) );
endfunction
function Ginsengs( item )
  return CInt( GetObjProperty( item, "Ginsengs" ) );
endfunction
function Garlic( item )
  return CInt( GetObjProperty( item, "Garlic" ) );
endfunction
function Nightshade( item )
  return CInt( GetObjProperty( item, "Nightshade" ) );
endfunction
function SulphurousAsh( item )
  return CInt( GetObjProperty( item, "SulphurousAsh" ) );
endfunction
function SpiderSilk( item )
  return CInt( GetObjProperty( item, "SpiderSilk" ) );
endfunction
function BlackPearl( item )
  return CInt( GetObjProperty( item, "BlackPearl" ) );
endfunction
function BloodMoss( item )
  return CInt( GetObjProperty( item, "BloodMoss" ) );
endfunction
function Batwing( item )
  return CInt( GetObjProperty( item, "Batwing" ) );
endfunction
function Blackmoor( item )
  return CInt( GetObjProperty( item, "Blackmoor" ) );
endfunction
function Bloodspawn( item )
  return CInt( GetObjProperty( item, "Bloodspawn" ) );
endfunction
function VialOfBlood( item )
  return CInt( GetObjProperty( item, "VialOfBlood" ) );
endfunction
function Bone( item )
  return CInt( GetObjProperty( item, "Bone" ) );
endfunction
function Brimstone( item )
  return CInt( GetObjProperty( item, "Brimstone" ) );
endfunction
function DaemonBone( item )
  return CInt( GetObjProperty( item, "DaemonBone" ) );
endfunction
function FertileDirt( item )
  return CInt( GetObjProperty( item, "FertileDirt" ) );
endfunction
function DragonsBlood( item )
  return CInt( GetObjProperty( item, "DragonsBlood" ) );
endfunction
function ExecutionersCap( item )
  return CInt( GetObjProperty( item, "ExecutionersCap" ) );
endfunction
function EyeOfNewt( item )
  return CInt( GetObjProperty( item, "EyeOfNewt" ) );
endfunction
function Obsidian( item )
  return CInt( GetObjProperty( item, "Obsidian" ) );
endfunction
function PigIron( item )
  return CInt( GetObjProperty( item, "PigIron" ) );
endfunction
function Pumice( item )
  return CInt( GetObjProperty( item, "Pumice" ) );
endfunction
function SerpentsScales( item )
  return CInt( GetObjProperty( item, "SerpentsScales" ) );
endfunction
function VolcanicAsh( item )
  return CInt( GetObjProperty( item, "VolcanicAsh" ) );
endfunction
function Deadwood( item )
  return CInt( GetObjProperty( item, "Deadwood" ) );
endfunction
function WormsHeart( item )
  return CInt( GetObjProperty( item, "WormsHeart" ) );
endfunction
function Starsapphire( item )
  return CInt( GetObjProperty( item, "Starsapphire" ) );
endfunction
function Emerald( item )
  return CInt( GetObjProperty( item, "Emerald" ) );
endfunction
function Sapphire( item )
  return CInt( GetObjProperty( item, "Sapphire" ) );
endfunction
function Ruby( item )
  return CInt( GetObjProperty( item, "Ruby" ) );
endfunction
function Citrine( item )
  return CInt( GetObjProperty( item, "Citrine" ) );
endfunction
function Amethyst( item )
  return CInt( GetObjProperty( item, "Amethyst" ) );
endfunction
function Tourmaline( item )
  return CInt( GetObjProperty( item, "Tourmaline" ) );
endfunction
function Amber( item )
  return CInt( GetObjProperty( item, "Amber" ) );
endfunction
function Diamond( item )
  return CInt( GetObjProperty( item, "Diamond" ) );
endfunction
function IronIngot( item )
  return CInt( GetObjProperty( item, "IronIngot" ) );
endfunction
function CopperIngot( item )
  return CInt( GetObjProperty( item, "CopperIngot" ) );
endfunction
function BlackDwarfIngot( item )
  return CInt( GetObjProperty( item, "BlackDwarfIngot" ) );
endfunction
function PaganIngot( item )
  return CInt( GetObjProperty( item, "PaganIngot" ) );
endfunction
function SilverIngot( item )
  return CInt( GetObjProperty( item, "SilverIngot" ) );
endfunction
function SpectralIngot( item )
  return CInt( GetObjProperty( item, "SpectralIngot" ) );
endfunction
function LavaRockIngot( item )
  return CInt( GetObjProperty( item, "LavaRockIngot" ) );
endfunction
function IceRockIngot( item )
  return CInt( GetObjProperty( item, "IceRockIngot" ) );
endfunction
function MythrilIngot( item )
  return CInt( GetObjProperty( item, "MythrilIngot" ) );
endfunction
function BasiliskIngot( item )
  return CInt( GetObjProperty( item, "BasiliskIngot" ) );
endfunction
function SunIngot( item )
  return CInt( GetObjProperty( item, "SunIngot" ) );
endfunction
function DaedraIngot( item )
  return CInt( GetObjProperty( item, "DaedraIngot" ) );
endfunction
function DoomIngot( item )
  return CInt( GetObjProperty( item, "DoomIngot" ) );
endfunction
function NewZuluIngot( item )
  return CInt( GetObjProperty( item, "NewZuluIngot" ) );
endfunction
function Paradise( item )
  return CInt( GetObjProperty( item, "Paradise" ) );
endfunction
function Hell( item )
  return CInt( GetObjProperty( item, "Hell" ) );
endfunction
function Void( item )
  return CInt( GetObjProperty( item, "Void" ) );
endfunction
function Enchanted( item )
  return CInt( GetObjProperty( item, "Enchanted" ) );
endfunction
function boltofcloth( item )
  return CInt( GetObjProperty( item, "boltofcloth" ) );
endfunction
function cloth( item )
  return CInt( GetObjProperty( item, "cloth" ) );
endfunction
function wool( item )
  return CInt( GetObjProperty( item, "wool" ) );
endfunction
function clay( item )
  return CInt( GetObjProperty( item, "clay" ) );
endfunction
function goldingot( item )
  return CInt( GetObjProperty( item, "goldingot" ) );
endfunction
function hides( item )
  return CInt( GetObjProperty( item, "hides" ) );
endfunction
function lizardhide( item )
  return CInt( GetObjProperty( item, "lizardhide" ) );
endfunction
function imphide( item )
  return CInt( GetObjProperty( item, "imphide" ) );
endfunction
function trollhide( item )
  return CInt( GetObjProperty( item, "trollhide" ) );
endfunction
function terathanhide( item )
  return CInt( GetObjProperty( item, "terathanhide" ) );
endfunction
function necromancerhide( item )
  return CInt( GetObjProperty( item, "necromancerhide" ) );
endfunction
function icehide( item )
  return CInt( GetObjProperty( item, "icehide" ) );
endfunction
function lichehide( item )
  return CInt( GetObjProperty( item, "lichehide" ) );
endfunction
function daemonhide( item )
  return CInt( GetObjProperty( item, "daemonhide" ) );
endfunction
function balronhide( item )
  return CInt( GetObjProperty( item, "balronhide" ) );
endfunction
function soulthreads( item )
  return CInt( GetObjProperty( item, "soulthreads" ) );
endfunction
function drakehide( item )
  return CInt( GetObjProperty( item, "drakehide" ) );
endfunction
function dragonhide( item )
  return CInt( GetObjProperty( item, "dragonhide" ) );
endfunction
function wyvernhide( item )
  return CInt( GetObjProperty( item, "wyvernhide" ) );
endfunction
function wyrmhide( item )
  return CInt( GetObjProperty( item, "wyrmhide" ) );
endfunction
function celestialhide( item )
  return CInt( GetObjProperty( item, "celestialhide" ) );
endfunction
function golddragonhide( item )
  return CInt( GetObjProperty( item, "golddragonhide" ) );
endfunction
function logs( item )
  return CInt( GetObjProperty( item, "logs" ) );
endfunction
function birchlog( item )
  return CInt( GetObjProperty( item, "birchlog" ) );
endfunction
function cherrylog( item )
  return CInt( GetObjProperty( item, "cherrylog" ) );
endfunction
function swamplog( item )
  return CInt( GetObjProperty( item, "swamplog" ) );
endfunction
function oaklog( item )
  return CInt( GetObjProperty( item, "oaklog" ) );
endfunction
function hardrangerlog( item )
  return CInt( GetObjProperty( item, "hardrangerlog" ) );
endfunction
function jadelog( item )
  return CInt( GetObjProperty( item, "jadelog" ) );
endfunction
function stormteallog( item )
  return CInt( GetObjProperty( item, "stormteallog" ) );
endfunction
function blizzardlog( item )
  return CInt( GetObjProperty( item, "blizzardlog" ) );
endfunction
function vulcaniclog( item )
  return CInt( GetObjProperty( item, "vulcaniclog" ) );
endfunction
function vampiriclog( item )
  return CInt( GetObjProperty( item, "vampiriclog" ) );
endfunction
function zululogs( item )
  return CInt( GetObjProperty( item, "zululog" ) );
endfunction
function darknesslog( item )
  return CInt( GetObjProperty( item, "darknesslog" ) );
endfunction
function elvenlog( item )
  return CInt( GetObjProperty( item, "elvenlog" ) );
endfunction
function glass( item )
  return CInt( GetObjProperty( item, "glass" ) );
endfunction
// 	function emptypitcher( item )
// 		return CInt( GetObjProperty( item, "emptypitcher" ));
// 	endfunction
// 	function emptyglass( item )
// 	  return CInt( GetObjProperty( item, "emptyglass" ));
// 	endfunction
function bottleofliquor( item )
  return CInt( GetObjProperty( item, "bottleofliquor" ) );
endfunction
function bottleofale( item )
  return CInt( GetObjProperty( item, "bottleofale" ) );
endfunction
function bottleofwine( item )
  return CInt( GetObjProperty( item, "bottleofwine" ) );
endfunction
function pitcherofale( item )
  return CInt( GetObjProperty( item, "pitcherofale" ) );
endfunction
function pitcherofcider( item )
  return CInt( GetObjProperty( item, "pitcherofcider" ) );
endfunction
function pitcherofliquor( item )
  return CInt( GetObjProperty( item, "pitcherofliquor" ) );
endfunction
function pitcherofwine( item )
  return CInt( GetObjProperty( item, "pitcherofwine" ) );
endfunction
function pitcherofwater( item )
  return CInt( GetObjProperty( item, "pitcherofwater" ) );
endfunction
function pitcherofmilk( item )
  return CInt( GetObjProperty( item, "pitcherofmilk" ) );
endfunction
function glassofliquor( item )
  return CInt( GetObjProperty( item, "glassofliquor" ) );
endfunction
function mugofale( item )
  return CInt( GetObjProperty( item, "mugofale" ) );
endfunction
function glassofwine( item )
  return CInt( GetObjProperty( item, "glassofwine" ) );
endfunction
function glassofcider( item )
  return CInt( GetObjProperty( item, "glassofcider" ) );
endfunction
function glassofmilk( item )
  return CInt( GetObjProperty( item, "glassofmilk" ) );
endfunction
function glassofwater( item )
  return CInt( GetObjProperty( item, "glassofwater" ) );
endfunction
function flour( item )
  return CInt( GetObjProperty( item, "flour" ) );
endfunction
function rawrib( item )
  return CInt( GetObjProperty( item, "rawrib" ) );
endfunction
function rawfishsteak( item )
  return CInt( GetObjProperty( item, "rawfishsteak" ) );
endfunction
function rawbird( item )
  return CInt( GetObjProperty( item, "rawbird" ) );
endfunction
function rawham( item )
  return CInt( GetObjProperty( item, "rawham" ) );
endfunction
function slabofbacon( item )
  return CInt( GetObjProperty( item, "slabofbacon" ) );
endfunction
function lard( item )
  return CInt( GetObjProperty( item, "lard" ) );
endfunction
function rawchickenleg( item )
  return CInt( GetObjProperty( item, "rawchickenleg" ) );
endfunction
function rawlegoflamb( item )
  return CInt( GetObjProperty( item, "rawlegoflamb" ) );
endfunction
function honey( item )
  return CInt( GetObjProperty( item, "honey" ) );
endfunction
function coconut( item )
  return CInt( GetObjProperty( item, "coconut" ) );
endfunction
function pizzacrust( item )
  return CInt( GetObjProperty( item, "pizzacrust" ) );
endfunction
function piecrust( item )
  return CInt( GetObjProperty( item, "piecrust" ) );
endfunction
function fish2( item )
  return CInt( GetObjProperty( item, "fish2" ) );
endfunction
function fish3( item )
  return CInt( GetObjProperty( item, "fish3" ) );
endfunction
function fish4( item )
  return CInt( GetObjProperty( item, "fish4" ) );
endfunction
function wheelofcheese( item )
  return CInt( GetObjProperty( item, "wheelofcheese" ) );
endfunction
function friedchickenleg( item )
  return CInt( GetObjProperty( item, "friedchickenleg" ) );
endfunction
function cookedlegoflamb( item )
  return CInt( GetObjProperty( item, "cookedlegoflamb" ) );
endfunction
function sushi( item )
  return CInt( GetObjProperty( item, "sushi" ) );
endfunction
function CookedFishSteak( item )
  return CInt( GetObjProperty( item, "CookedFishSteak" ) );
endfunction
function smokedsalmon( item )
  return CInt( GetObjProperty( item, "smokedsalmon" ) );
endfunction
function cookedbird( item )
  return CInt( GetObjProperty( item, "cookedbird" ) );
endfunction
function CookedRib( item )
  return CInt( GetObjProperty( item, "CookedRib" ) );
endfunction
function magicfish1( item )
  return CInt( GetObjProperty( item, "magicfish1" ) );
endfunction
function magicfish2( item )
  return CInt( GetObjProperty( item, "magicfish2" ) );
endfunction
function magicfish3( item )
  return CInt( GetObjProperty( item, "magicfish3" ) );
endfunction
function magicfish4( item )
  return CInt( GetObjProperty( item, "magicfish4" ) );
endfunction
function magicfish5( item )
  return CInt( GetObjProperty( item, "magicfish5" ) );
endfunction
function magicfish6( item )
  return CInt( GetObjProperty( item, "magicfish6" ) );
endfunction
function magicfish7( item )
  return CInt( GetObjProperty( item, "magicfish7" ) );
endfunction
function magicfish8( item )
  return CInt( GetObjProperty( item, "magicfish8" ) );
endfunction
function pancakes( item )
  return CInt( GetObjProperty( item, "pancakes" ) );
endfunction
function mincemeatpie( item )
  return CInt( GetObjProperty( item, "mincemeatpie" ) );
endfunction
function chickenpotpie( item )
  return CInt( GetObjProperty( item, "chickenpotpie" ) );
endfunction
function lemonherbfish( item )
  return CInt( GetObjProperty( item, "lemonherbfish" ) );
endfunction
function onion( item )
  return CInt( GetObjProperty( item, "onion" ) );
endfunction
function Goldcoin( item )
  return CInt( GetObjProperty( item, "Goldcoin" ) );
endfunction
function zulucoin( item )
  return CInt( GetObjProperty( item, "zulucoin" ) );
endfunction
function ammoarrow( item )
  return CInt( GetObjProperty( item, "ammoarrow" ) );
endfunction
function ammobolt( item )
  return CInt( GetObjProperty( item, "ammobolt" ) );
endfunction
function ammofire( item )
  return CInt( GetObjProperty( item, "ammofire" ) );
endfunction
function ammoice( item )
  return CInt( GetObjProperty( item, "ammoice" ) );
endfunction
function ammothunder( item )
  return CInt( GetObjProperty( item, "ammothunder" ) );
endfunction
function ammothrow( item )
  return CInt( GetObjProperty( item, "ammothrow" ) );
endfunction
function ammogun( item )
  return CInt( GetObjProperty( item, "ammogun" ) );
endfunction
function ammoshaft( item )
  return CInt( GetObjProperty( item, "ammoshaft" ) );
endfunction
function ammofeather( item )
  return CInt( GetObjProperty( item, "ammofeather" ) );
endfunction
function LHEALPOTION( item )
  return CInt( GetObjProperty( item, "LHEALPOTION" ) );
endfunction
function HEALPOTION( item )
  return CInt( GetObjProperty( item, "HEALPOTION" ) );
endfunction
function GHEALPOTION( item )
  return CInt( GetObjProperty( item, "GHEALPOTION" ) );
endfunction
function LPOISONPOTION( item )
  return CInt( GetObjProperty( item, "LPOISONPOTION" ) );
endfunction
function POISONPOTION( item )
  return CInt( GetObjProperty( item, "POISONPOTION" ) );
endfunction
function GRPOISONPOTION( item )
  return CInt( GetObjProperty( item, "GRPOISONPOTION" ) );
endfunction
function GREXPLOSIONPOTION( item )
  return CInt( GetObjProperty( item, "GREXPLOSIONPOTION" ) );
endfunction
function LEXPLOSIONPOTION( item )
  return CInt( GetObjProperty( item, "LEXPLOSIONPOTION" ) );
endfunction
function EXPLOSIONPOTION( item )
  return CInt( GetObjProperty( item, "EXPLOSIONPOTION" ) );
endfunction
function LAGILITYPOTION( item )
  return CInt( GetObjProperty( item, "LAGILITYPOTION" ) );
endfunction
function AGILITYPOTION( item )
  return CInt( GetObjProperty( item, "AGILITYPOTION" ) );
endfunction
function GRAGILITYPOTION( item )
  return CInt( GetObjProperty( item, "GRAGILITYPOTION" ) );
endfunction
function REFRESHPOTION( item )
  return CInt( GetObjProperty( item, "REFRESHPOTION" ) );
endfunction
function FULLREFRESHPOTION( item )
  return CInt( GetObjProperty( item, "FULLREFRESHPOTION" ) );
endfunction
function LSTRENGTHPOTION( item )
  return CInt( GetObjProperty( item, "LSTRENGTHPOTION" ) );
endfunction
function STRENGTHPOTION( item )
  return CInt( GetObjProperty( item, "STRENGTHPOTION" ) );
endfunction
function GRSTRENGTHPOTION( item )
  return CInt( GetObjProperty( item, "GRSTRENGTHPOTION" ) );
endfunction
function LCUREPOTION( item )
  return CInt( GetObjProperty( item, "LCUREPOTION" ) );
endfunction
function CUREPOTION( item )
  return CInt( GetObjProperty( item, "CUREPOTION" ) );
endfunction
function GRCUREPOTION( item )
  return CInt( GetObjProperty( item, "GRCUREPOTION" ) );
endfunction
function DEDLYPOISONPOTION( item )
  return CInt( GetObjProperty( item, "DEDLYPOISONPOTION" ) );
endfunction
function LMINDPOTION( item )
  return CInt( GetObjProperty( item, "LMINDPOTION" ) );
endfunction
function MINDPOTION( item )
  return CInt( GetObjProperty( item, "MINDPOTION" ) );
endfunction
function GMINDPOTION( item )
  return CInt( GetObjProperty( item, "GMINDPOTION" ) );
endfunction
function InvisibilityPotion( item )
  return CInt( GetObjProperty( item, "InvisibilityPotion" ) );
endfunction
function FineIntellect( item )
  return CInt( GetObjProperty( item, "FineIntellect" ) );
endfunction
function FabulousIntellect( item )
  return CInt( GetObjProperty( item, "FabulousIntellect" ) );
endfunction
function FantasticIntellect( item )
  return CInt( GetObjProperty( item, "FantasticIntellect" ) );
endfunction
function lesserMegoInvul( item )
  return CInt( GetObjProperty( item, "lesserMegoInvul" ) );
endfunction
function MegoInvulnerabilitypotion( item )
  return CInt( GetObjProperty( item, "MegoInvulnerabilitypotion" ) );
endfunction
function greaterMegoInvulnerabilitypotion( item )
  return CInt( GetObjProperty( item, "greaterMegoInvulnerabilitypotion" ) );
endfunction
function GrandMageRefreshElixir( item )
  return CInt( GetObjProperty( item, "GrandMageRefreshElixir" ) );
endfunction
function HomericMightpotion( item )
  return CInt( GetObjProperty( item, "HomericMightpotion" ) );
endfunction
function GreaterHomericMightpotion( item )
  return CInt( GetObjProperty( item, "GreaterHomericMightpotion" ) );
endfunction
function TamlaHealpotion( item )
  return CInt( GetObjProperty( item, "TamlaHealpotion" ) );
endfunction
function MinorTransmutation( item )
  return CInt( GetObjProperty( item, "MinorTransmutation" ) );
endfunction
function MajorTransmutation( item )
  return CInt( GetObjProperty( item, "MajorTransmutation" ) );
endfunction
function Totem( item )
  return CInt( GetObjProperty( item, "Totem" ) );
endfunction
function Elixer( item )
  return CInt( GetObjProperty( item, "Elixer" ) );
endfunction
function GreatElixerium( item )
  return CInt( GetObjProperty( item, "GreatElixerium" ) );
endfunction
function MegoElixerium( item )
  return CInt( GetObjProperty( item, "MegoElixerium" ) );
endfunction
function DispelPotion( item )
  return CInt( GetObjProperty( item, "DispelPotion" ) );
endfunction
function Antidotescroll( item )
  return CInt( GetObjProperty( item, "Antidotescroll" ) );
endfunction
function Owlsightscroll( item )
  return CInt( GetObjProperty( item, "Owlsightscroll" ) );
endfunction
function Shiftingearthscroll( item )
  return CInt( GetObjProperty( item, "Shiftingearthscroll" ) );
endfunction
function Summonmammalsscroll( item )
  return CInt( GetObjProperty( item, "Summonmammalsscroll" ) );
endfunction
function Calllightningscroll( item )
  return CInt( GetObjProperty( item, "Calllightningscroll" ) );
endfunction
function Earthblessingscroll( item )
  return CInt( GetObjProperty( item, "Earthblessingscroll" ) );
endfunction
function Earthportalscroll( item )
  return CInt( GetObjProperty( item, "Earthportalscroll" ) );
endfunction
function Naturestouchscroll( item )
  return CInt( GetObjProperty( item, "Naturestouchscroll" ) );
endfunction
function Gustofairscroll( item )
  return CInt( GetObjProperty( item, "Gustofairscroll" ) );
endfunction
function Risingfirescroll( item )
  return CInt( GetObjProperty( item, "Risingfirescroll" ) );
endfunction
function Shapeshiftscroll( item )
  return CInt( GetObjProperty( item, "Shapeshiftscroll" ) );
endfunction
function Icestrikescroll( item )
  return CInt( GetObjProperty( item, "Icestrikescroll" ) );
endfunction
function Earthspiritscroll( item )
  return CInt( GetObjProperty( item, "Earthspiritscroll" ) );
endfunction
function Flamespiritscroll( item )
  return CInt( GetObjProperty( item, "Flamespiritscroll" ) );
endfunction
function Stormspiritscroll( item )
  return CInt( GetObjProperty( item, "Stormspiritscroll" ) );
endfunction
function Waterspiritscroll( item )
  return CInt( GetObjProperty( item, "Waterspiritscroll" ) );
endfunction
function ControlUndeadScroll( item )
  return CInt( GetObjProperty( item, "ControlUndeadScroll" ) );
endfunction
function DarknessScroll( item )
  return CInt( GetObjProperty( item, "DarknessScroll" ) );
endfunction
function DecayingRayScroll( item )
  return CInt( GetObjProperty( item, "DecayingRayScroll" ) );
endfunction
function SpectresTouchScroll( item )
  return CInt( GetObjProperty( item, "SpectresTouchScroll" ) );
endfunction
function AbyssalFlameScroll( item )
  return CInt( GetObjProperty( item, "AbyssalFlameScroll" ) );
endfunction
function AnimateDeadScroll( item )
  return CInt( GetObjProperty( item, "AnimateDeadScroll" ) );
endfunction
function SacrificeScroll( item )
  return CInt( GetObjProperty( item, "SacrificeScroll" ) );
endfunction
function WraithsBreathScroll( item )
  return CInt( GetObjProperty( item, "WraithsBreathScroll" ) );
endfunction
function SorcerersBaneScroll( item )
  return CInt( GetObjProperty( item, "SorcerersBaneScroll" ) );
endfunction
function SummonSpiritScroll( item )
  return CInt( GetObjProperty( item, "SummonSpiritScroll" ) );
endfunction
function WraithformScroll( item )
  return CInt( GetObjProperty( item, "WraithformScroll" ) );
endfunction
function WyvernStrikeScroll( item )
  return CInt( GetObjProperty( item, "WyvernStrikeScroll" ) );
endfunction
function KillScroll( item )
  return CInt( GetObjProperty( item, "KillScroll" ) );
endfunction
function LicheScroll( item )
  return CInt( GetObjProperty( item, "LicheScroll" ) );
endfunction
function PlagueScroll( item )
  return CInt( GetObjProperty( item, "PlagueScroll" ) );
endfunction
function SpellbindScroll( item )
  return CInt( GetObjProperty( item, "SpellbindScroll" ) );
endfunction
function songscroll1( item )
  return CInt( GetObjProperty( item, "songscroll1" ) );
endfunction
function songscroll2( item )
  return CInt( GetObjProperty( item, "songscroll2" ) );
endfunction
function songscroll3( item )
  return CInt( GetObjProperty( item, "songscroll3" ) );
endfunction
function songscroll4( item )
  return CInt( GetObjProperty( item, "songscroll4" ) );
endfunction
function songscroll5( item )
  return CInt( GetObjProperty( item, "songscroll5" ) );
endfunction
function songscroll6( item )
  return CInt( GetObjProperty( item, "songscroll6" ) );
endfunction
function songscroll7( item )
  return CInt( GetObjProperty( item, "songscroll7" ) );
endfunction
function songscroll8( item )
  return CInt( GetObjProperty( item, "songscroll8" ) );
endfunction
function songscroll9( item )
  return CInt( GetObjProperty( item, "songscroll9" ) );
endfunction
function songscroll10( item )
  return CInt( GetObjProperty( item, "songscroll10" ) );
endfunction
function songscroll11( item )
  return CInt( GetObjProperty( item, "songscroll11" ) );
endfunction
function songscroll12( item )
  return CInt( GetObjProperty( item, "songscroll12" ) );
endfunction
function songscroll13( item )
  return CInt( GetObjProperty( item, "songscroll13" ) );
endfunction
function songscroll14( item )
  return CInt( GetObjProperty( item, "songscroll14" ) );
endfunction
function songscroll15( item )
  return CInt( GetObjProperty( item, "songscroll15" ) );
endfunction
function songscroll16( item )
  return CInt( GetObjProperty( item, "songscroll16" ) );
endfunction
function songscroll17( item )
  return CInt( GetObjProperty( item, "songscroll17" ) );
endfunction
function songscroll18( item )
  return CInt( GetObjProperty( item, "songscroll18" ) );
endfunction
function songscroll19( item )
  return CInt( GetObjProperty( item, "songscroll19" ) );
endfunction
function songscroll20( item )
  return CInt( GetObjProperty( item, "songscroll20" ) );
endfunction
function holyscroll1( item )
  return CInt( GetObjProperty( item, "holyscroll1" ) );
endfunction
function holyscroll2( item )
  return CInt( GetObjProperty( item, "holyscroll2" ) );
endfunction
function holyscroll3( item )
  return CInt( GetObjProperty( item, "holyscroll3" ) );
endfunction
function holyscroll4( item )
  return CInt( GetObjProperty( item, "holyscroll4" ) );
endfunction
function holyscroll5( item )
  return CInt( GetObjProperty( item, "holyscroll5" ) );
endfunction
function holyscroll6( item )
  return CInt( GetObjProperty( item, "holyscroll6" ) );
endfunction
function holyscroll7( item )
  return CInt( GetObjProperty( item, "holyscroll7" ) );
endfunction
function holyscroll8( item )
  return CInt( GetObjProperty( item, "holyscroll8" ) );
endfunction
function holyscroll9( item )
  return CInt( GetObjProperty( item, "holyscroll9" ) );
endfunction
function blankscroll( item )
  return CInt( GetObjProperty( item, "blankscroll" ) );
endfunction
function blankmap( item )
  return CInt( GetObjProperty( item, "blankmap" ) );
endfunction
function lockpick( item )
  return CInt( GetObjProperty( item, "lockpick" ) );
endfunction
function emptybottle( item )
  return CInt( GetObjProperty( item, "emptybottle" ) );
endfunction
function recallrune( item )
  return CInt( GetObjProperty( item, "recallrune" ) );
endfunction
function kindling( item )
  return CInt( GetObjProperty( item, "kindling" ) );
endfunction
function bandages( item )
  return CInt( GetObjProperty( item, "bandages" ) );
endfunction
function SymbolOfAbsorption( item )
  return CInt( GetObjProperty( item, "SymbolOfAbsorption" ) );
endfunction
function SymbolOfToxinsResistance( item )
  return CInt( GetObjProperty( item, "SymbolOfToxinsResistance" ) );
endfunction
function SymbolOfHealth( item )
  return CInt( GetObjProperty( item, "SymbolOfHealth" ) );
endfunction
function SymbolOfHeavenTouch( item )
  return CInt( GetObjProperty( item, "SymbolOfHeavenTouch" ) );
endfunction
function SymbolOfHellFire( item )
  return CInt( GetObjProperty( item, "SymbolOfHellFire" ) );
endfunction
function SymbolOfVanishing( item )
  return CInt( GetObjProperty( item, "SymbolOfVanishing" ) );
endfunction
function SymbolOfVengeance( item )
  return CInt( GetObjProperty( item, "SymbolOfVengeance" ) );
endfunction
function SymbolOfRecalling( item )
  return CInt( GetObjProperty( item, "SymbolOfRecalling" ) );
endfunction
function SymbolOfThunderStorm( item )
  return CInt( GetObjProperty( item, "SymbolOfThunderStorm" ) );
endfunction
function SymbolOfRegeneration( item )
  return CInt( GetObjProperty( item, "SymbolOfRegeneration" ) );
endfunction
function SymbolOfLifeStream( item )
  return CInt( GetObjProperty( item, "SymbolOfLifeStream" ) );
endfunction
function AirEnchantedRune( item )
  return CInt( GetObjProperty( item, "AirEnchantedRune" ) );
endfunction
function EarthEnchantedRune2( item )
  return CInt( GetObjProperty( item, "EarthEnchantedRune2" ) );
endfunction
function FireEnchantedRune3( item )
  return CInt( GetObjProperty( item, "FireEnchantedRune3" ) );
endfunction
function NecroEnchantedRune4( item )
  return CInt( GetObjProperty( item, "NecroEnchantedRune4" ) );
endfunction
function WaterEnchantedRune5( item )
  return CInt( GetObjProperty( item, "WaterEnchantedRune5" ) );
endfunction
function HolyEnchantedRune6( item )
  return CInt( GetObjProperty( item, "HolyEnchantedRune6" ) );
endfunction
function PoisonEnchantedRune7( item )
  return CInt( GetObjProperty( item, "PoisonEnchantedRune7" ) );
endfunction
function DefenseEnchantedRune8( item )
  return CInt( GetObjProperty( item, "DefenseEnchantedRune8" ) );
endfunction
function ColdEnchantedRune9( item )
  return CInt( GetObjProperty( item, "ColdEnchantedRune9" ) );
endfunction
function LightEnchantedRune10( item )
  return CInt( GetObjProperty( item, "LightEnchantedRune10" ) );
endfunction
function DarkEnchantedRune11( item )
  return CInt( GetObjProperty( item, "DarkEnchantedRune11" ) );
endfunction
function HealingEnchantedRune12( item )
  return CInt( GetObjProperty( item, "HealingEnchantedRune12" ) );
endfunction
function speedEnchantedRune20( item )
  return CInt( GetObjProperty( item, "speedEnchantedRune20" ) );
endfunction
function mindEnchantedRune21( item )
  return CInt( GetObjProperty( item, "mindEnchantedRune21" ) );
endfunction
function staminaEnchantedRune22( item )
  return CInt( GetObjProperty( item, "staminaEnchantedRune22" ) );
endfunction
function anatomyEnchantedRune31( item )
  return CInt( GetObjProperty( item, "anatomyEnchantedRune31" ) );
endfunction
function fencingEnchantedRune72( item )
  return CInt( GetObjProperty( item, "fencingEnchantedRune72" ) );
endfunction
function healingEnchantedRune47( item )
  return CInt( GetObjProperty( item, "healingEnchantedRune47" ) );
endfunction
function maceEnchantedRune71( item )
  return CInt( GetObjProperty( item, "maceEnchantedRune71" ) );
endfunction
function parryingEnchantedRune35( item )
  return CInt( GetObjProperty( item, "parryingEnchantedRune35" ) );
endfunction
function swordEnchantedRune70( item )
  return CInt( GetObjProperty( item, "swordEnchantedRune70" ) );
endfunction
function tacticsEnchantedRune57( item )
  return CInt( GetObjProperty( item, "tacticsEnchantedRune57" ) );
endfunction
function wrestlingEnchantedRune73( item )
  return CInt( GetObjProperty( item, "wrestlingEnchantedRune73" ) );
endfunction
function loreEnchantedRune32( item )
  return CInt( GetObjProperty( item, "loreEnchantedRune32" ) );
endfunction
function tamingEnchantedRune65( item )
  return CInt( GetObjProperty( item, "tamingEnchantedRune65" ) );
endfunction
function archeryEnchantedRune61( item )
  return CInt( GetObjProperty( item, "archeryEnchantedRune61" ) );
endfunction
function cartEnchantedRune42( item )
  return CInt( GetObjProperty( item, "cartEnchantedRune42" ) );
endfunction
function fishingEnchantedRune48( item )
  return CInt( GetObjProperty( item, "fishingEnchantedRune48" ) );
endfunction
function trackEnchantedRune68( item )
  return CInt( GetObjProperty( item, "trackEnchantedRune68" ) );
endfunction
function veterEnchantedRune69( item )
  return CInt( GetObjProperty( item, "veterEnchantedRune69" ) );
endfunction
function cookingEnchantedRune43( item )
  return CInt( GetObjProperty( item, "cookingEnchantedRune43" ) );
endfunction
function alchemyEnchantedRune30( item )
  return CInt( GetObjProperty( item, "alchemyEnchantedRune30" ) );
endfunction
function evalEnchantedRune46( item )
  return CInt( GetObjProperty( item, "evalEnchantedRune46" ) );
endfunction
function scribeEnchantedRune53( item )
  return CInt( GetObjProperty( item, "scribeEnchantedRune53" ) );
endfunction
function itemidEnchantedRune33( item )
  return CInt( GetObjProperty( item, "itemidEnchantedRune33" ) );
endfunction
function mageryEnchantedRune55( item )
  return CInt( GetObjProperty( item, "mageryEnchantedRune55" ) );
endfunction
function meditEnchantedRune76( item )
  return CInt( GetObjProperty( item, "meditEnchantedRune76" ) );
endfunction
function resistEnchantedRune56( item )
  return CInt( GetObjProperty( item, "resistEnchantedRune56" ) );
endfunction
function spiritEnchantedRune62( item )
  return CInt( GetObjProperty( item, "spiritEnchantedRune62" ) );
endfunction
function beggingEnchantedRune36( item )
  return CInt( GetObjProperty( item, "beggingEnchantedRune36" ) );
endfunction
// function mageryEnchantedRune55( item )
// 	return CInt( GetObjProperty( item, "mageryEnchantedRune55" ));
// endfunction
function enticEnchantedRune45( item )
  return CInt( GetObjProperty( item, "enticEnchantedRune45" ) );
endfunction
function herdingEnchantedRune50( item )
  return CInt( GetObjProperty( item, "herdingEnchantedRune50" ) );
endfunction
function musicEnchantedRune59( item )
  return CInt( GetObjProperty( item, "musicEnchantedRune59" ) );
endfunction
function peaceEnchantedRune39( item )
  return CInt( GetObjProperty( item, "peaceEnchantedRune39" ) );
endfunction
function provocEnchantedRune52( item )
  return CInt( GetObjProperty( item, "provocEnchantedRune52" ) );
endfunction
// function archeryEnchantedRune61( item )
// 	return CInt( GetObjProperty( item, "archeryEnchantedRune61" ));
// endfunction
function detectEnchantedRune44( item )
  return CInt( GetObjProperty( item, "detectEnchantedRune44" ) );
endfunction
function hidingEnchantedRune51( item )
  return CInt( GetObjProperty( item, "hidingEnchantedRune51" ) );
endfunction
function lockpickEnchantedRune54( item )
  return CInt( GetObjProperty( item, "lockpickEnchantedRune54" ) );
endfunction
function poisonEnchantedRune60( item )
  return CInt( GetObjProperty( item, "poisonEnchantedRune60" ) );
endfunction
function snoopEnchantedRune58( item )
  return CInt( GetObjProperty( item, "snoopEnchantedRune58" ) );
endfunction
function stealingEnchantedRune63( item )
  return CInt( GetObjProperty( item, "stealingEnchantedRune63" ) );
endfunction
function stealthEnchantedRune77( item )
  return CInt( GetObjProperty( item, "stealthEnchantedRune77" ) );
endfunction
function armsloreEnchantedRune34( item )
  return CInt( GetObjProperty( item, "armsloreEnchantedRune34" ) );
endfunction
function bsEnchantedRune37( item )
  return CInt( GetObjProperty( item, "bsEnchantedRune37" ) );
endfunction
function bowcraftEnchantedRune38( item )
  return CInt( GetObjProperty( item, "bowcraftEnchantedRune38" ) );
endfunction
function carpEnchantedRune41( item )
  return CInt( GetObjProperty( item, "carpEnchantedRune41" ) );
endfunction
function lumberEnchantedRune74( item )
  return CInt( GetObjProperty( item, "lumberEnchantedRune74" ) );
endfunction
function miningEnchantedRune75( item )
  return CInt( GetObjProperty( item, "miningEnchantedRune75" ) );
endfunction
function tailoringEnchantedRune64( item )
  return CInt( GetObjProperty( item, "tailoringEnchantedRune64" ) );
endfunction
function tinkeringEnchantedRune67( item )
  return CInt( GetObjProperty( item, "tinkeringEnchantedRune67" ) );
endfunction
function campingEnchantedRune40( item )
  return CInt( GetObjProperty( item, "campingEnchantedRune40" ) );
endfunction
function forensicEnchantedRune49( item )
  return CInt( GetObjProperty( item, "forensicEnchantedRune49" ) );
endfunction
function removetrapEnchantedRune78( item )
  return CInt( GetObjProperty( item, "removetrapEnchantedRune78" ) );
endfunction
function tasteidEnchantedRune66( item )
  return CInt( GetObjProperty( item, "tasteidEnchantedRune66" ) );
endfunction
function castspeedupgrade( item )
  return CInt( GetObjProperty( item, "castspeedupgrade" ) );
endfunction
function hitupgrade( item )
  return CInt( GetObjProperty( item, "hitupgrade" ) );
endfunction
function damagebonus( item )
  return CInt( GetObjProperty( item, "damagebonus" ) );
endfunction
function armorupgrade( item )
  return CInt( GetObjProperty( item, "armorupgrade" ) );
endfunction

function store_collection_item( who, what, item )
  case ( what.objtype )
	0x0F91:
	  if ( GetObjProperty( item, "WormsHeart" ) )
		SetObjProperty( item, "WormsHeart", GetObjProperty( item, "WormsHeart" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "WormsHeart", CINT( what.amount ) );
	  endif
	0x0F90:
	  if ( GetObjProperty( item, "Deadwood" ) )
		SetObjProperty( item, "Deadwood", GetObjProperty( item, "Deadwood" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Deadwood", CINT( what.amount ) );
	  endif
	0x0F8F:
	  if ( GetObjProperty( item, "VolcanicAsh" ) )
		SetObjProperty( item, "VolcanicAsh", GetObjProperty( item, "VolcanicAsh" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "VolcanicAsh", CINT( what.amount ) );
	  endif
	0x0F8E:
	  if ( GetObjProperty( item, "SerpentsScales" ) )
		SetObjProperty( item, "SerpentsScales", GetObjProperty( item, "SerpentsScales" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SerpentsScales", CINT( what.amount ) );
	  endif
	0x0F8B:
	  if ( GetObjProperty( item, "Pumice" ) )
		SetObjProperty( item, "Pumice", GetObjProperty( item, "Pumice" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Pumice", CINT( what.amount ) );
	  endif
	0x0F8A:
	  if ( GetObjProperty( item, "PigIron" ) )
		SetObjProperty( item, "PigIron", GetObjProperty( item, "PigIron" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "PigIron", CINT( what.amount ) );
	  endif
	0x0F89:
	  if ( GetObjProperty( item, "Obsidian" ) )
		SetObjProperty( item, "Obsidian", GetObjProperty( item, "Obsidian" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Obsidian", CINT( what.amount ) );
	  endif
	0x0F87:
	  if ( GetObjProperty( item, "EyeOfNewt" ) )
		SetObjProperty( item, "EyeOfNewt", GetObjProperty( item, "EyeOfNewt" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "EyeOfNewt", CINT( what.amount ) );
	  endif
	0x0F83:
	  if ( GetObjProperty( item, "ExecutionersCap" ) )
		SetObjProperty( item, "ExecutionersCap", GetObjProperty( item, "ExecutionersCap" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "ExecutionersCap", CINT( what.amount ) );
	  endif
	0x0F82:
	  if ( GetObjProperty( item, "DragonsBlood" ) )
		SetObjProperty( item, "DragonsBlood", GetObjProperty( item, "DragonsBlood" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "DragonsBlood", CINT( what.amount ) );
	  endif
	0x0F81:
	  if ( GetObjProperty( item, "FertileDirt" ) )
		SetObjProperty( item, "FertileDirt", GetObjProperty( item, "FertileDirt" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "FertileDirt", CINT( what.amount ) );
	  endif
	0x0F80:
	  if ( GetObjProperty( item, "DaemonBone" ) )
		SetObjProperty( item, "DaemonBone", GetObjProperty( item, "DaemonBone" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "DaemonBone", CINT( what.amount ) );
	  endif
	0x0F7F:
	  if ( GetObjProperty( item, "Brimstone" ) )
		SetObjProperty( item, "Brimstone", GetObjProperty( item, "Brimstone" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Brimstone", CINT( what.amount ) );
	  endif
	0x0F7E:
	  if ( GetObjProperty( item, "Bone" ) )
		SetObjProperty( item, "Bone", GetObjProperty( item, "Bone" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Bone", CINT( what.amount ) );
	  endif
	0x0F7D:
	  if ( GetObjProperty( item, "VialOfBlood" ) )
		SetObjProperty( item, "VialOfBlood", GetObjProperty( item, "VialOfBlood" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "VialOfBlood", CINT( what.amount ) );
	  endif
	0x0F7C:
	  if ( GetObjProperty( item, "Bloodspawn" ) )
		SetObjProperty( item, "Bloodspawn", GetObjProperty( item, "Bloodspawn" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Bloodspawn", CINT( what.amount ) );
	  endif
	0x0F79:
	  if ( GetObjProperty( item, "Blackmoor" ) )
		SetObjProperty( item, "Blackmoor", GetObjProperty( item, "Blackmoor" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Blackmoor", CINT( what.amount ) );
	  endif
	0x0F78:
	  if ( GetObjProperty( item, "Batwing" ) )
		SetObjProperty( item, "Batwing", GetObjProperty( item, "Batwing" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Batwing", CINT( what.amount ) );
	  endif
	0x0F7B:
	  if ( GetObjProperty( item, "BloodMoss" ) )
		SetObjProperty( item, "BloodMoss", GetObjProperty( item, "BloodMoss" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "BloodMoss", CINT( what.amount ) );
	  endif
	0x0F7A:
	  if ( GetObjProperty( item, "BlackPearl" ) )
		SetObjProperty( item, "BlackPearl", GetObjProperty( item, "BlackPearl" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "BlackPearl", CINT( what.amount ) );
	  endif
	0x0F8D:
	  if ( GetObjProperty( item, "SpiderSilk" ) )
		SetObjProperty( item, "SpiderSilk", GetObjProperty( item, "SpiderSilk" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SpiderSilk", CINT( what.amount ) );
	  endif
	0x0F8C:
	  if ( GetObjProperty( item, "SulphurousAsh" ) )
		SetObjProperty( item, "SulphurousAsh", GetObjProperty( item, "SulphurousAsh" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SulphurousAsh", CINT( what.amount ) );
	  endif
	0x0F88:
	  if ( GetObjProperty( item, "Nightshade" ) )
		SetObjProperty( item, "Nightshade", GetObjProperty( item, "Nightshade" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Nightshade", CINT( what.amount ) );
	  endif
	0x0F84:
	  if ( GetObjProperty( item, "Garlic" ) )
		SetObjProperty( item, "Garlic", GetObjProperty( item, "Garlic" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Garlic", CINT( what.amount ) );
	  endif
	0x0f86:
	  if ( GetObjProperty( item, "MandrakeRoot" ) )
		SetObjProperty( item, "MandrakeRoot", GetObjProperty( item, "MandrakeRoot" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "MandrakeRoot", CINT( what.amount ) );
	  endif
	0x0f85:
	  if ( GetObjProperty( item, "Ginsengs" ) )
		SetObjProperty( item, "Ginsengs", GetObjProperty( item, "Ginsengs" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Ginsengs", CINT( what.amount ) );
	  endif
	0x0F0F:
	  if ( GetObjProperty( item, "Starsapphire" ) )
		SetObjProperty( item, "Starsapphire", GetObjProperty( item, "Starsapphire" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Starsapphire", CINT( what.amount ) );
	  endif
	0x0F10:
	  if ( GetObjProperty( item, "Emerald" ) )
		SetObjProperty( item, "Emerald", GetObjProperty( item, "Emerald" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Emerald", CINT( what.amount ) );
	  endif
	0x0F11:
	  if ( GetObjProperty( item, "Sapphire" ) )
		SetObjProperty( item, "Sapphire", GetObjProperty( item, "Sapphire" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Sapphire", CINT( what.amount ) );
	  endif
	0x0F13:
	  if ( GetObjProperty( item, "Ruby" ) )
		SetObjProperty( item, "Ruby", GetObjProperty( item, "Ruby" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Ruby", CINT( what.amount ) );
	  endif
	0x0F15:
	  if ( GetObjProperty( item, "Citrine" ) )
		SetObjProperty( item, "Citrine", GetObjProperty( item, "Citrine" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Citrine", CINT( what.amount ) );
	  endif
	0x0F16:
	  if ( GetObjProperty( item, "Amethyst" ) )
		SetObjProperty( item, "Amethyst", GetObjProperty( item, "Amethyst" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Amethyst", CINT( what.amount ) );
	  endif
	0x0F18:
	  if ( GetObjProperty( item, "Tourmaline" ) )
		SetObjProperty( item, "Tourmaline", GetObjProperty( item, "Tourmaline" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Tourmaline", CINT( what.amount ) );
	  endif
	0x0F25:
	  if ( GetObjProperty( item, "Amber" ) )
		SetObjProperty( item, "Amber", GetObjProperty( item, "Amber" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Amber", CINT( what.amount ) );
	  endif
	0x0F30:
	  if ( GetObjProperty( item, "Diamond" ) )
		SetObjProperty( item, "Diamond", GetObjProperty( item, "Diamond" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Diamond", CINT( what.amount ) );
	  endif
	0x6011:
	  if ( GetObjProperty( item, "IronIngot" ) )
		SetObjProperty( item, "IronIngot", GetObjProperty( item, "IronIngot" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "IronIngot", CINT( what.amount ) );
	  endif
	0x6012:
	  if ( GetObjProperty( item, "CopperIngot" ) )
		SetObjProperty( item, "CopperIngot", GetObjProperty( item, "CopperIngot" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "CopperIngot", CINT( what.amount ) );
	  endif
	0x6013:
	  if ( GetObjProperty( item, "BlackDwarfIngot" ) )
		SetObjProperty( item, "BlackDwarfIngot", GetObjProperty( item, "BlackDwarfIngot" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "BlackDwarfIngot", CINT( what.amount ) );
	  endif
	0x6014:
	  if ( GetObjProperty( item, "PaganIngot" ) )
		SetObjProperty( item, "PaganIngot", GetObjProperty( item, "PaganIngot" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "PaganIngot", CINT( what.amount ) );
	  endif
	0x6015:
	  if ( GetObjProperty( item, "SilverIngot" ) )
		SetObjProperty( item, "SilverIngot", GetObjProperty( item, "SilverIngot" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SilverIngot", CINT( what.amount ) );
	  endif
	0x6016:
	  if ( GetObjProperty( item, "SpectralIngot" ) )
		SetObjProperty( item, "SpectralIngot", GetObjProperty( item, "SpectralIngot" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SpectralIngot", CINT( what.amount ) );
	  endif
	0x6017:
	  if ( GetObjProperty( item, "LavaRockIngot" ) )
		SetObjProperty( item, "LavaRockIngot", GetObjProperty( item, "LavaRockIngot" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "LavaRockIngot", CINT( what.amount ) );
	  endif
	0x6018:
	  if ( GetObjProperty( item, "IceRockIngot" ) )
		SetObjProperty( item, "IceRockIngot", GetObjProperty( item, "IceRockIngot" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "IceRockIngot", CINT( what.amount ) );
	  endif
	0xc510:
	  if ( GetObjProperty( item, "MythrilIngot" ) )
		SetObjProperty( item, "MythrilIngot", GetObjProperty( item, "MythrilIngot" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "MythrilIngot", CINT( what.amount ) );
	  endif
	0xc511:
	  if ( GetObjProperty( item, "BasiliskIngot" ) )
		SetObjProperty( item, "BasiliskIngot", GetObjProperty( item, "BasiliskIngot" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "BasiliskIngot", CINT( what.amount ) );
	  endif
	0xc512:
	  if ( GetObjProperty( item, "SunIngot" ) )
		SetObjProperty( item, "SunIngot", GetObjProperty( item, "SunIngot" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SunIngot", CINT( what.amount ) );
	  endif
	0xc513:
	  if ( GetObjProperty( item, "DaedraIngot" ) )
		SetObjProperty( item, "DaedraIngot", GetObjProperty( item, "DaedraIngot" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "DaedraIngot", CINT( what.amount ) );
	  endif
	0xc514:
	  if ( GetObjProperty( item, "DoomIngot" ) )
		SetObjProperty( item, "DoomIngot", GetObjProperty( item, "DoomIngot" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "DoomIngot", CINT( what.amount ) );
	  endif
	0xc515:
	  if ( GetObjProperty( item, "NewZuluIngot" ) )
		SetObjProperty( item, "NewZuluIngot", GetObjProperty( item, "NewZuluIngot" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "NewZuluIngot", CINT( what.amount ) );
	  endif
	0xc516:
	  if ( GetObjProperty( item, "Paradise" ) )
		SetObjProperty( item, "Paradise", GetObjProperty( item, "Paradise" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Paradise", CINT( what.amount ) );
	  endif
	0xc517:
	  if ( GetObjProperty( item, "Hell" ) )
		SetObjProperty( item, "Hell", GetObjProperty( item, "Hell" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Hell", CINT( what.amount ) );
	  endif
	0xc518:
	  if ( GetObjProperty( item, "Void" ) )
		SetObjProperty( item, "Void", GetObjProperty( item, "Void" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Void", CINT( what.amount ) );
	  endif
	0xd04a:
	  if ( GetObjProperty( item, "Enchanted" ) )
		SetObjProperty( item, "Enchanted", GetObjProperty( item, "Enchanted" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Enchanted", CINT( what.amount ) );
	  endif
	0x0F95:
	  if ( GetObjProperty( item, "boltofcloth" ) )
		SetObjProperty( item, "boltofcloth", GetObjProperty( item, "boltofcloth" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "boltofcloth", CINT( what.amount ) );
	  endif
	0x1765:
	  if ( GetObjProperty( item, "cloth" ) )
		SetObjProperty( item, "cloth", GetObjProperty( item, "cloth" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "cloth", CINT( what.amount ) );
	  endif
	0x0df8:
	  if ( GetObjProperty( item, "wool" ) )
		SetObjProperty( item, "wool", GetObjProperty( item, "wool" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "wool", CINT( what.amount ) );
	  endif
	0xee20:
	  if ( GetObjProperty( item, "glass" ) )
		SetObjProperty( item, "glass", GetObjProperty( item, "glass" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "glass", CINT( what.amount ) );
	  endif
	0xee19:
	  if ( GetObjProperty( item, "clay" ) )
		SetObjProperty( item, "clay", GetObjProperty( item, "clay" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "clay", CINT( what.amount ) );
	  endif
	0x1be9:
	  if ( GetObjProperty( item, "goldingot" ) )
		SetObjProperty( item, "goldingot", GetObjProperty( item, "goldingot" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "goldingot", CINT( what.amount ) );
	  endif
	0x1078:
	  if ( GetObjProperty( item, "hides" ) )
		SetObjProperty( item, "hides", GetObjProperty( item, "hides" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "hides", CINT( what.amount ) );
	  endif
	0x7020:
	  if ( GetObjProperty( item, "lizardhide" ) )
		SetObjProperty( item, "lizardhide", GetObjProperty( item, "lizardhide" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "lizardhide", CINT( what.amount ) );
	  endif
	0x7021:
	  if ( GetObjProperty( item, "imphide" ) )
		SetObjProperty( item, "imphide", GetObjProperty( item, "imphide" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "imphide", CINT( what.amount ) );
	  endif
	0x7022:
	  if ( GetObjProperty( item, "trollhide" ) )
		SetObjProperty( item, "trollhide", GetObjProperty( item, "trollhide" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "trollhide", CINT( what.amount ) );
	  endif
	0x702d:
	  if ( GetObjProperty( item, "terathanhide" ) )
		SetObjProperty( item, "terathanhide", GetObjProperty( item, "terathanhide" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "terathanhide", CINT( what.amount ) );
	  endif
	0x7023:
	  if ( GetObjProperty( item, "necromancerhide" ) )
		SetObjProperty( item, "necromancerhide", GetObjProperty( item, "necromancerhide" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "necromancerhide", CINT( what.amount ) );
	  endif
	0x7025:
	  if ( GetObjProperty( item, "icehide" ) )
		SetObjProperty( item, "icehide", GetObjProperty( item, "icehide" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "icehide", CINT( what.amount ) );
	  endif
	0x7026:
	  if ( GetObjProperty( item, "lichehide" ) )
		SetObjProperty( item, "lichehide", GetObjProperty( item, "lichehide" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "lichehide", CINT( what.amount ) );
	  endif
	0x7028:
	  if ( GetObjProperty( item, "daemonhide" ) )
		SetObjProperty( item, "daemonhide", GetObjProperty( item, "daemonhide" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "daemonhide", CINT( what.amount ) );
	  endif
	0x702a:
	  if ( GetObjProperty( item, "balronhide" ) )
		SetObjProperty( item, "balronhide", GetObjProperty( item, "balronhide" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "balronhide", CINT( what.amount ) );
	  endif
	0x702e:
	  if ( GetObjProperty( item, "soulthreads" ) )
		SetObjProperty( item, "soulthreads", GetObjProperty( item, "soulthreads" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "soulthreads", CINT( what.amount ) );
	  endif
	0x7024:
	  if ( GetObjProperty( item, "drakehide" ) )
		SetObjProperty( item, "drakehide", GetObjProperty( item, "drakehide" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "drakehide", CINT( what.amount ) );
	  endif
	0x7027:
	  if ( GetObjProperty( item, "dragonhide" ) )
		SetObjProperty( item, "dragonhide", GetObjProperty( item, "dragonhide" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "dragonhide", CINT( what.amount ) );
	  endif
	0x702f:
	  if ( GetObjProperty( item, "wyvernhide" ) )
		SetObjProperty( item, "wyvernhide", GetObjProperty( item, "wyvernhide" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "wyvernhide", CINT( what.amount ) );
	  endif
	0x7029:
	  if ( GetObjProperty( item, "wyrmhide" ) )
		SetObjProperty( item, "wyrmhide", GetObjProperty( item, "wyrmhide" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "wyrmhide", CINT( what.amount ) );
	  endif
	0x702b:
	  if ( GetObjProperty( item, "celestialhide" ) )
		SetObjProperty( item, "celestialhide", GetObjProperty( item, "celestialhide" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "celestialhide", CINT( what.amount ) );
	  endif
	0x702c:
	  if ( GetObjProperty( item, "golddragonhide" ) )
		SetObjProperty( item, "golddragonhide", GetObjProperty( item, "golddragonhide" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "golddragonhide", CINT( what.amount ) );
	  endif
	0x1BDD:
	  if ( GetObjProperty( item, "logs" ) )
		SetObjProperty( item, "logs", GetObjProperty( item, "logs" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "logs", CINT( what.amount ) );
	  endif
	0x7300:
	  if ( GetObjProperty( item, "birchlog" ) )
		SetObjProperty( item, "birchlog", GetObjProperty( item, "birchlog" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "birchlog", CINT( what.amount ) );
	  endif
	0x7301:
	  if ( GetObjProperty( item, "cherrylog" ) )
		SetObjProperty( item, "cherrylog", GetObjProperty( item, "cherrylog" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "cherrylog", CINT( what.amount ) );
	  endif
	0x7302:
	  if ( GetObjProperty( item, "swamplog" ) )
		SetObjProperty( item, "swamplog", GetObjProperty( item, "swamplog" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "swamplog", CINT( what.amount ) );
	  endif
	0x7303:
	  if ( GetObjProperty( item, "oaklog" ) )
		SetObjProperty( item, "oaklog", GetObjProperty( item, "oaklog" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "oaklog", CINT( what.amount ) );
	  endif
	0x7304:
	  if ( GetObjProperty( item, "hardrangerlog" ) )
		SetObjProperty( item, "hardrangerlog", GetObjProperty( item, "hardrangerlog" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "hardrangerlog", CINT( what.amount ) );
	  endif
	0x7305:
	  if ( GetObjProperty( item, "jadelog" ) )
		SetObjProperty( item, "jadelog", GetObjProperty( item, "jadelog" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "jadelog", CINT( what.amount ) );
	  endif
	0x7306:
	  if ( GetObjProperty( item, "stormteallog" ) )
		SetObjProperty( item, "stormteallog", GetObjProperty( item, "stormteallog" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "stormteallog", CINT( what.amount ) );
	  endif
	0x7307:
	  if ( GetObjProperty( item, "blizzardlog" ) )
		SetObjProperty( item, "blizzardlog", GetObjProperty( item, "blizzardlog" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "blizzardlog", CINT( what.amount ) );
	  endif
	0x7308:
	  if ( GetObjProperty( item, "vulcaniclog" ) )
		SetObjProperty( item, "vulcaniclog", GetObjProperty( item, "vulcaniclog" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "vulcaniclog", CINT( what.amount ) );
	  endif
	0x7309:
	  if ( GetObjProperty( item, "vampiriclog" ) )
		SetObjProperty( item, "vampiriclog", GetObjProperty( item, "vampiriclog" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "vampiriclog", CINT( what.amount ) );
	  endif
	0x730a:
	  if ( GetObjProperty( item, "zululog" ) )
		SetObjProperty( item, "zululog", GetObjProperty( item, "zululog" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "zululog", CINT( what.amount ) );
	  endif
	0x730b:
	  if ( GetObjProperty( item, "darknesslog" ) )
		SetObjProperty( item, "darknesslog", GetObjProperty( item, "darknesslog" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "darknesslog", CINT( what.amount ) );
	  endif
	0x730c:
	  if ( GetObjProperty( item, "elvenlog" ) )
		SetObjProperty( item, "elvenlog", GetObjProperty( item, "elvenlog" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "elvenlog", CINT( what.amount ) );
	  endif
	// 0x09a7:
	// 	if (GetObjProperty(item, "emptypitcher"))
	// 		SetObjProperty(item,"emptypitcher",GetObjProperty(item,"emptypitcher") + CINT(what.amount));
	// 	else
	// 		SetObjProperty(item, "emptypitcher",CINT(what.amount));
	// 	endif
	// 0x1f81:
	// 	if (GetObjProperty(item, "emptyglass"))
	// 		SetObjProperty(item,"emptyglass",GetObjProperty(item,"emptyglass") + CINT(what.amount));
	// 	else
	// 		SetObjProperty(item, "emptyglass",CINT(what.amount));
	// 	endif
	0x099B:
	  if ( GetObjProperty( item, "bottleofliquor" ) )
		SetObjProperty( item, "bottleofliquor", GetObjProperty( item, "bottleofliquor" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "bottleofliquor", CINT( what.amount ) );
	  endif
	0x099F:
	  if ( GetObjProperty( item, "bottleofale" ) )
		SetObjProperty( item, "bottleofale", GetObjProperty( item, "bottleofale" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "bottleofale", CINT( what.amount ) );
	  endif
	0x09C7:
	  if ( GetObjProperty( item, "bottleofwine" ) )
		SetObjProperty( item, "bottleofwine", GetObjProperty( item, "bottleofwine" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "bottleofwine", CINT( what.amount ) );
	  endif
	0x1f96:
	  if ( GetObjProperty( item, "pitcherofale" ) )
		SetObjProperty( item, "pitcherofale", GetObjProperty( item, "pitcherofale" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "pitcherofale", CINT( what.amount ) );
	  endif
	0x1f98:
	  if ( GetObjProperty( item, "pitcherofcider" ) )
		SetObjProperty( item, "pitcherofcider", GetObjProperty( item, "pitcherofcider" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "pitcherofcider", CINT( what.amount ) );
	  endif
	0x1f9a:
	  if ( GetObjProperty( item, "pitcherofliquor" ) )
		SetObjProperty( item, "pitcherofliquor", GetObjProperty( item, "pitcherofliquor" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "pitcherofliquor", CINT( what.amount ) );
	  endif
	0x1f9c:
	  if ( GetObjProperty( item, "pitcherofwine" ) )
		SetObjProperty( item, "pitcherofwine", GetObjProperty( item, "pitcherofwine" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "pitcherofwine", CINT( what.amount ) );
	  endif
	0x1f9e:
	  if ( GetObjProperty( item, "pitcherofwater" ) )
		SetObjProperty( item, "pitcherofwater", GetObjProperty( item, "pitcherofwater" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "pitcherofwater", CINT( what.amount ) );
	  endif
	0x09ad:
	  if ( GetObjProperty( item, "pitcherofmilk" ) )
		SetObjProperty( item, "pitcherofmilk", GetObjProperty( item, "pitcherofmilk" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "pitcherofmilk", CINT( what.amount ) );
	  endif
	0x1F85:
	  if ( GetObjProperty( item, "glassofliquor" ) )
		SetObjProperty( item, "glassofliquor", GetObjProperty( item, "glassofliquor" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "glassofliquor", CINT( what.amount ) );
	  endif
	0x09EE:
	  if ( GetObjProperty( item, "mugofale" ) )
		SetObjProperty( item, "mugofale", GetObjProperty( item, "mugofale" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "mugofale", CINT( what.amount ) );
	  endif
	0x1F8D:
	  if ( GetObjProperty( item, "glassofwine" ) )
		SetObjProperty( item, "glassofwine", GetObjProperty( item, "glassofwine" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "glassofwine", CINT( what.amount ) );
	  endif
	0x1F7D:
	  if ( GetObjProperty( item, "glassofcider" ) )
		SetObjProperty( item, "glassofcider", GetObjProperty( item, "glassofcider" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "glassofcider", CINT( what.amount ) );
	  endif
	0x1F89:
	  if ( GetObjProperty( item, "glassofmilk" ) )
		SetObjProperty( item, "glassofmilk", GetObjProperty( item, "glassofmilk" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "glassofmilk", CINT( what.amount ) );
	  endif
	0x1F91:
	  if ( GetObjProperty( item, "glassofwater" ) )
		SetObjProperty( item, "glassofwater", GetObjProperty( item, "glassofwater" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "glassofwater", CINT( what.amount ) );
	  endif
	0x1045:
	  if ( GetObjProperty( item, "flour" ) )
		SetObjProperty( item, "flour", GetObjProperty( item, "flour" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "flour", CINT( what.amount ) );
	  endif
	0x0c6d:
	  if ( GetObjProperty( item, "onion" ) )
		SetObjProperty( item, "onion", GetObjProperty( item, "onion" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "onion", CINT( what.amount ) );
	  endif
	0x09f1:
	  if ( GetObjProperty( item, "rawrib" ) )
		SetObjProperty( item, "rawrib", GetObjProperty( item, "rawrib" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "rawrib", CINT( what.amount ) );
	  endif
	0x097a:
	  if ( GetObjProperty( item, "rawfishsteak" ) )
		SetObjProperty( item, "rawfishsteak", GetObjProperty( item, "rawfishsteak" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "rawfishsteak", CINT( what.amount ) );
	  endif
	0x09b9:
	  if ( GetObjProperty( item, "rawbird" ) )
		SetObjProperty( item, "rawbird", GetObjProperty( item, "rawbird" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "rawbird", CINT( what.amount ) );
	  endif
	0x09c9:
	  if ( GetObjProperty( item, "rawham" ) )
		SetObjProperty( item, "rawham", GetObjProperty( item, "rawham" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "rawham", CINT( what.amount ) );
	  endif
	0x0976:
	  if ( GetObjProperty( item, "slabofbacon" ) )
		SetObjProperty( item, "slabofbacon", GetObjProperty( item, "slabofbacon" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "slabofbacon", CINT( what.amount ) );
	  endif
	0x1e8a:
	  if ( GetObjProperty( item, "lard" ) )
		SetObjProperty( item, "lard", GetObjProperty( item, "lard" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "lard", CINT( what.amount ) );
	  endif
	0x1607:
	  if ( GetObjProperty( item, "rawchickenleg" ) )
		SetObjProperty( item, "rawchickenleg", GetObjProperty( item, "rawchickenleg" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "rawchickenleg", CINT( what.amount ) );
	  endif
	0x1609:
	  if ( GetObjProperty( item, "rawlegoflamb" ) )
		SetObjProperty( item, "rawlegoflamb", GetObjProperty( item, "rawlegoflamb" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "rawlegoflamb", CINT( what.amount ) );
	  endif
	0x09ec:
	  if ( GetObjProperty( item, "honey" ) )
		SetObjProperty( item, "honey", GetObjProperty( item, "honey" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "honey", CINT( what.amount ) );
	  endif
	0x1726:
	  if ( GetObjProperty( item, "coconut" ) )
		SetObjProperty( item, "coconut", GetObjProperty( item, "coconut" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "coconut", CINT( what.amount ) );
	  endif
	0xc803:
	  if ( GetObjProperty( item, "pizzacrust" ) )
		SetObjProperty( item, "pizzacrust", GetObjProperty( item, "pizzacrust" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "pizzacrust", CINT( what.amount ) );
	  endif
	0xc804:
	  if ( GetObjProperty( item, "piecrust" ) )
		SetObjProperty( item, "piecrust", GetObjProperty( item, "piecrust" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "piecrust", CINT( what.amount ) );
	  endif
	0x09cd:
	  if ( GetObjProperty( item, "fish2" ) )
		SetObjProperty( item, "fish2", GetObjProperty( item, "fish2" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "fish2", CINT( what.amount ) );
	  endif
	0x09ce:
	  if ( GetObjProperty( item, "fish3" ) )
		SetObjProperty( item, "fish3", GetObjProperty( item, "fish3" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "fish3", CINT( what.amount ) );
	  endif
	0x09cf:
	  if ( GetObjProperty( item, "fish4" ) )
		SetObjProperty( item, "fish4", GetObjProperty( item, "fish4" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "fish4", CINT( what.amount ) );
	  endif
	0x097E:
	  if ( GetObjProperty( item, "wheelofcheese" ) )
		SetObjProperty( item, "wheelofcheese", GetObjProperty( item, "wheelofcheese" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "wheelofcheese", CINT( what.amount ) );
	  endif
	0x1608:
	  if ( GetObjProperty( item, "friedchickenleg" ) )
		SetObjProperty( item, "friedchickenleg", GetObjProperty( item, "friedchickenleg" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "friedchickenleg", CINT( what.amount ) );
	  endif
	0x160a:
	  if ( GetObjProperty( item, "cookedlegoflamb" ) )
		SetObjProperty( item, "cookedlegoflamb", GetObjProperty( item, "cookedlegoflamb" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "cookedlegoflamb", CINT( what.amount ) );
	  endif
	0xc923:
	  if ( GetObjProperty( item, "sushi" ) )
		SetObjProperty( item, "sushi", GetObjProperty( item, "sushi" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "sushi", CINT( what.amount ) );
	  endif
	0x097b:
	  if ( GetObjProperty( item, "CookedFishSteak" ) )
		SetObjProperty( item, "CookedFishSteak", GetObjProperty( item, "CookedFishSteak" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "CookedFishSteak", CINT( what.amount ) );
	  endif
	0x1e1e:
	  if ( GetObjProperty( item, "smokedsalmon" ) )
		SetObjProperty( item, "smokedsalmon", GetObjProperty( item, "smokedsalmon" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "smokedsalmon", CINT( what.amount ) );
	  endif
	0x09b7:
	  if ( GetObjProperty( item, "cookedbird" ) )
		SetObjProperty( item, "cookedbird", GetObjProperty( item, "cookedbird" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "cookedbird", CINT( what.amount ) );
	  endif
	0x09f2:
	  if ( GetObjProperty( item, "CookedRib" ) )
		SetObjProperty( item, "CookedRib", GetObjProperty( item, "CookedRib" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "CookedRib", CINT( what.amount ) );
	  endif
	0xA368:
	  if ( GetObjProperty( item, "magicfish1" ) )
		SetObjProperty( item, "magicfish1", GetObjProperty( item, "magicfish1" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "magicfish1", CINT( what.amount ) );
	  endif
	0xA369:
	  if ( GetObjProperty( item, "magicfish2" ) )
		SetObjProperty( item, "magicfish2", GetObjProperty( item, "magicfish2" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "magicfish2", CINT( what.amount ) );
	  endif
	0xA36A:
	  if ( GetObjProperty( item, "magicfish3" ) )
		SetObjProperty( item, "magicfish3", GetObjProperty( item, "magicfish3" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "magicfish3", CINT( what.amount ) );
	  endif
	0xA36B:
	  if ( GetObjProperty( item, "magicfish4" ) )
		SetObjProperty( item, "magicfish4", GetObjProperty( item, "magicfish4" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "magicfish4", CINT( what.amount ) );
	  endif
	0xA36C:
	  if ( GetObjProperty( item, "magicfish5" ) )
		SetObjProperty( item, "magicfish5", GetObjProperty( item, "magicfish5" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "magicfish5", CINT( what.amount ) );
	  endif
	0xA36D:
	  if ( GetObjProperty( item, "magicfish6" ) )
		SetObjProperty( item, "magicfish6", GetObjProperty( item, "magicfish6" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "magicfish6", CINT( what.amount ) );
	  endif
	0xA36E:
	  if ( GetObjProperty( item, "magicfish7" ) )
		SetObjProperty( item, "magicfish7", GetObjProperty( item, "magicfish7" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "magicfish7", CINT( what.amount ) );
	  endif
	0xA36F:
	  if ( GetObjProperty( item, "magicfish8" ) )
		SetObjProperty( item, "magicfish8", GetObjProperty( item, "magicfish8" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "magicfish8", CINT( what.amount ) );
	  endif
	0xc912:
	  if ( GetObjProperty( item, "pancakes" ) )
		SetObjProperty( item, "pancakes", GetObjProperty( item, "pancakes" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "pancakes", CINT( what.amount ) );
	  endif
	0xc942:
	  if ( GetObjProperty( item, "mincemeatpie" ) )
		SetObjProperty( item, "mincemeatpie", GetObjProperty( item, "mincemeatpie" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "mincemeatpie", CINT( what.amount ) );
	  endif
	0xc943:
	  if ( GetObjProperty( item, "chickenpotpie" ) )
		SetObjProperty( item, "chickenpotpie", GetObjProperty( item, "chickenpotpie" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "chickenpotpie", CINT( what.amount ) );
	  endif
	0x27bc:
	  if ( GetObjProperty( item, "lemonherbfish" ) )
		SetObjProperty( item, "lemonherbfish", GetObjProperty( item, "lemonherbfish" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "lemonherbfish", CINT( what.amount ) );
	  endif
	0x0eed:
	  if ( GetObjProperty( item, "Goldcoin" ) )
		SetObjProperty( item, "Goldcoin", GetObjProperty( item, "Goldcoin" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Goldcoin", CINT( what.amount ) );
	  endif
	0x3b9a:
	  if ( GetObjProperty( item, "zulucoin" ) )
		SetObjProperty( item, "zulucoin", GetObjProperty( item, "zulucoin" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "zulucoin", CINT( what.amount ) );
	  endif
	0xdf0c:
	  if ( GetObjProperty( item, "Goldcoin" ) )
		SetObjProperty( item, "Goldcoin", GetObjProperty( item, "Goldcoin" )
				  + CINT( GetObjProperty( what, "gold_amount" ) ) );
	  else
		SetObjProperty( item, "Goldcoin", CINT( GetObjProperty( what, "gold_amount" ) ) );
	  endif
	0xdc01:
	  if ( GetObjProperty( item, "LHEALPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageLHeal" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageLHeal", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "LHEALPOTION", GetObjProperty( item, "LHEALPOTION" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "LHEALPOTION", CINT( what.amount ) );
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageLHeal", GetObjProperty( what, "ByTrueMage" ) );
		endif
	  endif
	0xdc02:
	  if ( GetObjProperty( item, "HEALPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageLHeal" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageLHeal", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "HEALPOTION", GetObjProperty( item, "HEALPOTION" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "HEALPOTION", CINT( what.amount ) );
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageHeal", GetObjProperty( what, "ByTrueMage" ) );
		endif
	  endif

	0xdc03:
	  if ( GetObjProperty( item, "GHEALPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageGHeal" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageGHeal", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "GHEALPOTION", GetObjProperty( item, "GHEALPOTION" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "GHEALPOTION", CINT( what.amount ) );
		if ( GetObjProperty( what, "ByTrueMage" ) )

		  SetObjProperty( item, "ByTrueMageGHeal", GetObjProperty( what, "ByTrueMage" ) );
		endif
	  endif
	0xdc04:
	  if ( GetObjProperty( item, "LPOISONPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageLPoison" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageLPoison", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "LPOISONPOTION", GetObjProperty( item, "LPOISONPOTION" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "LPOISONPOTION", CINT( what.amount ) );
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageGHeal", GetObjProperty( what, "ByTrueMage" ) );
		endif
	  endif
	0xdc05:
	  if ( GetObjProperty( item, "POISONPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMagePoison" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMagePoison", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "POISONPOTION", GetObjProperty( item, "POISONPOTION" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "POISONPOTION", CINT( what.amount ) );
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMagePoison", GetObjProperty( what, "ByTrueMage" ) );
		endif
	  endif
	0xdc06:
	  if ( GetObjProperty( item, "GRPOISONPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageGPoison" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageGPoison", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "GRPOISONPOTION", GetObjProperty( item, "GRPOISONPOTION" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "GRPOISONPOTION", CINT( what.amount ) );
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageGPoison", GetObjProperty( what, "ByTrueMage" ) );
		endif
	  endif
	0xdc07:
	  if ( GetObjProperty( item, "GREXPLOSIONPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageGExpl" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageGExpl", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "GREXPLOSIONPOTION", GetObjProperty( item, "GREXPLOSIONPOTION" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "GREXPLOSIONPOTION", CINT( what.amount ) );
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageGExpl", GetObjProperty( what, "ByTrueMage" ) );
		endif
	  endif
	0xdc08:
	  if ( GetObjProperty( item, "LEXPLOSIONPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageLExpl" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageLExpl", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "LEXPLOSIONPOTION", GetObjProperty( item, "LEXPLOSIONPOTION" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "LEXPLOSIONPOTION", CINT( what.amount ) );
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageLExpl", GetObjProperty( what, "ByTrueMage" ) );
		endif
	  endif
	0xdc09:
	  if ( GetObjProperty( item, "EXPLOSIONPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageExpl" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageExpl", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "EXPLOSIONPOTION", GetObjProperty( item, "EXPLOSIONPOTION" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "EXPLOSIONPOTION", CINT( what.amount ) );
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageExpl", GetObjProperty( what, "ByTrueMage" ) );
		endif
	  endif

	0xdc0b:
	  if ( GetObjProperty( item, "LAGILITYPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageLagil" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageLagil", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "LAGILITYPOTION", GetObjProperty( item, "LAGILITYPOTION" )
				  + CINT( what.amount ) );
	  else
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageLagil", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "LAGILITYPOTION", CINT( what.amount ) );
	  endif
	0xdc0c:
	  if ( GetObjProperty( item, "AGILITYPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageAgil" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageAgil", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "AGILITYPOTION", GetObjProperty( item, "AGILITYPOTION" ) + CINT( what.amount ) );
	  else
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageAgil", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "AGILITYPOTION", CINT( what.amount ) );
	  endif
	0xdc0d:
	  if ( GetObjProperty( item, "GRAGILITYPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageGagil" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageGagil", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "GRAGILITYPOTION", GetObjProperty( item, "GRAGILITYPOTION" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "GRAGILITYPOTION", CINT( what.amount ) );
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageGagil", GetObjProperty( what, "ByTrueMage" ) );
		endif
	  endif
	0xdc0e:
	  if ( GetObjProperty( item, "REFRESHPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageRefresh" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageRefresh", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "REFRESHPOTION", GetObjProperty( item, "REFRESHPOTION" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "REFRESHPOTION", CINT( what.amount ) );
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageRefresh", GetObjProperty( what, "ByTrueMage" ) );
		endif
	  endif
	0xdc0f:
	  if ( GetObjProperty( item, "FULLREFRESHPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageFRefresh" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageFRefresh", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "FULLREFRESHPOTION", GetObjProperty( item, "FULLREFRESHPOTION" )
				  + CINT( what.amount ) );
	  else
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageFRefresh", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "FULLREFRESHPOTION", CINT( what.amount ) );
	  endif
	0xdc10:
	  if ( GetObjProperty( item, "LSTRENGTHPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageLstrpot" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageLstrpot", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "LSTRENGTHPOTION", GetObjProperty( item, "LSTRENGTHPOTION" )
				  + CINT( what.amount ) );
	  else
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageLstrpot", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "LSTRENGTHPOTION", CINT( what.amount ) );
	  endif
	0xdc11:
	  if ( GetObjProperty( item, "STRENGTHPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageStrpot" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageStrpot", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "STRENGTHPOTION", GetObjProperty( item, "STRENGTHPOTION" )
				  + CINT( what.amount ) );
	  else
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageStrpot", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "STRENGTHPOTION", CINT( what.amount ) );
	  endif
	0xdc12:
	  if ( GetObjProperty( item, "GRSTRENGTHPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageGStrpot" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageGStrpot", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "GRSTRENGTHPOTION", GetObjProperty( item, "GRSTRENGTHPOTION" )
				  + CINT( what.amount ) );
	  else
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageGStrpot", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "GRSTRENGTHPOTION", CINT( what.amount ) );
	  endif
	0xdc14:
	  if ( GetObjProperty( item, "LCUREPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageLcurepot" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageLcurepot", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "LCUREPOTION", GetObjProperty( item, "LCUREPOTION" ) + CINT( what.amount ) );
	  else
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageLcurepot", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "LCUREPOTION", CINT( what.amount ) );
	  endif

	0xdc15:
	  if ( GetObjProperty( item, "CUREPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageCurepot" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageCurepot", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "CUREPOTION", GetObjProperty( item, "CUREPOTION" ) + CINT( what.amount ) );
	  else
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageCurepot", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "CUREPOTION", CINT( what.amount ) );
	  endif
	0xdc16:
	  if ( GetObjProperty( item, "GRCUREPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageGCurepot" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageGCurepot", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "GRCUREPOTION", GetObjProperty( item, "GRCUREPOTION" ) + CINT( what.amount ) );
	  else
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageGCurepot", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "GRCUREPOTION", CINT( what.amount ) );
	  endif

	0xdc17:
	  if ( GetObjProperty( item, "DEDLYPOISONPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageDpoisonpot" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageDpoisonpot", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "DEDLYPOISONPOTION", GetObjProperty( item, "DEDLYPOISONPOTION" )
				  + CINT( what.amount ) );
	  else
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageDpoisonpot", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "DEDLYPOISONPOTION", CINT( what.amount ) );
	  endif
	0xdce6:
	  if ( GetObjProperty( item, "LMINDPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageLMindpotion" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageLMindpotion", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "LMINDPOTION", GetObjProperty( item, "LMINDPOTION" ) + CINT( what.amount ) );
	  else
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageLMindpotion", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "LMINDPOTION", CINT( what.amount ) );
	  endif

	0xdce7:
	  if ( GetObjProperty( item, "MINDPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageMindpotion" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageMindpotion", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "MINDPOTION", GetObjProperty( item, "MINDPOTION" ) + CINT( what.amount ) );
	  else
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageMindpotion", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "MINDPOTION", CINT( what.amount ) );
	  endif
	0xdce8:
	  if ( GetObjProperty( item, "GMINDPOTION" ) )
		if ( GetObjProperty( item, "ByTrueMageGMindpotion" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
		  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
		  return;
		endif
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageGMindpotion", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "GMINDPOTION", GetObjProperty( item, "GMINDPOTION" ) + CINT( what.amount ) );
	  else
		if ( GetObjProperty( what, "ByTrueMage" ) )
		  SetObjProperty( item, "ByTrueMageGMindpotion", GetObjProperty( what, "ByTrueMage" ) );
		endif
		SetObjProperty( item, "GMINDPOTION", CINT( what.amount ) );
	  endif
	0x7059:
	  case ( GetObjProperty( what, "itemtype" ) )
		23:
		  if ( GetObjProperty( item, "InvisibilityPotion" ) )
			if ( GetObjProperty( item, "ByTrueMageInvispot" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMageInvispot", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "InvisibilityPotion", GetObjProperty( item, "InvisibilityPotion" )
				   + CINT( what.amount ) );
		  else
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMageInvispot", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "InvisibilityPotion", CINT( what.amount ) );
		  endif
		24:
		  if ( GetObjProperty( item, "FineIntellect" ) )
			if ( GetObjProperty( item, "ByTrueMagefineint" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagefineint", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "FineIntellect", GetObjProperty( item, "FineIntellect" )
				   + CINT( what.amount ) );
		  else
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagefineint", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "FineIntellect", CINT( what.amount ) );
		  endif
		25:
		  if ( GetObjProperty( item, "FabulousIntellect" ) )
			if ( GetObjProperty( item, "ByTrueMagefabint" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagefabint", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "FabulousIntellect", GetObjProperty( item, "FabulousIntellect" )
				   + CINT( what.amount ) );
		  else
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagefabint", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "FabulousIntellect", CINT( what.amount ) );
		  endif

		26:
		  if ( GetObjProperty( item, "FantasticIntellect" ) )
			if ( GetObjProperty( item, "ByTrueMagefanint" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagefanint", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "FantasticIntellect", GetObjProperty( item, "FantasticIntellect" )
				   + CINT( what.amount ) );
		  else
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagefanint", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "FantasticIntellect", CINT( what.amount ) );
		  endif
		27:
		  if ( GetObjProperty( item, "lesserMegoInvul" ) )
			if ( GetObjProperty( item, "ByTrueMagelinv" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagelinv", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "lesserMegoInvul", GetObjProperty( item, "lesserMegoInvul" )
				   + CINT( what.amount ) );
		  else
			SetObjProperty( item, "ByTrueMagelinv", GetObjProperty( what, "ByTrueMage" ) );
			SetObjProperty( item, "lesserMegoInvul", CINT( what.amount ) );
		  endif
		28:
		  if ( GetObjProperty( item, "MegoInvulnerabilitypotion" ) )
			if ( GetObjProperty( item, "ByTrueMageMinv" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMageMinv", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "MegoInvulnerabilitypotion",
				   GetObjProperty( item, "MegoInvulnerabilitypotion" ) + CINT( what.amount ) );
		  else
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMageMinv", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "MegoInvulnerabilitypotion", CINT( what.amount ) );
		  endif
		29:
		  if ( GetObjProperty( item, "greaterMegoInvulnerabilitypotion" ) )
			if ( GetObjProperty( item, "ByTrueMageGMinv" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMageGMinv", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "greaterMegoInvulnerabilitypotion",
				   GetObjProperty( item, "greaterMegoInvulnerabilitypotion" ) + CINT( what.amount ) );
		  else
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMageGMinv", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "greaterMegoInvulnerabilitypotion", CINT( what.amount ) );
		  endif
		30:
		  if ( GetObjProperty( item, "GrandMageRefreshElixir" ) )
			if ( GetObjProperty( item, "ByTrueMagegmrefresh" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagegmrefresh", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "GrandMageRefreshElixir", GetObjProperty( item, "GrandMageRefreshElixir" )
				   + CINT( what.amount ) );
		  else
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagegmrefresh", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "GrandMageRefreshElixir", CINT( what.amount ) );
		  endif

		31:
		  if ( GetObjProperty( item, "HomericMightpotion" ) )
			if ( GetObjProperty( item, "ByTrueMageHompot" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMageHompot", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "HomericMightpotion", GetObjProperty( item, "HomericMightpotion" )
				   + CINT( what.amount ) );
		  else
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMageHompot", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "HomericMightpotion", CINT( what.amount ) );
		  endif

		32:
		  if ( GetObjProperty( item, "GreaterHomericMightpotion" ) )
			if ( GetObjProperty( item, "ByTrueMageGHompot" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMageGHompot", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "GreaterHomericMightpotion",
				   GetObjProperty( item, "GreaterHomericMightpotion" ) + CINT( what.amount ) );
		  else
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMageGHompot", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "GreaterHomericMightpotion", CINT( what.amount ) );
		  endif

		33:
		  if ( GetObjProperty( item, "TamlaHealpotion" ) )
			if ( GetObjProperty( item, "ByTrueMagetalmpot" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagetalmpot", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "TamlaHealpotion", GetObjProperty( item, "TamlaHealpotion" )
				   + CINT( what.amount ) );

		  else
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagetalmpot", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "TamlaHealpotion", CINT( what.amount ) );
		  endif
		34:
		  if ( GetObjProperty( item, "MinorTransmutation" ) )
			if ( GetObjProperty( item, "ByTrueMagemintrans" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagemintrans", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "MinorTransmutation", GetObjProperty( item, "MinorTransmutation" )
				   + CINT( what.amount ) );
		  else
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagemintrans", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "MinorTransmutation", CINT( what.amount ) );
		  endif

		35:
		  if ( GetObjProperty( item, "MajorTransmutation" ) )
			if ( GetObjProperty( item, "ByTrueMagemajtrans" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagemajtrans", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "MajorTransmutation", GetObjProperty( item, "MajorTransmutation" )
				   + CINT( what.amount ) );
		  else
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagemajtrans", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "MajorTransmutation", CINT( what.amount ) );
		  endif
		36:
		  if ( GetObjProperty( item, "Totem" ) )
			if ( GetObjProperty( item, "ByTrueMageTotem" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMageTotem", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "Totem", GetObjProperty( item, "Totem" ) + CINT( what.amount ) );
		  else
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMageTotem", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "Totem", CINT( what.amount ) );
		  endif
		37:
		  if ( GetObjProperty( item, "Elixer" ) )
			if ( GetObjProperty( item, "ByTrueMageElixer" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMageElixer", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "Elixer", GetObjProperty( item, "Elixer" ) + CINT( what.amount ) );
		  else
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMageElixer", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "Elixer", CINT( what.amount ) );
		  endif

		39:
		  if ( GetObjProperty( item, "GreatElixerium" ) )
			if ( GetObjProperty( item, "ByTrueMagegElixer" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagegElixer", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "GreatElixerium", GetObjProperty( item, "GreatElixerium" )
				   + CINT( what.amount ) );
		  else
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagegElixer", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "GreatElixerium", CINT( what.amount ) );
		  endif

		40:
		  if ( GetObjProperty( item, "MegoElixerium" ) )
			if ( GetObjProperty( item, "ByTrueMageMElixer" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMageMElixer", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "MegoElixerium", GetObjProperty( item, "MegoElixerium" )
				   + CINT( what.amount ) );
		  else
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMageMElixer", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "MegoElixerium", CINT( what.amount ) );
		  endif
		43:
		  if ( GetObjProperty( item, "DispelPotion" ) )
			if ( GetObjProperty( item, "ByTrueMagedispot" ) != ( GetObjProperty( what, "ByTrueMage" ) ) )
			  SendSysMessage( who, "To place this potion, get rid of the existing in the cabinet" );
			  return;
			endif
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagedispot", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "DispelPotion", GetObjProperty( item, "DispelPotion" ) + CINT( what.amount ) );
		  else
			if ( GetObjProperty( what, "ByTrueMage" ) )
			  SetObjProperty( item, "ByTrueMagedispot", GetObjProperty( what, "ByTrueMage" ) );
			endif
			SetObjProperty( item, "DispelPotion", CINT( what.amount ) );
		  endif

		default:
		  SendSysMessage( who, "There is no place for this item." );
		  return;
	  endcase
	0x0f3f:
	  if ( GetObjProperty( item, "ammoarrow" ) )
		SetObjProperty( item, "ammoarrow", GetObjProperty( item, "ammoarrow" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "ammoarrow", CINT( what.amount ) );
	  endif
	0x1bfb:
	  if ( GetObjProperty( item, "ammobolt" ) )
		SetObjProperty( item, "ammobolt", GetObjProperty( item, "ammobolt" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "ammobolt", CINT( what.amount ) );
	  endif
	0x6051:
	  if ( GetObjProperty( item, "ammofire" ) )
		SetObjProperty( item, "ammofire", GetObjProperty( item, "ammofire" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "ammofire", CINT( what.amount ) );
	  endif
	0xb200:
	  if ( GetObjProperty( item, "ammoice" ) )
		SetObjProperty( item, "ammoice", GetObjProperty( item, "ammoice" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "ammoice", CINT( what.amount ) );
	  endif
	0x824e:
	  if ( GetObjProperty( item, "ammothunder" ) )
		SetObjProperty( item, "ammothunder", GetObjProperty( item, "ammothunder" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "ammothunder", CINT( what.amount ) );
	  endif
	0xbbb1:
	  if ( GetObjProperty( item, "ammothrow" ) )
		SetObjProperty( item, "ammothrow", GetObjProperty( item, "ammothrow" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "ammothrow", CINT( what.amount ) );
	  endif

	0xd90f:
	  if ( GetObjProperty( item, "ammogun" ) )
		SetObjProperty( item, "ammogun", GetObjProperty( item, "ammogun" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "ammogun", CINT( what.amount ) );
	  endif
	0x1BD4:
	  if ( GetObjProperty( item, "ammoshaft" ) )
		SetObjProperty( item, "ammoshaft", GetObjProperty( item, "ammoshaft" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "ammoshaft", CINT( what.amount ) );
	  endif
	0x1bd1:
	  if ( GetObjProperty( item, "ammofeather" ) )
		SetObjProperty( item, "ammofeather", GetObjProperty( item, "ammofeather" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "ammofeather", CINT( what.amount ) );
	  endif
	/*
	0x1f2d:
		if (GetObjProperty(item, "reactivearmorscroll"))
			SetObjProperty(item,"reactivearmorscroll",GetObjProperty(item,"reactivearmorscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "reactivearmorscroll",CINT(what.amount));
		endif
	0x1f2e:
		if (GetObjProperty(item, "clumsyscroll"))
			SetObjProperty(item,"clumsyscroll",GetObjProperty(item,"clumsyscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "clumsyscroll",CINT(what.amount));
		endif
	0x1f2f:
		if (GetObjProperty(item, "createfoodscroll"))
			SetObjProperty(item,"createfoodscroll",GetObjProperty(item,"createfoodscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "createfoodscroll",CINT(what.amount));
		endif
	0x1f30:
		if (GetObjProperty(item, "feeblemindscroll"))
			SetObjProperty(item,"feeblemindscroll",GetObjProperty(item,"feeblemindscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "feeblemindscroll",CINT(what.amount));
		endif
	0x1f31:
		if (GetObjProperty(item, "healscroll"))
			SetObjProperty(item,"healscroll",GetObjProperty(item,"healscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "healscroll",CINT(what.amount));
		endif
	0x1f32:
		if (GetObjProperty(item, "magicarrowscroll"))
			SetObjProperty(item,"magicarrowscroll",GetObjProperty(item,"magicarrowscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "magicarrowscroll",CINT(what.amount));
		endif
	0x1f33:
		if (GetObjProperty(item, "nightsightscroll"))
			SetObjProperty(item,"nightsightscroll",GetObjProperty(item,"nightsightscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "nightsightscroll",CINT(what.amount));
		endif
	0x1f34:
		if (GetObjProperty(item, "weakenscroll"))
			SetObjProperty(item,"weakenscroll",GetObjProperty(item,"weakenscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "weakenscroll",CINT(what.amount));
		endif
	0x1f35:
		if (GetObjProperty(item, "agilityscroll"))
			SetObjProperty(item,"agilityscroll",GetObjProperty(item,"agilityscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "agilityscroll",CINT(what.amount));
		endif
	0x1f36:
		if (GetObjProperty(item, "cunningscroll"))
			SetObjProperty(item,"cunningscroll",GetObjProperty(item,"cunningscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "cunningscroll",CINT(what.amount));
		endif
	0x1f37:
		if (GetObjProperty(item, "curescroll"))
			SetObjProperty(item,"curescroll",GetObjProperty(item,"curescroll") + CINT(what.amount));
		else
			SetObjProperty(item, "curescroll",CINT(what.amount));
		endif
	0x1f38:
		if (GetObjProperty(item, "harmscroll"))
			SetObjProperty(item,"harmscroll",GetObjProperty(item,"harmscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "harmscroll",CINT(what.amount));
		endif
	0x1f39:
		if (GetObjProperty(item, "magictrapscroll"))
			SetObjProperty(item,"magictrapscroll",GetObjProperty(item,"magictrapscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "magictrapscroll",CINT(what.amount));
		endif
	0x1f3a:
		if (GetObjProperty(item, "magicuntrapscroll"))
			SetObjProperty(item,"magicuntrapscroll",GetObjProperty(item,"magicuntrapscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "magicuntrapscroll",CINT(what.amount));
		endif
	0x1f3b:
		if (GetObjProperty(item, "protectionscroll"))
			SetObjProperty(item,"protectionscroll",GetObjProperty(item,"protectionscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "protectionscroll",CINT(what.amount));
		endif
	0x1f3c:
		if (GetObjProperty(item, "strengthscroll"))
			SetObjProperty(item,"strengthscroll",GetObjProperty(item,"strengthscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "strengthscroll",CINT(what.amount));
		endif
	0x1f3d:
		if (GetObjProperty(item, "blessscroll"))
			SetObjProperty(item,"blessscroll",GetObjProperty(item,"blessscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "blessscroll",CINT(what.amount));
		endif
	0x1f3e:
		if (GetObjProperty(item, "fireballscroll"))
			SetObjProperty(item,"fireballscroll",GetObjProperty(item,"fireballscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "fireballscroll",CINT(what.amount));
		endif
	0x1f3f:
		if (GetObjProperty(item, "magiclockscroll"))
			SetObjProperty(item,"magiclockscroll",GetObjProperty(item,"magiclockscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "magiclockscroll",CINT(what.amount));
		endif
	0x1f40:
		if (GetObjProperty(item, "poisonscroll"))
			SetObjProperty(item,"poisonscroll",GetObjProperty(item,"poisonscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "poisonscroll",CINT(what.amount));
		endif
	0x1f41:
		if (GetObjProperty(item, "telekinesisscroll"))
			SetObjProperty(item,"telekinesisscroll",GetObjProperty(item,"telekinesisscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "telekinesisscroll",CINT(what.amount));
		endif
	0x1f42:
		if (GetObjProperty(item, "teleportscroll"))
			SetObjProperty(item,"teleportscroll",GetObjProperty(item,"teleportscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "teleportscroll",CINT(what.amount));
		endif
	0x1f43:
		if (GetObjProperty(item, "magicunlockscroll"))
			SetObjProperty(item,"magicunlockscroll",GetObjProperty(item,"magicunlockscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "magicunlockscroll",CINT(what.amount));
		endif
	0x1f44:
		if (GetObjProperty(item, "wallofstonescroll"))
			SetObjProperty(item,"wallofstonescroll",GetObjProperty(item,"wallofstonescroll") + CINT(what.amount));
		else
			SetObjProperty(item, "wallofstonescroll",CINT(what.amount));
		endif
	0x1f45:
		if (GetObjProperty(item, "archcurescroll"))
			SetObjProperty(item,"archcurescroll",GetObjProperty(item,"archcurescroll") + CINT(what.amount));
		else
			SetObjProperty(item, "archcurescroll",CINT(what.amount));
		endif
	0x1f46:
		if (GetObjProperty(item, "archprotectionscroll"))
			SetObjProperty(item,"archprotectionscroll",GetObjProperty(item,"archprotectionscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "archprotectionscroll",CINT(what.amount));
		endif
	0x1f47:
		if (GetObjProperty(item, "cursecroll"))
			SetObjProperty(item,"cursecroll",GetObjProperty(item,"cursecroll") + CINT(what.amount));
		else
			SetObjProperty(item, "cursecroll",CINT(what.amount));
		endif
	0x1f48:
		if (GetObjProperty(item, "firefieldscroll"))
			SetObjProperty(item,"firefieldscroll",GetObjProperty(item,"firefieldscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "firefieldscroll",CINT(what.amount));
		endif
	0x1f49:
		if (GetObjProperty(item, "greaterhealscroll"))
			SetObjProperty(item,"greaterhealscroll",GetObjProperty(item,"greaterhealscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "greaterhealscroll",CINT(what.amount));
		endif
	0x1f4a:
		if (GetObjProperty(item, "lightningscroll"))
			SetObjProperty(item,"lightningscroll",GetObjProperty(item,"lightningscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "lightningscroll",CINT(what.amount));
		endif
	0x1f4b:
		if (GetObjProperty(item, "manadrainscroll"))
			SetObjProperty(item,"manadrainscroll",GetObjProperty(item,"manadrainscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "manadrainscroll",CINT(what.amount));
		endif
	0x1f4c:
		if (GetObjProperty(item, "recallscroll"))
			SetObjProperty(item,"recallscroll",GetObjProperty(item,"recallscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "recallscroll",CINT(what.amount));
		endif
	0x1f4d:
		if (GetObjProperty(item, "bladespiritscroll"))
			SetObjProperty(item,"bladespiritscroll",GetObjProperty(item,"bladespiritscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "bladespiritscroll",CINT(what.amount));
		endif
	0x1f4e:
		if (GetObjProperty(item, "dispelfieldscroll"))
			SetObjProperty(item,"dispelfieldscroll",GetObjProperty(item,"dispelfieldscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "dispelfieldscroll",CINT(what.amount));
		endif
	0x1f4f:
		if (GetObjProperty(item, "incognitoscroll"))
			SetObjProperty(item,"incognitoscroll",GetObjProperty(item,"incognitoscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "incognitoscroll",CINT(what.amount));
		endif
	0x1f50:
		if (GetObjProperty(item, "magicrelfectscroll"))
			SetObjProperty(item,"magicrelfectscroll",GetObjProperty(item,"magicrelfectscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "magicrelfectscroll",CINT(what.amount));
		endif
	0x1f51:
		if (GetObjProperty(item, "mindblastscroll"))
			SetObjProperty(item,"mindblastscroll",GetObjProperty(item,"mindblastscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "mindblastscroll",CINT(what.amount));
		endif
	0x1f52:
		if (GetObjProperty(item, "paralyzescroll"))
			SetObjProperty(item,"paralyzescroll",GetObjProperty(item,"paralyzescroll") + CINT(what.amount));
		else
			SetObjProperty(item, "paralyzescroll",CINT(what.amount));
		endif
	0x1f53:
		if (GetObjProperty(item, "poisonfieldscroll"))
			SetObjProperty(item,"poisonfieldscroll",GetObjProperty(item,"poisonfieldscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "poisonfieldscroll",CINT(what.amount));
		endif
	0x1f54:
		if (GetObjProperty(item, "summoncreaturescroll"))
			SetObjProperty(item,"summoncreaturescroll",GetObjProperty(item,"summoncreaturescroll") + CINT(what.amount));
		else
			SetObjProperty(item, "summoncreaturescroll",CINT(what.amount));
		endif
	0x1f55:
		if (GetObjProperty(item, "dispelscroll"))
			SetObjProperty(item,"dispelscroll",GetObjProperty(item,"dispelscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "dispelscroll",CINT(what.amount));
		endif
	0x1f56:
		if (GetObjProperty(item, "energyboltscroll"))
			SetObjProperty(item,"energyboltscroll",GetObjProperty(item,"energyboltscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "energyboltscroll",CINT(what.amount));
		endif
	0x1f57:
		if (GetObjProperty(item, "explosionscroll"))
			SetObjProperty(item,"explosionscroll",GetObjProperty(item,"explosionscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "explosionscroll",CINT(what.amount));
		endif
	0x1f58:
		if (GetObjProperty(item, "invisibilityscroll"))
			SetObjProperty(item,"invisibilityscroll",GetObjProperty(item,"invisibilityscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "invisibilityscroll",CINT(what.amount));
		endif
	0x1f59:
		if (GetObjProperty(item, "markscroll"))
			SetObjProperty(item,"markscroll",GetObjProperty(item,"markscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "markscroll",CINT(what.amount));
		endif
	0x1f5a:
		if (GetObjProperty(item, "masscursescroll"))
			SetObjProperty(item,"masscursescroll",GetObjProperty(item,"masscursescroll") + CINT(what.amount));
		else
			SetObjProperty(item, "masscursescroll",CINT(what.amount));
		endif
	0x1f5b:
		if (GetObjProperty(item, "paralyzefieldscroll"))
			SetObjProperty(item,"paralyzefieldscroll",GetObjProperty(item,"paralyzefieldscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "paralyzefieldscroll",CINT(what.amount));
		endif
	0x1f5c:
		if (GetObjProperty(item, "revealscroll"))
			SetObjProperty(item,"revealscroll",GetObjProperty(item,"revealscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "revealscroll",CINT(what.amount));
		endif
	0x1f5d:
		if (GetObjProperty(item, "chainlightningscroll"))
			SetObjProperty(item,"chainlightningscroll",GetObjProperty(item,"chainlightningscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "chainlightningscroll",CINT(what.amount));
		endif
	0x1f5e:
		if (GetObjProperty(item, "energyfieldscroll"))
			SetObjProperty(item,"energyfieldscroll",GetObjProperty(item,"energyfieldscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "energyfieldscroll",CINT(what.amount));
		endif
	0x1f5f:
		if (GetObjProperty(item, "flamestrikescroll"))
			SetObjProperty(item,"flamestrikescroll",GetObjProperty(item,"flamestrikescroll") + CINT(what.amount));
		else
			SetObjProperty(item, "flamestrikescroll",CINT(what.amount));
		endif
	0x1f60:
		if (GetObjProperty(item, "gatetravelscroll"))
			SetObjProperty(item,"gatetravelscroll",GetObjProperty(item,"gatetravelscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "gatetravelscroll",CINT(what.amount));
		endif
	0x1f61:
		if (GetObjProperty(item, "manavampirescroll"))
			SetObjProperty(item,"manavampirescroll",GetObjProperty(item,"manavampirescroll") + CINT(what.amount));
		else
			SetObjProperty(item, "manavampirescroll",CINT(what.amount));
		endif
	0x1f62:
		if (GetObjProperty(item, "massdispelscroll"))
			SetObjProperty(item,"massdispelscroll",GetObjProperty(item,"massdispelscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "massdispelscroll",CINT(what.amount));
		endif
	0x1f63:
		if (GetObjProperty(item, "meteorswarmscroll"))
			SetObjProperty(item,"meteorswarmscroll",GetObjProperty(item,"meteorswarmscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "meteorswarmscroll",CINT(what.amount));
		endif
	0x1f64:
		if (GetObjProperty(item, "polymorphscroll"))
			SetObjProperty(item,"polymorphscroll",GetObjProperty(item,"polymorphscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "polymorphscroll",CINT(what.amount));
		endif
	0x1f65:
		if (GetObjProperty(item, "earthquakescroll"))
			SetObjProperty(item,"earthquakescroll",GetObjProperty(item,"earthquakescroll") + CINT(what.amount));
		else
			SetObjProperty(item, "earthquakescroll",CINT(what.amount));
		endif
	0x1f66:
		if (GetObjProperty(item, "energyvortexscroll"))
			SetObjProperty(item,"energyvortexscroll",GetObjProperty(item,"energyvortexscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "energyvortexscroll",CINT(what.amount));
		endif
	0x1f67:
		if (GetObjProperty(item, "resurrectionscroll"))
			SetObjProperty(item,"resurrectionscroll",GetObjProperty(item,"resurrectionscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "resurrectionscroll",CINT(what.amount));
		endif
	0x1f68:
		if (GetObjProperty(item, "summonairelemscroll"))
			SetObjProperty(item,"summonairelemscroll",GetObjProperty(item,"summonairelemscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "summonairelemscroll",CINT(what.amount));
		endif
	0x1f69:
		if (GetObjProperty(item, "summondaemonscroll"))
			SetObjProperty(item,"summondaemonscroll",GetObjProperty(item,"summondaemonscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "summondaemonscroll",CINT(what.amount));
		endif
	0x1f6a:
		if (GetObjProperty(item, "summonearthelemscroll"))
			SetObjProperty(item,"summonearthelemscroll",GetObjProperty(item,"summonearthelemscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "summonearthelemscroll",CINT(what.amount));
		endif
	0x1f6b:
		if (GetObjProperty(item, "summonfireelemscroll"))
			SetObjProperty(item,"summonfireelemscroll",GetObjProperty(item,"summonfireelemscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "summonfireelemscroll",CINT(what.amount));
		endif
	0x1f6c:
		if (GetObjProperty(item, "summonwaterelemscroll"))
			SetObjProperty(item,"summonwaterelemscroll",GetObjProperty(item,"summonwaterelemscroll") + CINT(what.amount));
		else
			SetObjProperty(item, "summonwaterelemscroll",CINT(what.amount));
		endif
*/
	0xB101:
	  if ( GetObjProperty( item, "Antidotescroll" ) )
		SetObjProperty( item, "Antidotescroll", GetObjProperty( item, "Antidotescroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Antidotescroll", CINT( what.amount ) );
	  endif
	0xB102:
	  if ( GetObjProperty( item, "Owlsightscroll" ) )
		SetObjProperty( item, "Owlsightscroll", GetObjProperty( item, "Owlsightscroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Owlsightscroll", CINT( what.amount ) );
	  endif
	0xB103:
	  if ( GetObjProperty( item, "Shiftingearthscroll" ) )
		SetObjProperty( item, "Shiftingearthscroll", GetObjProperty( item, "Shiftingearthscroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Shiftingearthscroll", CINT( what.amount ) );
	  endif
	0xB104:
	  if ( GetObjProperty( item, "Summonmammalsscroll" ) )
		SetObjProperty( item, "Summonmammalsscroll", GetObjProperty( item, "Summonmammalsscroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Summonmammalsscroll", CINT( what.amount ) );
	  endif
	0xB105:
	  if ( GetObjProperty( item, "Calllightningscroll" ) )
		SetObjProperty( item, "Calllightningscroll", GetObjProperty( item, "Calllightningscroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Calllightningscroll", CINT( what.amount ) );
	  endif
	0xB106:
	  if ( GetObjProperty( item, "Earthblessingscroll" ) )
		SetObjProperty( item, "Earthblessingscroll", GetObjProperty( item, "Earthblessingscroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Earthblessingscroll", CINT( what.amount ) );
	  endif
	0xB107:
	  if ( GetObjProperty( item, "Earthportalscroll" ) )
		SetObjProperty( item, "Earthportalscroll", GetObjProperty( item, "Earthportalscroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Earthportalscroll", CINT( what.amount ) );
	  endif
	0xB108:
	  if ( GetObjProperty( item, "Naturestouchscroll" ) )
		SetObjProperty( item, "Naturestouchscroll", GetObjProperty( item, "Naturestouchscroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Naturestouchscroll", CINT( what.amount ) );
	  endif
	0xB109:
	  if ( GetObjProperty( item, "Gustofairscroll" ) )
		SetObjProperty( item, "Gustofairscroll", GetObjProperty( item, "Gustofairscroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Gustofairscroll", CINT( what.amount ) );
	  endif
	0xB10A:
	  if ( GetObjProperty( item, "Risingfirescroll" ) )
		SetObjProperty( item, "Risingfirescroll", GetObjProperty( item, "Risingfirescroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Risingfirescroll", CINT( what.amount ) );
	  endif
	0xB10B:
	  if ( GetObjProperty( item, "Shapeshiftscroll" ) )
		SetObjProperty( item, "Shapeshiftscroll", GetObjProperty( item, "Shapeshiftscroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Shapeshiftscroll", CINT( what.amount ) );
	  endif
	0xB10C:
	  if ( GetObjProperty( item, "Icestrikescroll" ) )
		SetObjProperty( item, "Icestrikescroll", GetObjProperty( item, "Icestrikescroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Icestrikescroll", CINT( what.amount ) );
	  endif
	0xB10D:
	  if ( GetObjProperty( item, "Earthspiritscroll" ) )
		SetObjProperty( item, "Earthspiritscroll", GetObjProperty( item, "Earthspiritscroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Earthspiritscroll", CINT( what.amount ) );
	  endif
	0xB10E:
	  if ( GetObjProperty( item, "Flamespiritscroll" ) )
		SetObjProperty( item, "Flamespiritscroll", GetObjProperty( item, "Flamespiritscroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Flamespiritscroll", CINT( what.amount ) );
	  endif
	0xB10F:
	  if ( GetObjProperty( item, "Stormspiritscroll" ) )
		SetObjProperty( item, "Stormspiritscroll", GetObjProperty( item, "Stormspiritscroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Stormspiritscroll", CINT( what.amount ) );
	  endif
	0xB110:
	  if ( GetObjProperty( item, "Waterspiritscroll" ) )
		SetObjProperty( item, "Waterspiritscroll", GetObjProperty( item, "Waterspiritscroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "Waterspiritscroll", CINT( what.amount ) );
	  endif
	0xA101:
	  if ( GetObjProperty( item, "ControlUndeadScroll" ) )
		SetObjProperty( item, "ControlUndeadScroll", GetObjProperty( item, "ControlUndeadScroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "ControlUndeadScroll", CINT( what.amount ) );
	  endif
	0xA102:
	  if ( GetObjProperty( item, "DarknessScroll" ) )
		SetObjProperty( item, "DarknessScroll", GetObjProperty( item, "DarknessScroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "DarknessScroll", CINT( what.amount ) );
	  endif
	0xA103:
	  if ( GetObjProperty( item, "DecayingRayScroll" ) )
		SetObjProperty( item, "DecayingRayScroll", GetObjProperty( item, "DecayingRayScroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "DecayingRayScroll", CINT( what.amount ) );
	  endif
	0xA104:
	  if ( GetObjProperty( item, "SpectresTouchScroll" ) )
		SetObjProperty( item, "SpectresTouchScroll", GetObjProperty( item, "SpectresTouchScroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SpectresTouchScroll", CINT( what.amount ) );
	  endif
	0xA105:
	  if ( GetObjProperty( item, "AbyssalFlameScroll" ) )
		SetObjProperty( item, "AbyssalFlameScroll", GetObjProperty( item, "AbyssalFlameScroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "AbyssalFlameScroll", CINT( what.amount ) );
	  endif
	0xA106:
	  if ( GetObjProperty( item, "AnimateDeadScroll" ) )
		SetObjProperty( item, "AnimateDeadScroll", GetObjProperty( item, "AnimateDeadScroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "AnimateDeadScroll", CINT( what.amount ) );
	  endif
	0xA107:
	  if ( GetObjProperty( item, "SacrificeScroll" ) )
		SetObjProperty( item, "SacrificeScroll", GetObjProperty( item, "SacrificeScroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SacrificeScroll", CINT( what.amount ) );
	  endif
	0xA108:
	  if ( GetObjProperty( item, "WraithsBreathScroll" ) )
		SetObjProperty( item, "WraithsBreathScroll", GetObjProperty( item, "WraithsBreathScroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "WraithsBreathScroll", CINT( what.amount ) );
	  endif
	0xA109:
	  if ( GetObjProperty( item, "SorcerersBaneScroll" ) )
		SetObjProperty( item, "SorcerersBaneScroll", GetObjProperty( item, "SorcerersBaneScroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SorcerersBaneScroll", CINT( what.amount ) );
	  endif
	0xA10A:
	  if ( GetObjProperty( item, "SummonSpiritScroll" ) )
		SetObjProperty( item, "SummonSpiritScroll", GetObjProperty( item, "SummonSpiritScroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SummonSpiritScroll", CINT( what.amount ) );
	  endif
	0xA10B:
	  if ( GetObjProperty( item, "WraithformScroll" ) )
		SetObjProperty( item, "WraithformScroll", GetObjProperty( item, "WraithformScroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "WraithformScroll", CINT( what.amount ) );
	  endif
	0xA10C:
	  if ( GetObjProperty( item, "WyvernStrikeScroll" ) )
		SetObjProperty( item, "WyvernStrikeScroll", GetObjProperty( item, "WyvernStrikeScroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "WyvernStrikeScroll", CINT( what.amount ) );
	  endif
	0xA10D:
	  if ( GetObjProperty( item, "KillScroll" ) )
		SetObjProperty( item, "KillScroll", GetObjProperty( item, "KillScroll" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "KillScroll", CINT( what.amount ) );
	  endif
	0xA10E:
	  if ( GetObjProperty( item, "LicheScroll" ) )
		SetObjProperty( item, "LicheScroll", GetObjProperty( item, "LicheScroll" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "LicheScroll", CINT( what.amount ) );
	  endif
	0xA10F:
	  if ( GetObjProperty( item, "PlagueScroll" ) )
		SetObjProperty( item, "PlagueScroll", GetObjProperty( item, "PlagueScroll" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "PlagueScroll", CINT( what.amount ) );
	  endif
	0xA110:
	  if ( GetObjProperty( item, "SpellbindScroll" ) )
		SetObjProperty( item, "SpellbindScroll", GetObjProperty( item, "SpellbindScroll" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SpellbindScroll", CINT( what.amount ) );
	  endif
	0x6178:
	  if ( GetObjProperty( item, "songscroll1" ) )
		SetObjProperty( item, "songscroll1", GetObjProperty( item, "songscroll1" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll1", CINT( what.amount ) );
	  endif
	0x6179:
	  if ( GetObjProperty( item, "songscroll2" ) )
		SetObjProperty( item, "songscroll2", GetObjProperty( item, "songscroll2" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll2", CINT( what.amount ) );
	  endif
	0x617a:
	  if ( GetObjProperty( item, "songscroll3" ) )
		SetObjProperty( item, "songscroll3", GetObjProperty( item, "songscroll3" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll3", CINT( what.amount ) );
	  endif
	0x617b:
	  if ( GetObjProperty( item, "songscroll4" ) )
		SetObjProperty( item, "songscroll4", GetObjProperty( item, "songscroll4" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll4", CINT( what.amount ) );
	  endif
	0x617c:
	  if ( GetObjProperty( item, "songscroll5" ) )
		SetObjProperty( item, "songscroll5", GetObjProperty( item, "songscroll5" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll5", CINT( what.amount ) );
	  endif
	0x617d:
	  if ( GetObjProperty( item, "songscroll6" ) )
		SetObjProperty( item, "songscroll6", GetObjProperty( item, "songscroll6" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll6", CINT( what.amount ) );
	  endif
	0x617e:
	  if ( GetObjProperty( item, "songscroll7" ) )
		SetObjProperty( item, "songscroll7", GetObjProperty( item, "songscroll7" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll7", CINT( what.amount ) );
	  endif
	0x617f:
	  if ( GetObjProperty( item, "songscroll8" ) )
		SetObjProperty( item, "songscroll8", GetObjProperty( item, "songscroll8" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll8", CINT( what.amount ) );
	  endif
	0x6180:
	  if ( GetObjProperty( item, "songscroll9" ) )
		SetObjProperty( item, "songscroll9", GetObjProperty( item, "songscroll9" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll9", CINT( what.amount ) );
	  endif
	0x6181:
	  if ( GetObjProperty( item, "songscroll10" ) )
		SetObjProperty( item, "songscroll10", GetObjProperty( item, "songscroll10" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll10", CINT( what.amount ) );
	  endif
	0x6182:
	  if ( GetObjProperty( item, "songscroll11" ) )
		SetObjProperty( item, "songscroll11", GetObjProperty( item, "songscroll11" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll11", CINT( what.amount ) );
	  endif
	0x6183:
	  if ( GetObjProperty( item, "songscroll12" ) )
		SetObjProperty( item, "songscroll12", GetObjProperty( item, "songscroll12" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll12", CINT( what.amount ) );
	  endif
	0x6184:
	  if ( GetObjProperty( item, "songscroll13" ) )
		SetObjProperty( item, "songscroll13", GetObjProperty( item, "songscroll13" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll13", CINT( what.amount ) );
	  endif
	0x6185:
	  if ( GetObjProperty( item, "songscroll14" ) )
		SetObjProperty( item, "songscroll14", GetObjProperty( item, "songscroll14" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll14", CINT( what.amount ) );
	  endif
	0x6186:
	  if ( GetObjProperty( item, "songscroll15" ) )
		SetObjProperty( item, "songscroll15", GetObjProperty( item, "songscroll15" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll15", CINT( what.amount ) );
	  endif
	0x6187:
	  if ( GetObjProperty( item, "songscroll16" ) )
		SetObjProperty( item, "songscroll16", GetObjProperty( item, "songscroll16" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll16", CINT( what.amount ) );
	  endif
	0x6188:
	  if ( GetObjProperty( item, "songscroll17" ) )
		SetObjProperty( item, "songscroll17", GetObjProperty( item, "songscroll17" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll17", CINT( what.amount ) );
	  endif
	0x6189:
	  if ( GetObjProperty( item, "songscroll18" ) )
		SetObjProperty( item, "songscroll18", GetObjProperty( item, "songscroll18" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll18", CINT( what.amount ) );
	  endif
	0x618a:
	  if ( GetObjProperty( item, "songscroll19" ) )
		SetObjProperty( item, "songscroll19", GetObjProperty( item, "songscroll19" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll19", CINT( what.amount ) );
	  endif
	0x618b:
	  if ( GetObjProperty( item, "songscroll20" ) )
		SetObjProperty( item, "songscroll20", GetObjProperty( item, "songscroll20" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "songscroll20", CINT( what.amount ) );
	  endif
	0x6167:
	  if ( GetObjProperty( item, "holyscroll1" ) )
		SetObjProperty( item, "holyscroll1", GetObjProperty( item, "holyscroll1" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "holyscroll1", CINT( what.amount ) );
	  endif
	0x6168:
	  if ( GetObjProperty( item, "holyscroll2" ) )
		SetObjProperty( item, "holyscroll2", GetObjProperty( item, "holyscroll2" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "holyscroll2", CINT( what.amount ) );
	  endif
	0x6169:
	  if ( GetObjProperty( item, "holyscroll3" ) )
		SetObjProperty( item, "holyscroll3", GetObjProperty( item, "holyscroll3" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "holyscroll3", CINT( what.amount ) );
	  endif
	0x616a:
	  if ( GetObjProperty( item, "holyscroll4" ) )
		SetObjProperty( item, "holyscroll4", GetObjProperty( item, "holyscroll4" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "holyscroll4", CINT( what.amount ) );
	  endif
	0x616b:
	  if ( GetObjProperty( item, "holyscroll5" ) )
		SetObjProperty( item, "holyscroll5", GetObjProperty( item, "holyscroll5" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "holyscroll5", CINT( what.amount ) );
	  endif
	0x616c:
	  if ( GetObjProperty( item, "holyscroll6" ) )
		SetObjProperty( item, "holyscroll6", GetObjProperty( item, "holyscroll6" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "holyscroll6", CINT( what.amount ) );
	  endif
	0x616d:
	  if ( GetObjProperty( item, "holyscroll7" ) )
		SetObjProperty( item, "holyscroll7", GetObjProperty( item, "holyscroll7" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "holyscroll7", CINT( what.amount ) );
	  endif
	0x616e:
	  if ( GetObjProperty( item, "holyscroll8" ) )
		SetObjProperty( item, "holyscroll8", GetObjProperty( item, "holyscroll8" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "holyscroll8", CINT( what.amount ) );
	  endif
	0x616f:
	  if ( GetObjProperty( item, "holyscroll9" ) )
		SetObjProperty( item, "holyscroll9", GetObjProperty( item, "holyscroll9" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "holyscroll9", CINT( what.amount ) );
	  endif
	0x0E34:
	  if ( GetObjProperty( item, "blankscroll" ) )
		SetObjProperty( item, "blankscroll", GetObjProperty( item, "blankscroll" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "blankscroll", CINT( what.amount ) );
	  endif
	0x6001:
	  if ( GetObjProperty( item, "blankmap" ) )
		SetObjProperty( item, "blankmap", GetObjProperty( item, "blankmap" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "blankmap", CINT( what.amount ) );
	  endif
	0x14fb:
	  if ( GetObjProperty( item, "lockpick" ) )
		SetObjProperty( item, "lockpick", GetObjProperty( item, "lockpick" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "lockpick", CINT( what.amount ) );
	  endif
	0x0F0E:
	  if ( GetObjProperty( item, "emptybottle" ) )
		SetObjProperty( item, "emptybottle", GetObjProperty( item, "emptybottle" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "emptybottle", CINT( what.amount ) );
	  endif
	0x1f14:
	  if ( GetObjProperty( item, "recallrune" ) )
		SetObjProperty( item, "recallrune", GetObjProperty( item, "recallrune" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "recallrune", CINT( what.amount ) );
	  endif
	0x0de1:
	  if ( GetObjProperty( item, "kindling" ) )
		SetObjProperty( item, "kindling", GetObjProperty( item, "kindling" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "kindling", CINT( what.amount ) );
	  endif
	0x0e21:
	  if ( GetObjProperty( item, "bandages" ) )
		SetObjProperty( item, "bandages", GetObjProperty( item, "bandages" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "bandages", CINT( what.amount ) );
	  endif
	0x181d:
	  if ( GetObjProperty( item, "SymbolOfAbsorption" ) )
		SetObjProperty( item, "SymbolOfAbsorption", GetObjProperty( item, "SymbolOfAbsorption" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SymbolOfAbsorption", CINT( what.amount ) );
	  endif
	0x181e:
	  if ( GetObjProperty( item, "SymbolOfToxinsResistance" ) )
		SetObjProperty( item, "SymbolOfToxinsResistance",
				  GetObjProperty( item, "SymbolOfToxinsResistance" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SymbolOfToxinsResistance", CINT( what.amount ) );
	  endif
	0x181f:
	  if ( GetObjProperty( item, "SymbolOfHealth" ) )
		SetObjProperty( item, "SymbolOfHealth", GetObjProperty( item, "SymbolOfHealth" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SymbolOfHealth", CINT( what.amount ) );
	  endif
	0x1821:
	  if ( GetObjProperty( item, "SymbolOfHeavenTouch" ) )
		SetObjProperty( item, "SymbolOfHeavenTouch", GetObjProperty( item, "SymbolOfHeavenTouch" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SymbolOfHeavenTouch", CINT( what.amount ) );
	  endif
	0x1822:
	  if ( GetObjProperty( item, "SymbolOfHellFire" ) )
		SetObjProperty( item, "SymbolOfHellFire", GetObjProperty( item, "SymbolOfHellFire" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SymbolOfHellFire", CINT( what.amount ) );
	  endif
	0x1823:
	  if ( GetObjProperty( item, "SymbolOfVanishing" ) )
		SetObjProperty( item, "SymbolOfVanishing", GetObjProperty( item, "SymbolOfVanishing" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SymbolOfVanishing", CINT( what.amount ) );
	  endif
	0x1824:
	  if ( GetObjProperty( item, "SymbolOfVengeance" ) )
		SetObjProperty( item, "SymbolOfVengeance", GetObjProperty( item, "SymbolOfVengeance" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SymbolOfVengeance", CINT( what.amount ) );
	  endif
	0x1825:
	  if ( GetObjProperty( item, "SymbolOfRecalling" ) )
		SetObjProperty( item, "SymbolOfRecalling", GetObjProperty( item, "SymbolOfRecalling" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SymbolOfRecalling", CINT( what.amount ) );
	  endif
	0x1826:
	  if ( GetObjProperty( item, "SymbolOfThunderStorm" ) )
		SetObjProperty( item, "SymbolOfThunderStorm", GetObjProperty( item, "SymbolOfThunderStorm" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SymbolOfThunderStorm", CINT( what.amount ) );
	  endif
	0x1827:
	  if ( GetObjProperty( item, "SymbolOfRegeneration" ) )
		SetObjProperty( item, "SymbolOfRegeneration", GetObjProperty( item, "SymbolOfRegeneration" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SymbolOfRegeneration", CINT( what.amount ) );
	  endif
	0x1828:
	  if ( GetObjProperty( item, "SymbolOfLifeStream" ) )
		SetObjProperty( item, "SymbolOfLifeStream", GetObjProperty( item, "SymbolOfLifeStream" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "SymbolOfLifeStream", CINT( what.amount ) );
	  endif

	0xd05c:
	  if ( GetObjProperty( item, "AirEnchantedRune" ) )
		SetObjProperty( item, "AirEnchantedRune", GetObjProperty( item, "AirEnchantedRune" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "AirEnchantedRune", CINT( what.amount ) );
	  endif
	0xd05d:
	  if ( GetObjProperty( item, "EarthEnchantedRune2" ) )
		SetObjProperty( item, "EarthEnchantedRune2", GetObjProperty( item, "EarthEnchantedRune2" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "EarthEnchantedRune2", CINT( what.amount ) );
	  endif
	0xd05e:
	  if ( GetObjProperty( item, "FireEnchantedRune3" ) )
		SetObjProperty( item, "FireEnchantedRune3", GetObjProperty( item, "FireEnchantedRune3" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "FireEnchantedRune3", CINT( what.amount ) );
	  endif
	0xd05f:
	  if ( GetObjProperty( item, "NecroEnchantedRune4" ) )
		SetObjProperty( item, "NecroEnchantedRune4", GetObjProperty( item, "NecroEnchantedRune4" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "NecroEnchantedRune4", CINT( what.amount ) );
	  endif
	0xd060:
	  if ( GetObjProperty( item, "WaterEnchantedRune5" ) )
		SetObjProperty( item, "WaterEnchantedRune5", GetObjProperty( item, "WaterEnchantedRune5" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "WaterEnchantedRune5", CINT( what.amount ) );
	  endif
	0xd061:
	  if ( GetObjProperty( item, "HolyEnchantedRune6" ) )
		SetObjProperty( item, "HolyEnchantedRune6", GetObjProperty( item, "HolyEnchantedRune6" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "HolyEnchantedRune6", CINT( what.amount ) );
	  endif
	0xd062:
	  if ( GetObjProperty( item, "PoisonEnchantedRune7" ) )
		SetObjProperty( item, "PoisonEnchantedRune7", GetObjProperty( item, "PoisonEnchantedRune7" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "PoisonEnchantedRune7", CINT( what.amount ) );
	  endif
	0xd063:
	  if ( GetObjProperty( item, "DefenseEnchantedRune8" ) )
		SetObjProperty( item, "DefenseEnchantedRune8", GetObjProperty( item, "DefenseEnchantedRune8" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "DefenseEnchantedRune8", CINT( what.amount ) );
	  endif
	0xd064:
	  if ( GetObjProperty( item, "ColdEnchantedRune9" ) )
		SetObjProperty( item, "ColdEnchantedRune9", GetObjProperty( item, "ColdEnchantedRune9" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "ColdEnchantedRune9", CINT( what.amount ) );
	  endif
	0xd065:
	  if ( GetObjProperty( item, "LightEnchantedRune10" ) )
		SetObjProperty( item, "LightEnchantedRune10", GetObjProperty( item, "LightEnchantedRune10" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "LightEnchantedRune10", CINT( what.amount ) );
	  endif
	0xd066:
	  if ( GetObjProperty( item, "DarkEnchantedRune11" ) )
		SetObjProperty( item, "DarkEnchantedRune11", GetObjProperty( item, "DarkEnchantedRune11" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "DarkEnchantedRune11", CINT( what.amount ) );
	  endif
	0xd067:
	  if ( GetObjProperty( item, "HealingEnchantedRune12" ) )
		SetObjProperty( item, "HealingEnchantedRune12", GetObjProperty( item, "HealingEnchantedRune12" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "HealingEnchantedRune12", CINT( what.amount ) );
	  endif
	0xd068:
	  if ( GetObjProperty( item, "speedEnchantedRune20" ) )
		SetObjProperty( item, "speedEnchantedRune20", GetObjProperty( item, "speedEnchantedRune20" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "speedEnchantedRune20", CINT( what.amount ) );
	  endif
	0xd069:
	  if ( GetObjProperty( item, "mindEnchantedRune21" ) )
		SetObjProperty( item, "mindEnchantedRune21", GetObjProperty( item, "mindEnchantedRune21" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "mindEnchantedRune21", CINT( what.amount ) );
	  endif
	0xd06a:
	  if ( GetObjProperty( item, "staminaEnchantedRune22" ) )
		SetObjProperty( item, "staminaEnchantedRune22", GetObjProperty( item, "staminaEnchantedRune22" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "staminaEnchantedRune22", CINT( what.amount ) );
	  endif
	0xd06d:
	  if ( GetObjProperty( item, "anatomyEnchantedRune31" ) )
		SetObjProperty( item, "anatomyEnchantedRune31", GetObjProperty( item, "anatomyEnchantedRune31" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "anatomyEnchantedRune31", CINT( what.amount ) );
	  endif
	0xd096:
	  if ( GetObjProperty( item, "fencingEnchantedRune72" ) )
		SetObjProperty( item, "fencingEnchantedRune72", GetObjProperty( item, "fencingEnchantedRune72" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "fencingEnchantedRune72", CINT( what.amount ) );
	  endif
	0xd07d:
	  if ( GetObjProperty( item, "healingEnchantedRune47" ) )
		SetObjProperty( item, "healingEnchantedRune47", GetObjProperty( item, "healingEnchantedRune47" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "healingEnchantedRune47", CINT( what.amount ) );
	  endif
	0xd095:
	  if ( GetObjProperty( item, "maceEnchantedRune71" ) )
		SetObjProperty( item, "maceEnchantedRune71", GetObjProperty( item, "maceEnchantedRune71" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "maceEnchantedRune71", CINT( what.amount ) );
	  endif
	0xd071:
	  if ( GetObjProperty( item, "parryingEnchantedRune35" ) )
		SetObjProperty( item, "parryingEnchantedRune35",
				  GetObjProperty( item, "parryingEnchantedRune35" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "parryingEnchantedRune35", CINT( what.amount ) );
	  endif
	0xd094:
	  if ( GetObjProperty( item, "swordEnchantedRune70" ) )
		SetObjProperty( item, "swordEnchantedRune70", GetObjProperty( item, "swordEnchantedRune70" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "swordEnchantedRune70", CINT( what.amount ) );
	  endif
	0xd087:
	  if ( GetObjProperty( item, "tacticsEnchantedRune57" ) )
		SetObjProperty( item, "tacticsEnchantedRune57", GetObjProperty( item, "tacticsEnchantedRune57" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "tacticsEnchantedRune57", CINT( what.amount ) );
	  endif
	0xd097:
	  if ( GetObjProperty( item, "wrestlingEnchantedRune73" ) )
		SetObjProperty( item, "wrestlingEnchantedRune73",
				  GetObjProperty( item, "wrestlingEnchantedRune73" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "wrestlingEnchantedRune73", CINT( what.amount ) );
	  endif
	0xd06e:
	  if ( GetObjProperty( item, "loreEnchantedRune32" ) )
		SetObjProperty( item, "loreEnchantedRune32", GetObjProperty( item, "loreEnchantedRune32" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "loreEnchantedRune32", CINT( what.amount ) );
	  endif
	0xd08f:
	  if ( GetObjProperty( item, "tamingEnchantedRune65" ) )
		SetObjProperty( item, "tamingEnchantedRune65", GetObjProperty( item, "tamingEnchantedRune65" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "tamingEnchantedRune65", CINT( what.amount ) );
	  endif
	0xd08b:
	  if ( GetObjProperty( item, "archeryEnchantedRune61" ) )
		SetObjProperty( item, "archeryEnchantedRune61", GetObjProperty( item, "archeryEnchantedRune61" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "archeryEnchantedRune61", CINT( what.amount ) );
	  endif
	0xd078:
	  if ( GetObjProperty( item, "cartEnchantedRune42" ) )
		SetObjProperty( item, "cartEnchantedRune42", GetObjProperty( item, "cartEnchantedRune42" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "cartEnchantedRune42", CINT( what.amount ) );
	  endif
	0xd07e:
	  if ( GetObjProperty( item, "fishingEnchantedRune48" ) )
		SetObjProperty( item, "fishingEnchantedRune48", GetObjProperty( item, "fishingEnchantedRune48" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "fishingEnchantedRune48", CINT( what.amount ) );
	  endif
	0xd092:
	  if ( GetObjProperty( item, "trackEnchantedRune68" ) )
		SetObjProperty( item, "trackEnchantedRune68", GetObjProperty( item, "trackEnchantedRune68" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "trackEnchantedRune68", CINT( what.amount ) );
	  endif
	0xd093:
	  if ( GetObjProperty( item, "veterEnchantedRune69" ) )
		SetObjProperty( item, "veterEnchantedRune69", GetObjProperty( item, "veterEnchantedRune69" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "veterEnchantedRune69", CINT( what.amount ) );
	  endif
	0xd079:
	  if ( GetObjProperty( item, "cookingEnchantedRune43" ) )
		SetObjProperty( item, "cookingEnchantedRune43", GetObjProperty( item, "cookingEnchantedRune43" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "cookingEnchantedRune43", CINT( what.amount ) );
	  endif
	0xd06c:
	  if ( GetObjProperty( item, "alchemyEnchantedRune30" ) )
		SetObjProperty( item, "alchemyEnchantedRune30", GetObjProperty( item, "alchemyEnchantedRune30" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "alchemyEnchantedRune30", CINT( what.amount ) );
	  endif
	0xd07c:
	  if ( GetObjProperty( item, "evalEnchantedRune46" ) )
		SetObjProperty( item, "evalEnchantedRune46", GetObjProperty( item, "evalEnchantedRune46" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "evalEnchantedRune46", CINT( what.amount ) );
	  endif
	0xd083:
	  if ( GetObjProperty( item, "scribeEnchantedRune53" ) )
		SetObjProperty( item, "scribeEnchantedRune53", GetObjProperty( item, "scribeEnchantedRune53" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "scribeEnchantedRune53", CINT( what.amount ) );
	  endif
	0xd06f:
	  if ( GetObjProperty( item, "itemidEnchantedRune33" ) )
		SetObjProperty( item, "itemidEnchantedRune33", GetObjProperty( item, "itemidEnchantedRune33" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "itemidEnchantedRune33", CINT( what.amount ) );
	  endif
	0xd085:
	  if ( GetObjProperty( item, "mageryEnchantedRune55" ) )
		SetObjProperty( item, "mageryEnchantedRune55", GetObjProperty( item, "mageryEnchantedRune55" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "mageryEnchantedRune55", CINT( what.amount ) );
	  endif
	0xd09a:
	  if ( GetObjProperty( item, "meditEnchantedRune76" ) )
		SetObjProperty( item, "meditEnchantedRune76", GetObjProperty( item, "meditEnchantedRune76" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "meditEnchantedRune76", CINT( what.amount ) );
	  endif
	0xd086:
	  if ( GetObjProperty( item, "resistEnchantedRune56" ) )
		SetObjProperty( item, "resistEnchantedRune56", GetObjProperty( item, "resistEnchantedRune56" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "resistEnchantedRune56", CINT( what.amount ) );
	  endif
	0xd08c:
	  if ( GetObjProperty( item, "spiritEnchantedRune62" ) )
		SetObjProperty( item, "spiritEnchantedRune62", GetObjProperty( item, "spiritEnchantedRune62" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "spiritEnchantedRune62", CINT( what.amount ) );
	  endif
	0xd072:
	  if ( GetObjProperty( item, "beggingEnchantedRune36" ) )
		SetObjProperty( item, "beggingEnchantedRune36", GetObjProperty( item, "beggingEnchantedRune36" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "beggingEnchantedRune36", CINT( what.amount ) );
	  endif
	0xd07b:
	  if ( GetObjProperty( item, "enticEnchantedRune45" ) )
		SetObjProperty( item, "enticEnchantedRune45", GetObjProperty( item, "enticEnchantedRune45" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "enticEnchantedRune45", CINT( what.amount ) );
	  endif
	0xd080:
	  if ( GetObjProperty( item, "herdingEnchantedRune50" ) )
		SetObjProperty( item, "herdingEnchantedRune50", GetObjProperty( item, "herdingEnchantedRune50" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "herdingEnchantedRune50", CINT( what.amount ) );
	  endif
	0xd089:
	  if ( GetObjProperty( item, "musicEnchantedRune59" ) )
		SetObjProperty( item, "musicEnchantedRune59", GetObjProperty( item, "musicEnchantedRune59" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "musicEnchantedRune59", CINT( what.amount ) );
	  endif
	0xd075:
	  if ( GetObjProperty( item, "peaceEnchantedRune39" ) )
		SetObjProperty( item, "peaceEnchantedRune39", GetObjProperty( item, "peaceEnchantedRune39" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "peaceEnchantedRune39", CINT( what.amount ) );
	  endif
	0xd082:
	  if ( GetObjProperty( item, "provocEnchantedRune52" ) )
		SetObjProperty( item, "provocEnchantedRune52", GetObjProperty( item, "provocEnchantedRune52" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "provocEnchantedRune52", CINT( what.amount ) );
	  endif
	0xd07a:
	  if ( GetObjProperty( item, "detectEnchantedRune44" ) )
		SetObjProperty( item, "detectEnchantedRune44", GetObjProperty( item, "detectEnchantedRune44" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "detectEnchantedRune44", CINT( what.amount ) );
	  endif
	0xd081:
	  if ( GetObjProperty( item, "hidingEnchantedRune51" ) )
		SetObjProperty( item, "hidingEnchantedRune51", GetObjProperty( item, "hidingEnchantedRune51" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "hidingEnchantedRune51", CINT( what.amount ) );
	  endif
	0xd084:
	  if ( GetObjProperty( item, "lockpickEnchantedRune54" ) )
		SetObjProperty( item, "lockpickEnchantedRune54",
				  GetObjProperty( item, "lockpickEnchantedRune54" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "lockpickEnchantedRune54", CINT( what.amount ) );
	  endif
	0xd08a:
	  if ( GetObjProperty( item, "poisonEnchantedRune60" ) )
		SetObjProperty( item, "poisonEnchantedRune60", GetObjProperty( item, "poisonEnchantedRune60" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "poisonEnchantedRune60", CINT( what.amount ) );
	  endif
	0xd088:
	  if ( GetObjProperty( item, "snoopEnchantedRune58" ) )
		SetObjProperty( item, "snoopEnchantedRune58", GetObjProperty( item, "snoopEnchantedRune58" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "snoopEnchantedRune58", CINT( what.amount ) );
	  endif
	0xd08d:
	  if ( GetObjProperty( item, "stealingEnchantedRune63" ) )
		SetObjProperty( item, "stealingEnchantedRune63",
				  GetObjProperty( item, "stealingEnchantedRune63" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "stealingEnchantedRune63", CINT( what.amount ) );
	  endif
	0xd09b:
	  if ( GetObjProperty( item, "stealthEnchantedRune77" ) )
		SetObjProperty( item, "stealthEnchantedRune77", GetObjProperty( item, "stealthEnchantedRune77" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "stealthEnchantedRune77", CINT( what.amount ) );
	  endif
	0xd070:
	  if ( GetObjProperty( item, "armsloreEnchantedRune34" ) )
		SetObjProperty( item, "armsloreEnchantedRune34",
				  GetObjProperty( item, "armsloreEnchantedRune34" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "armsloreEnchantedRune34", CINT( what.amount ) );
	  endif
	0xd073:
	  if ( GetObjProperty( item, "bsEnchantedRune37" ) )
		SetObjProperty( item, "bsEnchantedRune37", GetObjProperty( item, "bsEnchantedRune37" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "bsEnchantedRune37", CINT( what.amount ) );
	  endif
	0xd074:
	  if ( GetObjProperty( item, "bowcraftEnchantedRune38" ) )
		SetObjProperty( item, "bowcraftEnchantedRune38",
				  GetObjProperty( item, "bowcraftEnchantedRune38" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "bowcraftEnchantedRune38", CINT( what.amount ) );
	  endif
	0xd077:
	  if ( GetObjProperty( item, "carpEnchantedRune41" ) )
		SetObjProperty( item, "carpEnchantedRune41", GetObjProperty( item, "carpEnchantedRune41" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "carpEnchantedRune41", CINT( what.amount ) );
	  endif
	0xd098:
	  if ( GetObjProperty( item, "lumberEnchantedRune74" ) )
		SetObjProperty( item, "lumberEnchantedRune74", GetObjProperty( item, "lumberEnchantedRune74" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "lumberEnchantedRune74", CINT( what.amount ) );
	  endif
	0xd099:
	  if ( GetObjProperty( item, "miningEnchantedRune75" ) )
		SetObjProperty( item, "miningEnchantedRune75", GetObjProperty( item, "miningEnchantedRune75" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "miningEnchantedRune75", CINT( what.amount ) );
	  endif
	0xd08e:
	  if ( GetObjProperty( item, "tailoringEnchantedRune64" ) )
		SetObjProperty( item, "tailoringEnchantedRune64",
				  GetObjProperty( item, "tailoringEnchantedRune64" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "tailoringEnchantedRune64", CINT( what.amount ) );
	  endif
	0xd091:
	  if ( GetObjProperty( item, "tinkeringEnchantedRune67" ) )
		SetObjProperty( item, "tinkeringEnchantedRune67",
				  GetObjProperty( item, "tinkeringEnchantedRune67" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "tinkeringEnchantedRune67", CINT( what.amount ) );
	  endif
	0xd076:
	  if ( GetObjProperty( item, "campingEnchantedRune40" ) )
		SetObjProperty( item, "campingEnchantedRune40", GetObjProperty( item, "campingEnchantedRune40" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "campingEnchantedRune40", CINT( what.amount ) );
	  endif
	0xd07f:
	  if ( GetObjProperty( item, "forensicEnchantedRune49" ) )
		SetObjProperty( item, "forensicEnchantedRune49",
				  GetObjProperty( item, "forensicEnchantedRune49" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "forensicEnchantedRune49", CINT( what.amount ) );
	  endif
	0xd09c:
	  if ( GetObjProperty( item, "removetrapEnchantedRune78" ) )
		SetObjProperty( item, "removetrapEnchantedRune78",
				  GetObjProperty( item, "removetrapEnchantedRune78" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "removetrapEnchantedRune78", CINT( what.amount ) );
	  endif
	0xd090:
	  if ( GetObjProperty( item, "tasteidEnchantedRune66" ) )
		SetObjProperty( item, "tasteidEnchantedRune66", GetObjProperty( item, "tasteidEnchantedRune66" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "tasteidEnchantedRune66", CINT( what.amount ) );
	  endif
	0xf022:
	  if ( GetObjProperty( item, "castspeedupgrade" ) )
		SetObjProperty( item, "castspeedupgrade", GetObjProperty( item, "castspeedupgrade" )
				  + CINT( what.amount ) );
	  else
		SetObjProperty( item, "castspeedupgrade", CINT( what.amount ) );
	  endif
	0xf025:
	  if ( GetObjProperty( item, "hitupgrade" ) )
		SetObjProperty( item, "hitupgrade", GetObjProperty( item, "hitupgrade" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "hitupgrade", CINT( what.amount ) );
	  endif
	0xf028:
	  if ( GetObjProperty( item, "damagebonus" ) )
		SetObjProperty( item, "damagebonus", GetObjProperty( item, "damagebonus" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "damagebonus", CINT( what.amount ) );
	  endif
	0xf029:
	  if ( GetObjProperty( item, "armorupgrade" ) )
		SetObjProperty( item, "armorupgrade", GetObjProperty( item, "armorupgrade" ) + CINT( what.amount ) );
	  else
		SetObjProperty( item, "armorupgrade", CINT( what.amount ) );
	  endif
	default: SendSysMessage( who, "There is no place for this item." ); return;
  endcase
  DestroyItem( what );
endfunction

function rescollect( who, item )
  SendSysMessage( who, "What item do you want to put in the closet?" );

  var what := Target( who, TGTOPT_CHECK_LOS );

  if ( coordist( item.x, item.y, who.x, who.y ) > 6 )
	SendSysMessage( who, "The box is too far away" );
	return;
  endif

  var obbjtype := { 0x0F85,
				    0x0F86,
				    0x0F84,
				    0x0F88,
				    0x0F8C,
				    0x0F8D,
				    0x0F7A,
				    0x0F7B,
				    0x0F78,
				    0x0F79,
				    0x0F7C,
				    0x0F7D,
				    0x0F7E,
				    0x0F7F,
				    0x0F80,
				    0x0F81,
				    0x0F82,
				    0x0F83,
				    0x0F87,
				    0x0F89,
				    0x0F8A,
				    0x0F8B,
				    0x0F8E,
				    0x0F8F,
				    0x0F90,
				    0x0F91,
				    0x0F0F,
				    0x0F10,
				    0x0F11,
				    0x0F13,
				    0x0F15,
				    0x0F16,
				    0x0F18,
				    0x0F25,
				    0x0F30,
				    0x6011,
				    0x6012,
				    0x6013,
				    0x6014,
				    0x6015,
				    0x6016,
				    0x6017,
				    0x6018,
				    0xc510,
				    0xc511,
				    0xc512,
				    0xc513,
				    0xc514,
				    0xc515,
				    0xc516,
				    0xc517,
				    0xc518,
				    0xd04a,
				    0x0F95,
				    0x1765,
				    0x0df8,
				    0xee19,
				    0x1be9,
				    0x1078,
				    0x7020,
				    0x7021,
				    0x7022,
				    0x702d,
				    0x7023,
				    0x7025,
				    0x7026,
				    0x7028,
				    0x702a,
				    0x702e,
				    0x7024,
				    0x7027,
				    0x702f,
				    0x7029,
				    0x702b,
				    0x702c,
				    0x1BDD,
				    0x7300,
				    0x7301,
				    0x7302,
				    0x7303,
				    0x7304,
				    0x7305,
				    0x7306,
				    0x7307,
				    0x7308,
				    0x7309,
				    0x730a,
				    0x730b,
				    0x730c,
				    0xee20,
				    0x099B,
				    0x099F,
				    0x09C7,
				    0x1f96,
				    0x1f98,
				    0x1f9a,
				    0x1f9c,
				    0x1f9e,
				    0x09ad,
				    0x1F85,
				    0x09EE,
				    0x1F8D,
				    0x1F7D,
				    0x1F89,
				    0x1F91,
				    0x1045,
				    0x09f1,
				    0x097a,
				    0x09b9,
				    0x09c9,
				    0x0976,
				    0x1e8a,
				    0x1607,
				    0x1609,
				    0x09ec,
				    0x1726,
				    0xc803,
				    0xc804,
				    0x09cd,
				    0x09ce,
				    0x09cf,
				    0x097E,
				    0x1608,
				    0x160a,
				    0xc923,
				    0x097b,
				    0x1e1e,
				    0x09b7,
				    0x09f2,
				    0xA368,
				    0xA369,
				    0xA36A,
				    0xA36B,
				    0xA36C,
				    0xA36D,
				    0xA36E,
				    0xA36F,
				    0xc912,
				    0xc942,
				    0xc943,
				    0x27bc,
				    0x0c6d,
				    0x0eed,
				    0x3b9a,
				    0xdf0c,
				    0x7059,
				    0xdc01,
				    0xdc02,
				    0xdc03,
				    0xdc04,
				    0xdc05,
				    0xdc06,
				    0xdc07,
				    0xdc08,
				    0xdc09,
				    0xdc0b,
				    0xdc0c,
				    0xdc0d,
				    0xdc0e,
				    0xdc0f,
				    0xdc10,
				    0xdc11,
				    0xdc12,
				    0xdc14,
				    0xdc15,
				    0xdc16,
				    0xdc17,
				    0xdce6,
				    0xdce7,
				    0xdce8,
				    0x0f3f,
				    0x1bfb,
				    0x6051,
				    0xb200,
				    0x824e,
				    0xbbb1,
				    0xd90f,
				    0x1BD4,
				    0x1bd1,
				    0xB101,
				    0xB102,
				    0xB103,
				    0xB104,
				    0xB105,
				    0xB106,
				    0xB107,
				    0xB108,
				    0xB109,
				    0xB10a,
				    0xB10b,
				    0xB10c,
				    0xB10d,
				    0xB10e,
				    0xB10f,
				    0xB110,
				    0xA101,
				    0xA102,
				    0xA103,
				    0xA104,
				    0xA105,
				    0xA106,
				    0xA107,
				    0xA108,
				    0xA109,
				    0xA10a,
				    0xA10b,
				    0xA10c,
				    0xA10d,
				    0xA10e,
				    0xA10f,
				    0xA110,
				    0x6178,
				    0x6179,
				    0x617a,
				    0x617b,
				    0x617c,
				    0x617d,
				    0x617e,
				    0x617f,
				    0x6180,
				    0x6181,
				    0x6182,
				    0x6183,
				    0x6184,
				    0x6185,
				    0x6186,
				    0x6187,
				    0x6188,
				    0x6189,
				    0x618a,
				    0x618b,
				    0x6167,
				    0x6168,
				    0x6169,
				    0x616a,
				    0x616b,
				    0x616c,
				    0x616d,
				    0x616e,
				    0x616f,
				    0x0E34,
				    0x6001,
				    0x14fb,
				    0x0F0E,
				    0x1f14,
				    0x0de1,
				    0x0e21,
				    0x181d,
				    0x181e,
				    0x181f,
				    0x1821,
				    0x1822,
				    0x1823,
				    0x1824,
				    0x1825,
				    0x1826,
				    0x1827,
				    0x1828,
				    0xd05c,
				    0xd05d,
				    0xd05e,
				    0xd05f,
				    0xd060,
				    0xd061,
				    0xd062,
				    0xd063,
				    0xd064,
				    0xd065,
				    0xd066,
				    0xd067,
				    0xd068,
				    0xd069,
				    0xd06a,
				    0xd06d,
				    0xd096,
				    0xd07d,
				    0xd095,
				    0xd071,
				    0xd094,
				    0xd087,
				    0xd097,
				    0xd06e,
				    0xd08f,
				    0xd08b,
				    0xd078,
				    0xd07e,
				    0xd092,
				    0xd093,
				    0xd079,
				    0xd06c,
				    0xd07c,
				    0xd083,
				    0xd06f,
				    0xd085,
				    0xd09a,
				    0xd086,
				    0xd072,
				    0xd080,
				    0xd089,
				    0xd075,
				    0xd082,
				    0xd070,
				    0xd073,
				    0xd074,
				    0xd077,
				    0xd098,
				    0xd099,
				    0xd08e,
				    0xd091,
				    0xd07a,
				    0xd081,
				    0xd084,
				    0xd08a,
				    0xd088,
				    0xd08d,
				    0xd09b,
				    0xd076,
				    0xd07f,
				    0xd09c,
				    0xd090,
				    0xf022,
				    0xf025,
				    0xf028,
				    0xf029,
				    0xd08c,
				    0xd07b /*
		0x1f2d,0x1f2e,0x1f2f,0x1f30,0x1f31,0x1f32,0x1f33,0x1f34,0x1f35,0x1f36,0x1f37,0x1f38,
		0x1f39,0x1f3a,0x1f3b,0x1f3c,0x1f3d,0x1f3e,0x1f3f,0x1f40,0x1f41,0x1f42,0x1f43,0x1f44,
		0x1f45,0x1f46,0x1f47,0x1f48,0x1f49,0x1f4a,0x1f4b,0x1f4c,0x1f4d,0x1f4e,0x1f4f,0x1f50,
		0x1f51,0x1f52,0x1f53,0x1f54,0x1f55,0x1f56,0x1f57,0x1f58,0x1f59,0x1f5a,0x1f5b,0x1f5c,
		0x1f5d,0x1f5e,0x1f5f,0x1f60,0x1f61,0x1f62,0x1f63,0x1f64,0x1f65,0x1f66,0x1f67,0x1f68,
		0x1f69,0x1f6a,0x1f6b,0x1f6c,
		spellbook
*/
				 };

  while ( what )

	if ( what.serial != who.backpack.serial and !IsInContainer( who.backpack, what ) )
	  // print("what.serial:" + what.serial);
	  // print("what.name:" + what.name);
	  // print("whobackpackname:" + who.backpack.name);
	  // print("whopbackpackserial:" + who.backpack.serial);
	  SendSysmessage( who, "That item has to be in your backpack." );
	  return;
	endif

	SendSysMessage( who, "Press ESC if you want to cancel the cursor.." );

	if ( what.isa( POLCLASS_CONTAINER ) )

	  var max_count := 0;
	  foreach thing in EnumerateItemsInContainer( what )
		if ( max_count > 50 )
		  break;
		endif
		if ( thing.objtype in obbjtype ) // objtype у thing.objtype - правильный атрибут типа вещи?
		  store_collection_item( who, thing, item );
		  max_count++;
		endif
	  endforeach

	elseif ( what.objtype in obbjtype )
	  store_collection_item( who, what, item );
	// print("whatobjtype: " + what.objtype);
	// print("itemtype:" + GetObjProperty(what, "itemtype"));
	// print("whatname:" + what.name);
	else
	  SendSysMessage( who, "This is the wrong item." );
	// print("whatobjtype: " + what.objtype);
	// print("whatname:" + what.name);
	endif

	what := Target( who, TGTOPT_CHECK_LOS );
  endwhile
endfunction

function IsInContainer( container, item )

  foreach thing in EnumerateItemsInContainer( container, ENUMERATE_ROOT_ONLY )
	if ( thing.serial == item.serial )
	  return 1;
	endif
  endforeach

  return 0;

endfunction
